# 頻出単語の追加定義（辞書にない一般的な単語）
COMMON_WORDS = {
    # 超頻出語
    'work': '仕事・働く', 'works': '仕事・働く（複数形）', 'working': '働いている',
    'time': '時間', 'times': '時間（複数形）',
    'world': '世界', 'worlds': '世界（複数形）',
    'important': '重要な',
    'culture': '文化', 'cultures': '文化（複数形）', 'cultural': '文化の',
    'environmental': '環境の',
    'diversity': '多様性',
    'healthy': '健康な', 'health': '健康',
    'waste': '廃棄物・無駄', 'wasted': '無駄にされた',
    'sustainable': '持続可能な', 'sustainability': '持続可能性',
    'impact': '影響', 'impacts': '影響（複数形）',
    'job': '仕事', 'jobs': '仕事（複数形）',
    'product': '製品', 'products': '製品（複数形）',
    'efficiency': '効率', 'efficient': '効率的な',
    'difference': '違い', 'differences': '違い（複数形）', 'different': '異なる',
    'emission': '排出', 'emissions': '排出（複数形）',
    'responsibility': '責任', 'responsible': '責任のある',
    'choice': '選択', 'choices': '選択（複数形）',
    'pollution': '汚染', 'pollute': '汚染する',
    'building': '建物', 'buildings': '建物（複数形）',
    'perspective': '視点', 'perspectives': '視点（複数形）',
    'transition': '移行',
    'made': '作られた',
    'well': 'よく',
    'service': 'サービス', 'services': 'サービス（複数形）',
    'decision': '決定', 'decisions': '決定（複数形）',
    'society': '社会', 'societies': '社会（複数形）',
    'generation': '世代', 'generations': '世代（複数形）',
    'panel': 'パネル', 'panels': 'パネル（複数形）',
    'way': '方法', 'ways': '方法（複数形）',
    
    # 追加の重要語
    '3d': '3D・三次元',
    'abandoned': '放棄された',
    'abnormalities': '異常（複数形）',
    'abroad': '海外で',
    'abuse': '虐待・乱用',
    'academically': '学業的に',
    'accidents': '事故（複数形）',
    'accommodation': '宿泊施設',
    'acidification': '酸性化',
    'acknowledgment': '承認',
    'afterlife': '来世',
    'agencies': '機関（複数形）',
    'agency': '機関',
    'agreements': '合意（複数形）',
    'aid': '援助',
    'aids': '援助（複数形）',
    'alertness': '警戒',
    'algorithms': 'アルゴリズム（複数形）',
    'ammonia': 'アンモニア',
    'analytics': '分析',
    'ancestry': '祖先',
    'anemia': '貧血',
    'animations': 'アニメーション（複数形）',
    'anything': '何でも',
    'anytime': 'いつでも',
    'apprenticeships': '徒弟制度（複数形）',
    'area': '地域・領域',
    'areas': '地域・領域（複数形）',
    'around': '周りに',
    'assimilation': '同化',
    'ate': '食べた',
    'attacker': '攻撃者',
    'attitudinal': '態度の',
    'authentically': '本物らしく',
    'authoritarian': '権威主義の',
    'automated': '自動化された',
    'automatically': '自動的に',
    'avocados': 'アボカド（複数形）',
    'backsliding': '後退',
    'bacterial': '細菌の',
    'banana': 'バナナ',
    'baseball': '野球',
    'basketball': 'バスケットボール',
    'bath': 'お風呂',
    'bathroom': '浴室',
    'beach': 'ビーチ',
    'beans': '豆（複数形）',
    'beautiful': '美しい',
    
    # さらに追加
    'ability': '能力',
    'achieve': '達成する',
    'action': '行動', 'actions': '行動（複数形）',
    'active': '活動的な',
    'activity': '活動', 'activities': '活動（複数形）',
    'actual': '実際の', 'actually': '実際に',
    'address': '対処する・住所',
    'advanced': '高度な',
    'advantage': '利点',
    'affect': '影響を与える',
    'agree': '同意する', 'agreement': '合意',
    'allow': '許可する',
    'already': 'すでに',
    'although': '〜だけれども',
    'always': 'いつも',
    'among': '〜の間で',
    'analysis': '分析',
    'approach': 'アプローチ・方法',
    'appropriate': '適切な',
    'attention': '注意',
    'attitude': '態度',
    'available': '利用可能な',
    'average': '平均',
    'avoid': '避ける',
    'aware': '気づいている',
    'awareness': '意識',
    'balance': 'バランス',
    'base': '基礎',
    'basic': '基本的な',
    'basis': '基礎',
    'behavior': '行動',
    'belief': '信念',
    'benefit': '利益',
    'beyond': '〜を超えて',
    'border': '国境',
    'capacity': '能力・容量',
    'cause': '原因',
    'century': '世紀',
    'challenge': '課題・挑戦', 'challenges': '課題・挑戦（複数形）',
    'character': '性格・文字',
    'citizen': '市民', 'citizens': '市民（複数形）',
    'climate': '気候',
    'common': '一般的な',
    'communicate': 'コミュニケーションする', 'communication': 'コミュニケーション',
    'community': 'コミュニティ', 'communities': 'コミュニティ（複数形）',
    'compare': '比較する', 'comparison': '比較',
    'complex': '複雑な',
    'concept': '概念',
    'concern': '懸念',
    'condition': '条件・状態', 'conditions': '条件・状態（複数形）',
    'connect': '接続する', 'connection': '接続',
    'consider': '考慮する',
    'consume': '消費する', 'consumption': '消費',
    'content': '内容',
    'context': '文脈',
    'continue': '続ける',
    'contribute': '貢献する', 'contribution': '貢献',
    'control': '制御',
    'cooperation': '協力',
    'cost': '費用', 'costs': '費用（複数形）',
    'create': '創造する', 'creation': '創造',
    'crisis': '危機',
    'critical': '批判的な',
    'current': '現在の',
    'custom': '習慣', 'customs': '習慣（複数形）',
    'daily': '毎日の',
    'data': 'データ',
    'deal': '取引・対処する',
    'decade': '10年',
    'define': '定義する', 'definition': '定義',
    'depend': '依存する', 'dependent': '依存している',
    'design': 'デザイン',
    'detail': '詳細', 'details': '詳細（複数形）',
    'develop': '発展させる', 'development': '発展',
    'device': '装置', 'devices': '装置（複数形）',
    'digital': 'デジタルの',
    'direct': '直接的な', 'directly': '直接的に',
    'discover': '発見する', 'discovery': '発見',
    'discuss': '議論する', 'discussion': '議論',
    'disease': '病気', 'diseases': '病気（複数形）',
    'economy': '経済', 'economic': '経済的な',
    'effective': '効果的な',
    'effort': '努力', 'efforts': '努力（複数形）',
    'element': '要素', 'elements': '要素（複数形）',
    'enable': '可能にする',
    'encourage': '奨励する',
    'energy': 'エネルギー',
    'engage': '従事する', 'engagement': '従事',
    'ensure': '確実にする',
    'entire': '全体の',
    'environment': '環境', 'environments': '環境（複数形）',
    'equal': '平等な', 'equality': '平等',
    'equipment': '設備',
    'essential': '不可欠な',
    'establish': '確立する',
    'event': '出来事', 'events': '出来事（複数形）',
    'eventually': '最終的に',
    'evidence': '証拠',
    'exactly': '正確に',
    'examine': '調べる',
    'exchange': '交換',
    'exist': '存在する', 'existence': '存在',
    'expand': '拡大する', 'expansion': '拡大',
    'expect': '期待する', 'expectation': '期待',
    'experience': '経験', 'experiences': '経験（複数形）',
    'expert': '専門家', 'experts': '専門家（複数形）',
    'explain': '説明する', 'explanation': '説明',
    'explore': '探索する', 'exploration': '探索',
    'express': '表現する', 'expression': '表現',
    'extend': '延長する',
    'extent': '範囲',
    'factor': '要因', 'factors': '要因（複数形）',
    'fail': '失敗する', 'failure': '失敗',
    'fair': '公正な',
    'feature': '特徴', 'features': '特徴（複数形）',
    'figure': '図・数字',
    'final': '最終的な', 'finally': '最終的に',
    'financial': '財政的な',
    'focus': '焦点',
    'follow': '従う', 'following': '次の',
    'force': '力',
    'foreign': '外国の',
    'form': '形式', 'forms': '形式（複数形）',
    'foundation': '基礎',
    'framework': '枠組み',
    'function': '機能', 'functions': '機能（複数形）',
    'fundamental': '基本的な',
    'furthermore': 'さらに',
    'gain': '得る',
    'gap': 'ギャップ',
    'gender': '性別',
    'global': 'グローバルな',
    'goal': '目標', 'goals': '目標（複数形）',
    'govern': '統治する', 'government': '政府',
    'gradually': '徐々に',
    'growth': '成長',
    'guarantee': '保証',
    'guide': 'ガイド',
    'harm': '害',
    'identity': 'アイデンティティ',
    'ignore': '無視する',
    'illegal': '違法な',
    'image': 'イメージ', 'images': 'イメージ（複数形）',
    'imagine': '想像する',
    'immediate': '即座の', 'immediately': '即座に',
    'improvement': '改善',
    'include': '含む', 'including': '〜を含めて',
    'income': '収入',
    'increase': '増加', 'increasing': '増加している',
    'indeed': '確かに',
    'independent': '独立した',
    'indicate': '示す',
    'individual': '個人', 'individuals': '個人（複数形）',
    'industry': '産業', 'industrial': '産業の',
    'influence': '影響',
    'information': '情報',
    'initial': '初期の',
    'initiative': 'イニシアチブ',
    'innovation': '革新',
    'instance': '例',
    'instead': '代わりに',
    'institution': '機関', 'institutions': '機関（複数形）',
    'instrument': '楽器・器具',
    'integrate': '統合する', 'integration': '統合',
    'intelligence': '知性',
    'intend': '意図する',
    'intense': '激しい',
    'interact': '交流する', 'interaction': '交流',
    'interest': '興味', 'interested': '興味がある', 'interesting': '興味深い',
    'international': '国際的な',
    'interpret': '解釈する', 'interpretation': '解釈',
    'introduce': '紹介する', 'introduction': '紹介',
    'invest': '投資する', 'investment': '投資',
    'involve': '含む', 'involved': '関与している',
    'item': '項目', 'items': '項目（複数形）',
    'justice': '正義',
    'knowledge': '知識',
    'labor': '労働',
    'lack': '欠如',
    'language': '言語', 'languages': '言語（複数形）',
    'largely': '主に',
    'later': '後で',
    'law': '法律', 'laws': '法律（複数形）',
    'layer': '層',
    'lead': '導く', 'leader': 'リーダー', 'leadership': 'リーダーシップ',
    'legal': '法的な',
    'legislation': '立法',
    'leisure': '余暇',
    'length': '長さ',
    'level': 'レベル', 'levels': 'レベル（複数形）',
    'lifestyle': 'ライフスタイル',
    'limit': '制限', 'limited': '制限された',
    'link': 'リンク',
    'local': '地域の',
    'locate': '位置する', 'location': '場所',
    'logical': '論理的な',
    'maintain': '維持する', 'maintenance': '維持',
    'major': '主要な',
    'manage': '管理する', 'management': '管理',
    'manner': '方法',
    'material': '材料', 'materials': '材料（複数形）',
    'matter': '問題',
    'meaning': '意味',
    'means': '手段',
    'measure': '測る・手段', 'measurement': '測定',
    'mechanism': 'メカニズム',
    'media': 'メディア',
    'medical': '医療の',
    'mental': '精神的な',
    'mention': '言及する',
    'message': 'メッセージ',
    'method': '方法', 'methods': '方法（複数形）',
    'middle': '中間',
    'migrate': '移住する', 'migration': '移住',
    'military': '軍事の',
    'minority': '少数派',
    'mission': '使命',
    'mix': '混合する', 'mixed': '混合された',
    'mobile': 'モバイルの',
    'model': 'モデル', 'models': 'モデル（複数形）',
    'modern': '現代の',
    'modify': '修正する', 'modification': '修正',
    'monitor': '監視する',
    'moreover': 'さらに',
    'motivate': '動機づける', 'motivation': '動機',
    'movement': '運動', 'movements': '運動（複数形）',
    'nation': '国', 'national': '国家の', 'nations': '国（複数形）',
    'native': 'ネイティブの',
    'natural': '自然な', 'naturally': '自然に', 'nature': '自然',
    'necessarily': '必然的に',
    'necessary': '必要な',
    'need': '必要', 'needs': '必要（複数形）',
    'negative': '否定的な',
    'network': 'ネットワーク', 'networks': 'ネットワーク（複数形）',
    'neutral': '中立の',
    'nevertheless': 'それにもかかわらず',
    'normal': '通常の', 'normally': '通常は',
    'notice': '気づく',
    'notion': '概念',
    'objective': '目的',
    'obtain': '得る',
    'obvious': '明白な', 'obviously': '明らかに',
    'occasion': '機会',
    'occur': '起こる',
    'offer': '提供する',
    'official': '公式の',
    'operate': '操作する', 'operation': '操作',
    'opportunity': '機会', 'opportunities': '機会（複数形）',
    'oppose': '反対する', 'opposite': '反対の',
    'option': '選択肢', 'options': '選択肢（複数形）',
    'order': '順序・注文',
    'organize': '組織する', 'organization': '組織',
    'origin': '起源', 'original': '元の',
    'otherwise': 'そうでなければ',
    'outcome': '結果', 'outcomes': '結果（複数形）',
    'output': '出力',
    'overall': '全体的な',
    'participate': '参加する', 'participation': '参加',
    'particular': '特定の', 'particularly': '特に',
    'partner': 'パートナー', 'partnership': 'パートナーシップ',
    'pattern': 'パターン', 'patterns': 'パターン（複数形）',
    'period': '期間',
    'permit': '許可する',
    'person': '人', 'personal': '個人的な', 'personality': '性格',
    'philosophy': '哲学',
    'physical': '物理的な', 'physically': '物理的に',
    'place': '場所', 'places': '場所（複数形）',
    'plan': '計画', 'planning': '計画',
    'plus': '加えて',
    'point': '点',
    'policy': '政策', 'policies': '政策（複数形）',
    'political': '政治的な', 'politics': '政治',
    'population': '人口',
    'position': '位置・立場',
    'positive': 'ポジティブな',
    'possibility': '可能性',
    'potential': '潜在的な',
    'poverty': '貧困',
    'practical': '実用的な', 'practice': '実践', 'practices': '実践（複数形）',
    'predict': '予測する', 'prediction': '予測',
    'prefer': '好む', 'preference': '好み',
    'prepare': '準備する', 'preparation': '準備',
    'presence': '存在',
    'present': '現在の・提示する', 'presentation': 'プレゼンテーション',
    'preserve': '保存する', 'preservation': '保存',
    'pressure': '圧力',
    'prevent': '防ぐ', 'prevention': '防止',
    'previous': '以前の', 'previously': '以前に',
    'primary': '主要な', 'primarily': '主に',
    'principle': '原則', 'principles': '原則（複数形）',
    'prior': '前の',
    'priority': '優先事項',
    'private': '私的な',
    'procedure': '手順',
    'process': '過程', 'processes': '過程（複数形）',
    'produce': '生産する', 'producer': '生産者', 'production': '生産',
    'professional': 'プロフェッショナルの',
    'profit': '利益',
    'progress': '進歩',
    'project': 'プロジェクト', 'projects': 'プロジェクト（複数形）',
    'promote': '促進する', 'promotion': '促進',
    'proper': '適切な', 'properly': '適切に',
    'property': '財産',
    'proportion': '割合',
    'proposal': '提案',
    'protect': '保護する', 'protection': '保護',
    'prove': '証明する',
    'provide': '提供する',
    'public': '公共の',
    'publish': '出版する',
    'purchase': '購入する',
    'purpose': '目的',
    'pursue': '追求する',
    'quality': '質',
    'quantity': '量',
    'question': '質問',
    'quote': '引用する',
    'race': '人種・競争',
    'range': '範囲',
    'rapid': '急速な', 'rapidly': '急速に',
    'rare': 'まれな', 'rarely': 'めったに〜ない',
    'rate': '率',
    'react': '反応する', 'reaction': '反応',
    'realize': '実現する',
    'reason': '理由', 'reasonable': '合理的な',
    'recent': '最近の', 'recently': '最近',
    'recognize': '認識する', 'recognition': '認識',
    'recommend': '推薦する', 'recommendation': '推薦',
    'record': '記録',
    'recover': '回復する', 'recovery': '回復',
    'reduce': '減らす', 'reduction': '減少',
    'refer': '参照する', 'reference': '参照',
    'reflect': '反映する', 'reflection': '反映',
    'reform': '改革',
    'regard': '関して', 'regarding': '〜に関して',
    'region': '地域', 'regional': '地域の',
    'register': '登録する', 'registration': '登録',
    'regulate': '規制する', 'regulation': '規制',
    'reject': '拒否する', 'rejection': '拒否',
    'relate': '関連する', 'relation': '関係', 'relationship': '関係',
    'relative': '相対的な', 'relatively': '比較的',
    'release': '解放する',
    'relevant': '関連した',
    'reliable': '信頼できる',
    'relief': '安心・救済',
    'rely': '頼る',
    'remain': '残る', 'remaining': '残りの',
    'remark': '発言',
    'remove': '取り除く',
    'renewable': '再生可能な',
    'repair': '修理する',
    'repeat': '繰り返す',
    'replace': '置き換える', 'replacement': '置き換え',
    'report': '報告', 'reporter': '記者',
    'represent': '代表する', 'representation': '表現', 'representative': '代表者',
    'request': '要求',
    'require': '必要とする', 'requirement': '要件',
    'research': '研究', 'researcher': '研究者',
    'reserve': '予約する・保護区',
    'residence': '住居', 'resident': '住民',
    'resist': '抵抗する', 'resistance': '抵抗',
    'resolution': '解決',
    'resolve': '解決する',
    'resource': '資源', 'resources': '資源（複数形）',
    'respect': '尊敬', 'respectful': '敬意を持った',
    'respond': '応答する', 'response': '応答',
    'restore': '復元する', 'restoration': '復元',
    'restrict': '制限する', 'restriction': '制限',
    'result': '結果', 'results': '結果（複数形）',
    'retain': '保持する',
    'reveal': '明らかにする',
    'revenue': '収入',
    'review': 'レビュー',
    'revise': '修正する', 'revision': '修正',
    'revolution': '革命', 'revolutionary': '革命的な',
    'reward': '報酬',
    'risk': 'リスク',
    'role': '役割', 'roles': '役割（複数形）',
    'route': 'ルート',
    'routine': '日常',
    'rule': 'ルール', 'rules': 'ルール（複数形）',
    'rural': '農村の',
    'scale': '規模',
    'scene': '場面',
    'schedule': 'スケジュール',
    'scheme': '計画',
    'scope': '範囲',
    'section': 'セクション',
    'sector': 'セクター',
    'secure': '安全な', 'security': '安全',
    'seek': '探す',
    'segment': 'セグメント',
    'select': '選択する', 'selection': '選択',
    'sense': '感覚',
    'sensitive': '敏感な',
    'separate': '分離する', 'separation': '分離',
    'sequence': '順序',
    'series': 'シリーズ',
    'serious': '深刻な', 'seriously': '真剣に',
    'session': 'セッション',
    'setting': '設定',
    'settle': '定住する', 'settlement': '定住',
    'severe': '厳しい',
    'share': '共有する', 'shared': '共有された',
    'shift': 'シフト',
    'significant': '重要な', 'significance': '重要性', 'significantly': '著しく',
    'similar': '似ている', 'similarly': '同様に', 'similarity': '類似性',
    'simple': 'シンプルな', 'simply': '単に', 'simplicity': 'シンプルさ',
    'site': 'サイト', 'sites': 'サイト（複数形）',
    'situation': '状況', 'situations': '状況（複数形）',
    'size': 'サイズ',
    'skill': 'スキル', 'skills': 'スキル（複数形）', 'skilled': '熟練した',
    'slightly': 'わずかに',
    'social': '社会的な', 'socially': '社会的に',
    'software': 'ソフトウェア',
    'solution': '解決策', 'solutions': '解決策（複数形）',
    'solve': '解決する',
    'somewhat': 'いくらか',
    'source': '源', 'sources': '源（複数形）',
    'southern': '南の',
    'space': '空間',
    'speak': '話す', 'speaker': '話者', 'speaking': '話すこと',
    'special': '特別な', 'specialist': '専門家', 'specialize': '専門化する',
    'specific': '特定の', 'specifically': '特に',
    'speed': '速度',
    'spend': '費やす', 'spending': '支出',
    'spirit': '精神', 'spiritual': '精神的な',
    'spread': '広がる',
    'stable': '安定した', 'stability': '安定性',
    'staff': 'スタッフ',
    'stage': 'ステージ',
    'standard': '基準', 'standards': '基準（複数形）',
    'start': '始める',
    'state': '状態・州', 'statement': '声明',
    'status': '状態',
    'step': 'ステップ', 'steps': 'ステップ（複数形）',
    'store': '店・保存する', 'storage': '保存',
    'story': '物語', 'stories': '物語（複数形）',
    'straight': 'まっすぐな',
    'strange': '奇妙な',
    'strategic': '戦略的な', 'strategy': '戦略',
    'stream': '流れ',
    'strength': '強さ', 'strengthen': '強化する',
    'stress': 'ストレス',
    'strict': '厳格な',
    'structure': '構造', 'structural': '構造的な',
    'struggle': '闘争',
    'stuff': 'もの',
    'style': 'スタイル',
    'subject': '主題',
    'submit': '提出する',
    'subsequent': '後続の', 'subsequently': 'その後',
    'substance': '物質',
    'substantial': '実質的な',
    'succeed': '成功する', 'success': '成功', 'successful': '成功した',
    'sufficient': '十分な',
    'suggest': '提案する', 'suggestion': '提案',
    'suitable': '適切な',
    'sum': '合計',
    'summary': '要約',
    'supply': '供給', 'supplies': '供給（複数形）',
    'support': '支援', 'supportive': '支援的な',
    'suppose': '仮定する',
    'surface': '表面',
    'survey': '調査',
    'survive': '生き残る', 'survival': '生存',
    'symbol': 'シンボル', 'symbolic': '象徴的な',
    'system': 'システム', 'systems': 'システム（複数形）', 'systematic': '体系的な',
    'target': 'ターゲット',
    'task': 'タスク', 'tasks': 'タスク（複数形）',
    'tax': '税',
    'team': 'チーム', 'teams': 'チーム（複数形）',
    'technical': '技術的な', 'technique': '技術', 'technology': '技術',
    'tend': '傾向がある', 'tendency': '傾向',
    'term': '用語', 'terms': '用語（複数形）',
    'territory': '領土',
    'text': 'テキスト',
    'theme': 'テーマ', 'themes': 'テーマ（複数形）',
    'theory': '理論', 'theoretical': '理論的な',
    'therefore': 'したがって',
    'threat': '脅威',
    'threaten': '脅かす',
    'thus': 'したがって',
    'topic': 'トピック',
    'total': '合計', 'totally': '完全に',
    'tough': '困難な',
    'track': '追跡する',
    'tradition': '伝統', 'traditional': '伝統的な',
    'train': '訓練する', 'training': '訓練',
    'transfer': '転送する',
    'transform': '変換する', 'transformation': '変換',
    'transport': '輸送', 'transportation': '輸送',
    'treat': '扱う', 'treatment': '治療',
    'trend': '傾向',
    'trial': '試験',
    'trigger': '引き金',
    'trip': '旅行',
    'trust': '信頼',
    'truth': '真実',
    'turn': '回転・順番',
    'type': '種類', 'types': '種類（複数形）',
    'typical': '典型的な', 'typically': '典型的に',
    'ultimate': '最終的な', 'ultimately': '最終的に',
    'unable': '不可能な',
    'understanding': '理解',
    'undertake': '引き受ける',
    'unemployment': '失業',
    'unexpected': '予期しない',
    'unfortunately': '残念ながら',
    'unique': 'ユニークな',
    'unit': '単位', 'units': '単位（複数形）',
    'universal': '普遍的な',
    'universe': '宇宙',
    'university': '大学',
    'unknown': '未知の',
    'unlike': '〜と異なり',
    'unlikely': 'ありそうにない',
    'urban': '都市の',
    'usage': '使用法',
    'useful': '有用な',
    'user': 'ユーザー', 'users': 'ユーザー（複数形）',
    'usual': '通常の', 'usually': '通常',
    'utility': '有用性',
    'utilize': '利用する',
    'valid': '有効な',
    'valuable': '貴重な', 'value': '価値', 'values': '価値（複数形）',
    'variable': '変数',
    'variation': '変化',
    'variety': '多様性', 'various': '様々な',
    'vast': '広大な',
    'vehicle': '車両', 'vehicles': '車両（複数形）',
    'version': 'バージョン',
    'via': '経由して',
    'victim': '被害者',
    'view': '見解', 'views': '見解（複数形）',
    'violence': '暴力', 'violent': '暴力的な',
    'virtual': '仮想の', 'virtually': '事実上',
    'virtue': '美徳',
    'visible': '見える',
    'vision': 'ビジョン',
    'visit': '訪問', 'visitor': '訪問者',
    'visual': '視覚的な',
    'vital': '極めて重要な',
    'voice': '声',
    'volume': '音量・巻',
    'voluntary': '自発的な', 'volunteer': 'ボランティア',
    'vote': '投票', 'voter': '投票者', 'voting': '投票',
    'vulnerable': '脆弱な',
    'wage': '賃金',
    'warn': '警告する', 'warning': '警告',
    'wealth': '富', 'wealthy': '裕福な',
    'weapon': '武器',
    'weather': '天気',
    'welfare': '福祉',
    'western': '西の',
    'whenever': 'いつでも',
    'whereas': '一方で',
    'whether': '〜かどうか',
    'widespread': '広範な',
    'willing': '喜んで',
    'wisdom': '知恵',
    'wise': '賢い',
    'within': '〜以内に',
    'witness': '目撃者',
    'wonder': '不思議に思う',
    'worth': '価値がある',
    'worthy': '価値のある',
    'wound': '傷',
    'wrap': '包む',
    'wrong': '間違った',
    'yield': '譲る・産出する',
    'zone': 'ゾーン',
}
