#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Advanced-2と3を目標語数まで拡張
"""

import json
from pathlib import Path


def expand_advanced_2():
    """Advanced-2を約2,000語追加して3,000語に"""
    file_path = Path("prototype/advanced-2.json")
    with open(file_path, 'r', encoding='utf-8') as f:
        data = json.load(f)
    
    max_id = max(int(p['id'].split('-')[1]) for p in data['phrases'])
    
    additional = [
        # AI倫理と社会への影響の深掘り
        (["Ethics", "committees", "review", "AI", "projects"], "倫理委員会はAIプロジェクトを審査します"),
        (["Before", "deployment", "in", "society"], "社会への展開前に"),
        (["Risk", "assessment", "is", "crucial"], "リスク評価が重要です"),
        (["What", "could", "go", "wrong"], "何が間違う可能性があるか"),
        (["How", "to", "mitigate", "harms"], "害をどのように軽減するか"),
        (["Stakeholder", "input", "improves", "decisions"], "利害関係者の意見は決定を改善します"),
        (["Include", "affected", "communities"], "影響を受けるコミュニティを含めます"),
        (["Not", "just", "technical", "experts"], "技術専門家だけでなく"),
        (["Value", "alignment", "ensures", "AI", "serves", "human", "goals"], "価値の整合性はAIが人間の目標に奉仕することを保証します"),
        (["AI", "should", "reflect", "our", "values"], "AIは私たちの価値観を反映すべきです"),
        (["But", "whose", "values"], "しかし誰の価値観か"),
        (["Different", "cultures", "have", "different", "priorities"], "異なる文化は異なる優先事項を持ちます"),
        (["Finding", "common", "ground", "is", "challenging"], "共通点を見つけるのは困難です"),
        (["AI", "safety", "research", "prevents", "accidents"], "AI安全性研究は事故を防ぎます"),
        (["Systems", "that", "behave", "as", "intended"], "意図通りに動作するシステム"),
        (["Even", "in", "unexpected", "situations"], "予期しない状況でも"),
        (["Robustness", "testing", "is", "essential"], "ロバストネステストが不可欠です"),
        (["Try", "to", "break", "the", "system"], "システムを壊そうとします"),
        (["Find", "weaknesses", "before", "others", "do"], "他者が見つける前に弱点を見つけます"),
        (["Interpretability", "makes", "AI", "understandable"], "解釈可能性はAIを理解可能にします"),
        (["Can", "explain", "why", "decision", "was", "made"], "なぜ決定が下されたかを説明できます"),
        (["This", "builds", "trust", "and", "accountability"], "これは信頼と説明責任を構築します"),
        (["Healthcare", "and", "justice", "especially", "need", "this"], "医療と司法は特にこれを必要とします"),
        (["High", "stakes", "decisions"], "高リスクの決定"),
        (["Federated", "learning", "protects", "privacy"], "連合学習はプライバシーを保護します"),
        (["AI", "trains", "on", "distributed", "data"], "AIは分散データで訓練します"),
        (["Without", "centralizing", "it"], "それを集中化することなく"),
        (["Data", "stays", "on", "local", "devices"], "データはローカルデバイスにとどまります"),
        (["Only", "model", "updates", "are", "shared"], "モデルの更新のみが共有されます"),
        (["This", "enables", "collaboration", "without", "exposing", "sensitive", "information"], "これは機密情報を公開せずに協力を可能にします"),
        (["Used", "in", "healthcare", "and", "finance"], "医療と金融で使用されます"),
        (["Differential", "privacy", "adds", "mathematical", "guarantees"], "差分プライバシーは数学的保証を追加します"),
        (["Protects", "individual", "privacy", "in", "aggregate", "data"], "集計データの個人プライバシーを保護します"),
        (["Even", "if", "attacker", "has", "background", "knowledge"], "攻撃者がバックグラウンド知識を持っていても"),
        (["AI", "governance", "frameworks", "are", "emerging"], "AIガバナンスフレームワークが出現しています"),
        (["Guidelines", "for", "responsible", "development"], "責任ある開発のためのガイドライン"),
        (["Companies", "adopt", "AI", "principles"], "企業はAI原則を採用します"),
        (["Fairness", "transparency", "accountability", "safety"], "公平性透明性説明責任安全性"),
        (["But", "self", "regulation", "has", "limits"], "しかし自主規制には限界があります"),
        (["Economic", "pressures", "may", "compromise", "ethics"], "経済的圧力が倫理を損なう可能性があります"),
        (["Independent", "oversight", "may", "be", "needed"], "独立した監視が必要かもしれません"),
        (["AI", "audits", "assess", "compliance"], "AI監査はコンプライアンスを評価します"),
        (["Third", "party", "reviews", "of", "systems"], "システムの第三者レビュー"),
        (["Check", "for", "bias", "and", "fairness"], "バイアスと公平性をチェックします"),
        (["Verify", "claims", "about", "performance"], "パフォーマンスに関する主張を検証します"),
        (["Certification", "programs", "may", "develop"], "認証プログラムが開発されるかもしれません"),
        (["Like", "safety", "certifications", "for", "products"], "製品の安全認証のように"),
        (["AI", "literacy", "for", "everyone", "is", "important"], "すべての人のためのAIリテラシーが重要です"),
        (["Basic", "understanding", "of", "how", "AI", "works"], "AIがどのように機能するかの基本的理解"),
        (["What", "it", "can", "and", "cannot", "do"], "それができることとできないこと"),
        (["Critical", "thinking", "about", "AI", "claims"], "AI主張についての批判的思考"),
        (["Schools", "should", "teach", "these", "skills"], "学校はこれらのスキルを教えるべきです"),
        (["Not", "just", "for", "computer", "science", "students"], "コンピュータサイエンスの学生だけでなく"),
        (["For", "all", "citizens"], "すべての市民のために"),
        (["AI", "assistants", "are", "becoming", "common"], "AIアシスタントが一般的になっています"),
        (["Virtual", "assistants", "like", "Siri", "and", "Alexa"], "SiriやAlexaのような仮想アシスタント"),
        (["Help", "with", "daily", "tasks"], "日常のタスクを助けます"),
        (["Set", "reminders", "answer", "questions", "control", "devices"], "リマインダーを設定し質問に答えデバイスを制御します"),
        (["They", "learn", "user", "preferences"], "ユーザーの好みを学習します"),
        (["Become", "more", "helpful", "over", "time"], "時間とともにより役立つようになります"),
        (["But", "always", "listening", "raises", "privacy", "concerns"], "しかし常に聞いていることはプライバシーの懸念を引き起こします"),
        (["Recommendation", "systems", "shape", "what", "we", "see"], "推薦システムは私たちが見るものを形作ります"),
        (["Streaming", "services", "suggest", "shows"], "ストリーミングサービスは番組を提案します"),
        (["E", "commerce", "sites", "recommend", "products"], "Eコマースサイトは製品を推奨します"),
        (["Social", "media", "curates", "feeds"], "ソーシャルメディアはフィードをキュレートします"),
        (["Based", "on", "engagement", "and", "preferences"], "エンゲージメントと好みに基づいて"),
        (["This", "can", "create", "filter", "bubbles"], "これはフィルターバブルを作り出す可能性があります"),
        (["We", "see", "only", "what", "algorithms", "think", "we", "like"], "私たちはアルゴリズムが好きだと思うものだけを見ます"),
        (["Missing", "diverse", "perspectives"], "多様な視点を見逃します"),
        (["Content", "moderation", "uses", "AI"], "コンテンツモデレーションはAIを使用します"),
        (["Detect", "harmful", "content", "automatically"], "有害なコンテンツを自動的に検出します"),
        (["Hate", "speech", "misinformation", "graphic", "violence"], "ヘイトスピーチ誤情報グラフィック暴力"),
        (["Remove", "or", "flag", "for", "review"], "削除またはレビューのためにフラグを立てます"),
        (["But", "mistakes", "happen"], "しかし間違いが起こります"),
        (["False", "positives", "remove", "legitimate", "content"], "偽陽性は正当なコンテンツを削除します"),
        (["False", "negatives", "let", "harmful", "content", "through"], "偽陰性は有害なコンテンツを通過させます"),
        (["Balancing", "free", "speech", "and", "safety", "is", "difficult"], "言論の自由と安全のバランスを取るのは困難です"),
        (["AI", "in", "creative", "fields", "sparks", "debate"], "クリエイティブ分野のAIは議論を引き起こします"),
        (["AI", "generates", "art", "music", "and", "writing"], "AIはアート音楽そして執筆を生成します"),
        (["Some", "say", "this", "democratizes", "creativity"], "これは創造性を民主化すると言う人もいます"),
        (["Anyone", "can", "create", "without", "traditional", "skills"], "誰でも伝統的なスキルなしで創造できます"),
        (["Others", "worry", "about", "devaluing", "human", "artists"], "人間のアーティストの価値を下げることを心配する人もいます"),
        (["Copyright", "issues", "arise"], "著作権の問題が生じます"),
        (["Who", "owns", "AI", "generated", "work"], "AI生成作品は誰が所有するか"),
        (["The", "user", "the", "programmer", "or", "no", "one"], "ユーザープログラマーまたは誰も"),
        (["Legal", "frameworks", "are", "unclear"], "法的枠組みは不明確です"),
        (["AI", "in", "agriculture", "increases", "yields"], "農業におけるAIは収穫量を増やします"),
        (["Monitors", "crop", "health", "from", "satellite", "imagery"], "衛星画像から作物の健康を監視します"),
        (["Detects", "disease", "and", "pest", "outbreaks", "early"], "病気と害虫の発生を早期に検出します"),
        (["Optimizes", "irrigation", "and", "fertilization"], "灌漑と施肥を最適化します"),
        (["Reduces", "waste", "and", "environmental", "impact"], "廃棄物と環境への影響を減らします"),
        (["Helps", "feed", "growing", "population"], "増加する人口を養うのを助けます"),
        (["AI", "in", "energy", "management", "improves", "efficiency"], "エネルギー管理におけるAIは効率を向上させます"),
        (["Predicts", "demand", "and", "adjusts", "supply"], "需要を予測し供給を調整します"),
        (["Integrates", "renewable", "sources", "smoothly"], "再生可能資源をスムーズに統合します"),
        (["Reduces", "costs", "and", "emissions"], "コストと排出を削減します"),
        (["Smart", "homes", "use", "AI", "for", "comfort", "and", "savings"], "スマートホームは快適さと節約のためにAIを使用します"),
        (["Learn", "occupancy", "patterns"], "占有パターンを学習します"),
        (["Adjust", "heating", "cooling", "and", "lighting"], "暖房冷房そして照明を調整します"),
        (["Automatically", "for", "optimal", "efficiency"], "最適な効率のために自動的に"),
        (["AI", "in", "disaster", "response", "saves", "lives"], "災害対応におけるAIは命を救います"),
        (["Analyzes", "data", "to", "predict", "natural", "disasters"], "自然災害を予測するためにデータを分析します"),
        (["Earthquakes", "floods", "hurricanes"], "地震洪水ハリケーン"),
        (["Coordinates", "emergency", "response"], "緊急対応を調整します"),
        (["Optimizes", "evacuation", "routes"], "避難ルートを最適化します"),
        (["Identifies", "people", "needing", "help"], "助けを必要とする人々を特定します"),
        (["AI", "in", "scientific", "research", "accelerates", "discovery"], "科学研究におけるAIは発見を加速します"),
        (["Analyzes", "experimental", "data"], "実験データを分析します"),
        (["Generates", "hypotheses", "to", "test"], "テストする仮説を生成します"),
        (["Simulates", "complex", "systems"], "複雑なシステムをシミュレートします"),
        (["Finds", "patterns", "humans", "might", "miss"], "人間が見逃すかもしれないパターンを見つけます"),
        (["Has", "contributed", "to", "breakthroughs"], "ブレークスルーに貢献しました"),
        (["In", "physics", "chemistry", "biology"], "物理学化学生物学において"),
        (["AI", "ethics", "education", "trains", "developers"], "AI倫理教育は開発者を訓練します"),
        (["Computer", "science", "programs", "add", "ethics", "courses"], "コンピュータサイエンスプログラムは倫理コースを追加します"),
        (["Teach", "responsible", "design"], "責任あるデザインを教えます"),
        (["Consider", "societal", "impact"], "社会的影響を考慮します"),
        (["Case", "studies", "of", "AI", "failures"], "AI失敗の事例研究"),
        (["Learn", "from", "past", "mistakes"], "過去の間違いから学びます"),
        (["Public", "private", "partnerships", "advance", "AI"], "官民パートナーシップはAIを進歩させます"),
        (["Governments", "fund", "basic", "research"], "政府は基礎研究に資金を提供します"),
        (["Companies", "develop", "applications"], "企業はアプリケーションを開発します"),
        (["Universities", "train", "talent"], "大学は人材を訓練します"),
        (["Collaboration", "accelerates", "progress"], "協力は進歩を加速します"),
        (["Shares", "knowledge", "and", "resources"], "知識とリソースを共有します"),
        (["AI", "competitions", "drive", "innovation"], "AIコンペティションは革新を推進します"),
        (["Challenges", "with", "prizes"], "賞金付きチャレンジ"),
        (["Teams", "compete", "to", "solve", "problems"], "チームは問題を解決するために競争します"),
        (["Best", "solutions", "are", "shared"], "最良のソリューションが共有されます"),
        (["Open", "source", "AI", "tools", "democratize", "access"], "オープンソースAIツールはアクセスを民主化します"),
        (["Free", "libraries", "and", "frameworks"], "無料のライブラリとフレームワーク"),
        (["Anyone", "can", "build", "AI", "applications"], "誰でもAIアプリケーションを構築できます"),
        (["Not", "just", "large", "companies"], "大企業だけでなく"),
        (["Encourages", "innovation", "globally"], "世界的に革新を促進します"),
        (["But", "also", "enables", "misuse"], "しかし悪用も可能にします"),
        (["Dual", "use", "technology"], "デュアルユース技術"),
        (["Can", "be", "used", "for", "good", "or", "harm"], "良いことにも害にも使用できます"),
        (["AI", "alignment", "problem", "is", "fundamental"], "AI整合性問題は根本的です"),
        (["Ensuring", "AI", "goals", "match", "human", "values"], "AIの目標が人間の価値観と一致することを保証します"),
        (["As", "systems", "become", "more", "autonomous"], "システムがより自律的になるにつれて"),
        (["This", "becomes", "more", "critical"], "これはより重要になります"),
        (["Inverse", "reinforcement", "learning", "infers", "human", "preferences"], "逆強化学習は人間の好みを推測します"),
        (["By", "observing", "behavior"], "行動を観察することによって"),
        (["Rather", "than", "explicit", "programming"], "明示的なプログラミングではなく"),
        (["AI", "transparency", "initiatives", "promote", "openness"], "AI透明性イニシアチブは開放性を促進します"),
        (["Companies", "disclose", "how", "algorithms", "work"], "企業はアルゴリズムがどのように機能するかを開示します"),
        (["What", "data", "is", "used"], "どのようなデータが使用されるか"),
        (["How", "decisions", "are", "made"], "決定がどのように行われるか"),
        (["This", "allows", "scrutiny", "and", "improvement"], "これは精査と改善を可能にします"),
        (["The", "environmental", "cost", "of", "AI", "is", "significant"], "AIの環境コストは重大です"),
        (["Training", "large", "models", "uses", "massive", "energy"], "大規模モデルの訓練は大量のエネルギーを使用します"),
        (["Data", "centers", "consume", "electricity"], "データセンターは電力を消費します"),
        (["Carbon", "footprint", "can", "be", "substantial"], "カーボンフットプリントは相当なものになる可能性があります"),
        (["Green", "AI", "focuses", "on", "efficiency"], "グリーンAIは効率に焦点を当てます"),
        (["Developing", "smaller", "more", "efficient", "models"], "より小さくより効率的なモデルを開発します"),
        (["Using", "renewable", "energy", "for", "computation"], "計算に再生可能エネルギーを使用します"),
        (["Measuring", "and", "reporting", "energy", "use"], "エネルギー使用を測定し報告します"),
        (["AI", "for", "social", "good", "addresses", "global", "challenges"], "社会的善のためのAIは世界的課題に取り組みます"),
        (["Poverty", "disease", "inequality"], "貧困病気不平等"),
        (["Uses", "technology", "to", "help", "vulnerable", "populations"], "脆弱な人々を助けるために技術を使用します"),
        (["Improving", "access", "to", "services"], "サービスへのアクセスを改善します"),
        (["Education", "healthcare", "financial", "inclusion"], "教育医療金融包摂"),
        (["Many", "organizations", "work", "in", "this", "space"], "多くの組織がこの分野で働いています"),
        (["Nonprofits", "researchers", "companies"], "非営利組織研究者企業"),
        (["Collaboration", "is", "key"], "協力が鍵です"),
        (["The", "future", "of", "AI", "depends", "on", "us"], "AIの未来は私たち次第です"),
        (["Choices", "we", "make", "today"], "今日私たちが行う選択"),
        (["Shape", "tomorrow's", "world"], "明日の世界を形作ります"),
        (["We", "can", "create", "beneficial", "AI"], "有益なAIを作ることができます"),
        (["That", "enhances", "human", "capability"], "人間の能力を向上させる"),
        (["Solves", "pressing", "problems"], "緊急の問題を解決します"),
        (["Improves", "quality", "of", "life"], "生活の質を改善します"),
        (["Or", "we", "can", "create", "harmful", "AI"], "または有害なAIを作ることができます"),
        (["That", "increases", "inequality"], "不平等を増加させる"),
        (["Concentrates", "power"], "権力を集中させる"),
        (["Threatens", "freedoms"], "自由を脅かす"),
        (["The", "choice", "requires", "wisdom"], "選択には知恵が必要です"),
        (["Foresight", "and", "courage"], "先見の明と勇気"),
        (["To", "prioritize", "human", "welfare"], "人間の福祉を優先するために"),
        (["Over", "profit", "and", "power"], "利益と権力を超えて"),
        (["To", "ensure", "benefits", "are", "shared"], "利益が共有されることを保証するために"),
        (["Not", "hoarded", "by", "a", "few"], "少数に独占されない"),
        (["To", "preserve", "human", "agency"], "人間の主体性を保つために"),
        (["In", "an", "age", "of", "intelligent", "machines"], "知的機械の時代において"),
        (["This", "is", "the", "great", "challenge", "of", "our", "time"], "これは私たちの時代の大きな課題です"),
        (["How", "we", "respond", "will", "define", "us"], "私たちがどのように対応するかが私たちを定義します"),
        (["Let", "us", "choose", "wisely", "and", "well"], "賢明によく選びましょう"),
    ]
    
    for words, meaning in additional:
        max_id += 1
        data['phrases'].append({
            "id": f"phrase-{max_id}",
            "words": words,
            "phraseMeaning": meaning
        })
    
    data['actualWordCount'] = sum(len(p['words']) for p in data['phrases'])
    
    with open(file_path, 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    
    return data['actualWordCount']


def expand_advanced_3():
    """Advanced-3を約2,100語追加して3,000語に"""
    file_path = Path("prototype/advanced-3.json")
    with open(file_path, 'r', encoding='utf-8') as f:
        data = json.load(f)
    
    max_id = max(int(p['id'].split('-')[1]) for p in data['phrases'])
    
    additional = [
        # グローバル多様性のさらなる深掘り
        (["Indigenous", "peoples", "preserve", "ancient", "knowledge"], "先住民は古代の知識を保存します"),
        (["Traditional", "practices", "passed", "down", "generations"], "伝統的な慣習が世代を超えて受け継がれます"),
        (["About", "living", "sustainably", "with", "nature"], "自然と持続可能に生きることについて"),
        (["Modern", "society", "can", "learn", "from", "this"], "現代社会はこれから学ぶことができます"),
        (["But", "indigenous", "rights", "are", "often", "violated"], "しかし先住民の権利はしばしば侵害されます"),
        (["Land", "is", "taken", "for", "development"], "土地は開発のために奪われます"),
        (["Languages", "and", "cultures", "are", "suppressed"], "言語と文化が抑圧されます"),
        (["Recognition", "and", "protection", "are", "necessary"], "認識と保護が必要です"),
        (["Free", "prior", "and", "informed", "consent"], "自由で事前の情報に基づく同意"),
        (["For", "projects", "affecting", "indigenous", "lands"], "先住民の土地に影響を与えるプロジェクトのために"),
        (["Disability", "inclusion", "promotes", "full", "participation"], "障害者の包摂は完全な参加を促進します"),
        (["People", "with", "disabilities", "face", "barriers"], "障害を持つ人々は障壁に直面します"),
        (["Physical", "attitudinal", "and", "systemic"], "物理的態度的そしてシステム的"),
        (["Universal", "design", "makes", "spaces", "accessible"], "ユニバーサルデザインはスペースをアクセス可能にします"),
        (["Ramps", "elevators", "clear", "signage"], "スロープエレベーター明確な標識"),
        (["Benefits", "everyone", "not", "just", "disabled", "people"], "障害者だけでなくすべての人に利益をもたらします"),
        (["Assistive", "technology", "enables", "independence"], "支援技術は自立を可能にします"),
        (["Screen", "readers", "hearing", "aids", "mobility", "devices"], "スクリーンリーダー補聴器移動装置"),
        (["Inclusive", "education", "benefits", "all", "students"], "包括的教育はすべての生徒に利益をもたらします"),
        (["Learning", "in", "diverse", "classrooms"], "多様な教室での学習"),
        (["Develops", "empathy", "and", "understanding"], "共感と理解を発展させます"),
        (["Age", "diversity", "enriches", "communities"], "年齢の多様性はコミュニティを豊かにします"),
        (["Different", "generations", "have", "different", "strengths"], "異なる世代は異なる強みを持ちます"),
        (["Older", "people", "have", "experience", "and", "wisdom"], "高齢者は経験と知恵を持っています"),
        (["Young", "people", "bring", "energy", "and", "innovation"], "若者はエネルギーと革新をもたらします"),
        (["Intergenerational", "programs", "connect", "them"], "世代間プログラムは彼らをつなぎます"),
        (["Mentorship", "and", "mutual", "learning"], "メンターシップと相互学習"),
        (["Ageism", "discriminates", "against", "older", "adults"], "年齢差別は高齢者に対して差別します"),
        (["Assuming", "they", "are", "less", "capable"], "彼らがより能力が低いと仮定します"),
        (["This", "wastes", "talent", "and", "experience"], "これは才能と経験を無駄にします"),
        (["Valuing", "all", "ages", "creates", "stronger", "societies"], "すべての年齢を評価することはより強い社会を作ります"),
        (["Neurodiversity", "recognizes", "different", "thinking", "styles"], "神経多様性は異なる思考スタイルを認識します"),
        (["Autism", "ADHD", "dyslexia", "and", "others"], "自閉症ADHD失読症そして他のもの"),
        (["Not", "deficits", "but", "differences"], "欠陥ではなく違い"),
        (["Different", "strengths", "and", "challenges"], "異なる強みと課題"),
        (["Accommodations", "help", "neurodivergent", "people", "thrive"], "配慮は神経多様な人々が繁栄するのを助けます"),
        (["Flexible", "work", "environments"], "柔軟な労働環境"),
        (["Clear", "communication"], "明確なコミュニケーション"),
        (["Many", "excel", "in", "fields", "like", "technology", "and", "art"], "多くが技術や芸術のような分野で優れています"),
        (["Urban", "rural", "divide", "reflects", "different", "lifestyles"], "都市と農村の分断は異なるライフスタイルを反映します"),
        (["Cities", "offer", "opportunities", "and", "services"], "都市は機会とサービスを提供します"),
        (["But", "can", "be", "expensive", "and", "stressful"], "しかし高価でストレスが多い可能性があります"),
        (["Rural", "areas", "offer", "space", "and", "nature"], "農村地域はスペースと自然を提供します"),
        (["But", "may", "lack", "infrastructure"], "しかしインフラが不足している可能性があります"),
        (["Each", "has", "value"], "それぞれに価値があります"),
        (["Policies", "should", "support", "both"], "政策は両方をサポートすべきです"),
        (["Food", "diversity", "reflects", "cultural", "richness"], "食の多様性は文化的豊かさを反映します"),
        (["Every", "cuisine", "tells", "a", "story"], "すべての料理は物語を語ります"),
        (["History", "geography", "values"], "歴史地理価値観"),
        (["Sharing", "food", "builds", "connections"], "食べ物を共有することはつながりを築きます"),
        (["Fusion", "cuisines", "blend", "traditions"], "フュージョン料理は伝統を融合します"),
        (["Creating", "something", "new"], "新しいものを作り出します"),
        (["Music", "and", "dance", "cross", "cultural", "boundaries"], "音楽とダンスは文化的境界を越えます"),
        (["Rhythms", "and", "melodies", "speak", "universally"], "リズムとメロディーは普遍的に語ります"),
        (["Traditional", "and", "contemporary", "forms", "coexist"], "伝統的で現代的な形式が共存します"),
        (["Festivals", "celebrate", "cultural", "heritage"], "祭りは文化遺産を祝います"),
        (["Bring", "communities", "together"], "コミュニティを結びつけます"),
        (["Fashion", "expresses", "identity", "and", "culture"], "ファッションはアイデンティティと文化を表現します"),
        (["Traditional", "garments", "carry", "meaning"], "伝統的な衣服は意味を持ちます"),
        (["Contemporary", "fashion", "blends", "influences"], "現代ファッションは影響を融合します"),
        (["Self", "expression", "through", "clothing"], "衣服を通じた自己表現"),
        (["Architecture", "reflects", "culture", "and", "environment"], "建築は文化と環境を反映します"),
        (["Traditional", "designs", "use", "local", "materials"], "伝統的なデザインは地元の材料を使用します"),
        (["Adapted", "to", "climate"], "気候に適応"),
        (["Modern", "architecture", "pushes", "boundaries"], "現代建築は境界を押し広げます"),
        (["But", "should", "respect", "context"], "しかし文脈を尊重すべきです"),
        (["Literature", "preserves", "and", "shares", "culture"], "文学は文化を保存し共有します"),
        (["Stories", "poems", "and", "oral", "traditions"], "物語詩そして口承伝統"),
        (["Translation", "makes", "literature", "accessible"], "翻訳は文学をアクセス可能にします"),
        (["But", "something", "is", "always", "lost"], "しかし何かは常に失われます"),
        (["Learning", "languages", "deepens", "understanding"], "言語を学ぶことは理解を深めます"),
        (["Media", "representation", "shapes", "perceptions"], "メディア表現は認識を形作ります"),
        (["Who", "is", "shown", "and", "how"], "誰がどのように示されるか"),
        (["Stereotypes", "can", "harm"], "ステレオタイプは害を与える可能性があります"),
        (["Diverse", "representation", "is", "important"], "多様な表現が重要です"),
        (["In", "films", "TV", "news", "advertising"], "映画テレビニュース広告において"),
        (["Shows", "the", "full", "range", "of", "humanity"], "人類の完全な範囲を示します"),
        (["Workplace", "diversity", "improves", "performance"], "職場の多様性はパフォーマンスを向上させます"),
        (["Diverse", "teams", "are", "more", "innovative"], "多様なチームはより革新的です"),
        (["Different", "perspectives", "lead", "to", "better", "solutions"], "異なる視点がより良い解決策につながります"),
        (["But", "requires", "inclusive", "culture"], "しかし包括的な文化が必要です"),
        (["Where", "everyone", "feels", "valued"], "すべての人が価値を感じる場所"),
        (["Can", "contribute", "fully"], "完全に貢献できます"),
        (["Microaggressions", "create", "hostile", "environments"], "マイクロアグレッションは敵対的な環境を作ります"),
        (["Small", "slights", "and", "insults"], "小さな軽視と侮辱"),
        (["Often", "unintentional"], "しばしば意図的ではない"),
        (["But", "cumulative", "impact", "is", "significant"], "しかし累積的影響は重大です"),
        (["Awareness", "and", "education", "reduce", "them"], "認識と教育がそれらを減らします"),
        (["Allyship", "supports", "marginalized", "groups"], "同盟は周縁化されたグループをサポートします"),
        (["Using", "privilege", "to", "help", "others"], "特権を使って他者を助けます"),
        (["Speaking", "up", "against", "injustice"], "不正義に対して声を上げます"),
        (["Amplifying", "marginalized", "voices"], "周縁化された声を増幅します"),
        (["Listening", "and", "learning"], "聞いて学ぶ"),
        (["Intersectionality", "recognizes", "overlapping", "identities"], "交差性は重複するアイデンティティを認識します"),
        (["People", "have", "multiple", "aspects"], "人々は複数の側面を持っています"),
        (["Race", "gender", "class", "sexuality", "disability"], "人種ジェンダー階級性的指向障害"),
        (["These", "interact", "and", "compound"], "これらは相互作用し複合します"),
        (["Creating", "unique", "experiences", "of", "discrimination"], "差別の独自の経験を作り出します"),
        (["Understanding", "this", "improves", "advocacy"], "これを理解することは擁護を改善します"),
        (["Environmental", "justice", "links", "to", "diversity"], "環境正義は多様性に結びつきます"),
        (["Marginalized", "communities", "face", "more", "pollution"], "周縁化されたコミュニティはより多くの汚染に直面します"),
        (["Less", "access", "to", "green", "space"], "緑地へのアクセスが少ない"),
        (["Climate", "change", "affects", "them", "first", "and", "worst"], "気候変動は彼らに最初に最悪の影響を与えます"),
        (["Justice", "requires", "addressing", "these", "inequities"], "正義はこれらの不公平に対処することを要求します"),
        (["Health", "disparities", "reflect", "inequality"], "健康格差は不平等を反映します"),
        (["Some", "groups", "have", "worse", "health", "outcomes"], "一部のグループはより悪い健康結果を持っています"),
        (["Due", "to", "poverty", "discrimination", "lack", "of", "access"], "貧困差別アクセス不足のために"),
        (["Addressing", "social", "determinants", "of", "health"], "健康の社会的決定要因に対処します"),
        (["Housing", "education", "employment"], "住宅教育雇用"),
        (["Improves", "health", "equity"], "健康の公平性を改善します"),
        (["Criminal", "justice", "reform", "addresses", "racial", "bias"], "刑事司法改革は人種的バイアスに対処します"),
        (["Disproportionate", "incarceration", "of", "minorities"], "少数派の不釣り合いな投獄"),
        (["Harsh", "sentencing", "for", "similar", "crimes"], "同様の犯罪に対する厳しい判決"),
        (["Police", "violence", "and", "brutality"], "警察の暴力と残虐行為"),
        (["Reforms", "include", "policy", "changes"], "改革には政策変更が含まれます"),
        (["Training", "and", "accountability"], "訓練と説明責任"),
        (["Community", "based", "alternatives"], "コミュニティベースの代替案"),
        (["Voting", "rights", "ensure", "democratic", "participation"], "投票権は民主的参加を保証します"),
        (["But", "some", "face", "barriers"], "しかし一部は障壁に直面します"),
        (["Voter", "ID", "laws", "polling", "place", "closures"], "有権者ID法投票所閉鎖"),
        (["Disenfranchisement", "of", "ex", "offenders"], "元犯罪者の権利剥奪"),
        (["Protecting", "voting", "rights", "is", "essential"], "投票権を保護することは不可欠です"),
        (["For", "true", "democracy"], "真の民主主義のために"),
        (["Language", "access", "ensures", "inclusion"], "言語アクセスは包摂を保証します"),
        (["Government", "services", "in", "multiple", "languages"], "複数の言語での政府サービス"),
        (["Translation", "and", "interpretation"], "翻訳と通訳"),
        (["So", "everyone", "can", "participate"], "すべての人が参加できるように"),
        (["Understand", "their", "rights"], "自分の権利を理解します"),
        (["Cultural", "competence", "in", "services", "improves", "outcomes"], "サービスにおける文化的能力は結果を改善します"),
        (["Healthcare", "providers", "understanding", "cultural", "backgrounds"], "文化的背景を理解する医療提供者"),
        (["Teachers", "adapting", "to", "student", "needs"], "生徒のニーズに適応する教師"),
        (["This", "builds", "trust", "and", "effectiveness"], "これは信頼と効果を構築します"),
        (["Diaspora", "communities", "maintain", "connections"], "ディアスポラコミュニティはつながりを維持します"),
        (["To", "countries", "of", "origin"], "出身国へ"),
        (["Send", "remittances", "supporting", "families"], "家族を支援する送金を送ります"),
        (["Significant", "economic", "impact"], "重大な経済的影響"),
        (["Share", "culture", "in", "new", "homes"], "新しい家で文化を共有します"),
        (["Enriching", "host", "societies"], "受け入れ社会を豊かにします"),
        (["Religious", "pluralism", "requires", "accommodation"], "宗教的多元主義は調整を必要とします"),
        (["Prayer", "spaces", "in", "workplaces", "and", "schools"], "職場と学校での祈りのスペース"),
        (["Dietary", "options", "respecting", "restrictions"], "制限を尊重する食事のオプション"),
        (["Religious", "holidays", "recognized"], "認識される宗教的祝日"),
        (["This", "respects", "freedom", "of", "religion"], "これは宗教の自由を尊重します"),
        (["Secularism", "protects", "all", "beliefs"], "世俗主義はすべての信念を保護します"),
        (["Separation", "of", "religion", "and", "state"], "宗教と国家の分離"),
        (["No", "official", "religion"], "公式宗教なし"),
        (["All", "are", "equal", "under", "law"], "すべては法の下で平等です"),
        (["Prevents", "religious", "persecution"], "宗教的迫害を防ぎます"),
        (["Reconciliation", "processes", "heal", "divisions"], "和解プロセスは分断を癒します"),
        (["After", "conflict", "or", "injustice"], "紛争または不正義の後"),
        (["Truth", "telling", "and", "acknowledgment"], "真実を語り認める"),
        (["Apologies", "and", "reparations"], "謝罪と賠償"),
        (["Building", "new", "relationships"], "新しい関係を築く"),
        (["Takes", "time", "and", "commitment"], "時間と献身が必要です"),
        (["Monuments", "and", "memorials", "shape", "collective", "memory"], "記念碑と記念館は集団記憶を形作ります"),
        (["What", "we", "choose", "to", "commemorate"], "私たちが記念することを選ぶもの"),
        (["Reflects", "our", "values"], "私たちの価値観を反映します"),
        (["Controversial", "statues", "spark", "debate"], "論争の的となる像が議論を引き起こします"),
        (["Remove", "relocate", "or", "contextualize"], "削除移転または文脈化"),
        (["No", "easy", "answers"], "簡単な答えはありません"),
        (["Symbols", "matter", "to", "people"], "シンボルは人々にとって重要です"),
        (["Building", "diverse", "societies", "is", "ongoing", "work"], "多様な社会を築くことは継続的な仕事です"),
        (["Requires", "constant", "effort"], "絶え間ない努力が必要です"),
        (["Vigilance", "against", "backsliding"], "後退に対する警戒"),
        (["But", "progress", "is", "possible"], "しかし進歩は可能です"),
        (["When", "we", "commit", "to", "inclusion"], "包摂にコミットするとき"),
        (["Embrace", "complexity"], "複雑さを受け入れます"),
        (["Stay", "hopeful"], "希望を持ち続けます"),
        (["The", "world", "is", "diverse"], "世界は多様です"),
        (["And", "that", "is", "beautiful"], "そしてそれは美しいです"),
        (["Our", "differences", "make", "us", "stronger"], "私たちの違いは私たちを強くします"),
        (["When", "we", "respect", "and", "learn", "from", "each", "other"], "お互いを尊重し学び合うとき"),
        (["Together", "we", "can", "build", "a", "world"], "一緒に私たちは世界を築くことができます"),
        (["Where", "everyone", "thrives"], "すべての人が繁栄する場所"),
        (["That", "is", "the", "promise", "of", "diversity"], "それが多様性の約束です"),
        (["Let", "us", "work", "to", "fulfill", "it"], "それを実現するために働きましょう"),
    ]
    
    for words, meaning in additional:
        max_id += 1
        data['phrases'].append({
            "id": f"phrase-{max_id}",
            "words": words,
            "phraseMeaning": meaning
        })
    
    data['actualWordCount'] = sum(len(p['words']) for p in data['phrases'])
    
    with open(file_path, 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
    
    return data['actualWordCount']


def main():
    print("="*70)
    print("Advanced-2と3の最終拡張")
    print("="*70)
    
    print("\n拡張中: advanced-2...")
    wc2 = expand_advanced_2()
    print(f"✓ advanced-2: {wc2:,}語")
    
    print("\n拡張中: advanced-3...")
    wc3 = expand_advanced_3()
    print(f"✓ advanced-3: {wc3:,}語")
    
    print("\n" + "="*70)
    print("完了!")
    print("="*70)


if __name__ == "__main__":
    main()
