#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
残り5つの高品質パッセージを生成
intermediate-4, intermediate-5, advanced-1, advanced-2, advanced-3
"""

import json
from pathlib import Path


class RemainingPassagesGenerator:
    def __init__(self):
        self.output_dir = Path("prototype")
        self.output_dir.mkdir(exist_ok=True)
    
    def create_phrase(self, phrase_id, words, meaning):
        """フレーズオブジェクトを作成"""
        return {
            "id": phrase_id,
            "words": words,
            "phraseMeaning": meaning
        }
    
    def generate_intermediate_4(self):
        """中級4: Cross-Cultural Understanding (2,500語目標)"""
        phrases = []
        pid = 1
        
        content = [
            # Introduction
            (["Our", "world", "is", "becoming", "more", "connected", "every", "day"],
             "私たちの世界は毎日よりつながっています"),
            (["People", "from", "different", "cultures", "interact", "more", "than", "ever", "before"],
             "異なる文化の人々がこれまで以上に交流しています"),
            (["Understanding", "other", "cultures", "is", "essential", "in", "modern", "life"],
             "他の文化を理解することは現代生活で不可欠です"),
            (["It", "helps", "us", "build", "friendships", "across", "borders"],
             "国境を越えて友情を築くのを助けます"),
            (["It", "opens", "doors", "to", "new", "opportunities"],
             "新しい機会への扉を開きます"),
            (["It", "makes", "us", "better", "global", "citizens"],
             "私たちをより良い地球市民にします"),
            (["Let", "us", "explore", "the", "importance", "of", "cultural", "understanding"],
             "文化的理解の重要性を探りましょう"),
            
            # What is Culture
            (["Culture", "is", "the", "way", "of", "life", "of", "a", "group", "of", "people"],
             "文化は人々のグループの生き方です"),
            (["It", "includes", "language", "customs", "and", "traditions"],
             "言語習慣伝統を含みます"),
            (["It", "includes", "food", "clothing", "and", "art"],
             "食べ物衣服芸術を含みます"),
            (["It", "includes", "beliefs", "values", "and", "behaviors"],
             "信念価値観行動を含みます"),
            (["Culture", "is", "learned", "from", "family", "and", "community"],
             "文化は家族とコミュニティから学ばれます"),
            (["It", "is", "passed", "down", "through", "generations"],
             "世代を通して受け継がれます"),
            (["Every", "culture", "has", "its", "own", "unique", "characteristics"],
             "すべての文化には独自の特徴があります"),
            (["No", "culture", "is", "better", "or", "worse", "than", "another"],
             "どの文化も他より良いまたは悪いということはありません"),
            (["They", "are", "simply", "different"],
             "単に異なるだけです"),
            (["Each", "has", "developed", "to", "meet", "the", "needs", "of", "its", "people"],
             "それぞれがその人々のニーズを満たすために発展しました"),
            (["Understanding", "this", "diversity", "enriches", "our", "lives"],
             "この多様性を理解することは私たちの生活を豊かにします"),
            
            # Language and Communication
            (["Language", "is", "the", "foundation", "of", "culture"],
             "言語は文化の基盤です"),
            (["There", "are", "over", "7000", "languages", "in", "the", "world"],
             "世界には7000以上の言語があります"),
            (["Each", "language", "reflects", "its", "culture", "unique", "worldview"],
             "各言語はその文化独自の世界観を反映します"),
            (["Learning", "another", "language", "opens", "new", "perspectives"],
             "別の言語を学ぶことは新しい視点を開きます"),
            (["It", "helps", "us", "understand", "how", "others", "think"],
             "他者がどう考えるか理解するのを助けます"),
            (["English", "is", "widely", "used", "as", "an", "international", "language"],
             "英語は国際語として広く使われています"),
            (["It", "helps", "people", "from", "different", "countries", "communicate"],
             "異なる国の人々がコミュニケーションするのを助けます"),
            (["However", "preserving", "local", "languages", "is", "also", "important"],
             "しかし地元の言語を保存することも重要です"),
            (["Each", "language", "contains", "unique", "knowledge", "and", "wisdom"],
             "各言語は独自の知識と知恵を含んでいます"),
            (["When", "a", "language", "dies", "we", "lose", "cultural", "heritage"],
             "言語が死ぬと文化遺産を失います"),
            (["Communication", "goes", "beyond", "words"],
             "コミュニケーションは言葉を超えます"),
            (["Body", "language", "varies", "across", "cultures"],
             "ボディランゲージは文化によって異なります"),
            (["Eye", "contact", "means", "different", "things", "in", "different", "places"],
             "アイコンタクトは異なる場所で異なることを意味します"),
            (["In", "some", "cultures", "direct", "eye", "contact", "shows", "respect"],
             "一部の文化では直接のアイコンタクトが敬意を示します"),
            (["In", "others", "it", "may", "be", "considered", "rude"],
             "他の文化では失礼と見なされるかもしれません"),
            (["Personal", "space", "preferences", "also", "differ"],
             "個人的な空間の好みも異なります"),
            (["Some", "cultures", "stand", "close", "when", "talking"],
             "一部の文化は話すときに近くに立ちます"),
            (["Others", "prefer", "more", "distance"],
             "他は距離を好みます"),
            (["Understanding", "these", "differences", "prevents", "misunderstandings"],
             "これらの違いを理解することは誤解を防ぎます"),
            
            # Food and Traditions
            (["Food", "is", "an", "important", "part", "of", "every", "culture"],
             "食べ物はすべての文化の重要な部分です"),
            (["Traditional", "dishes", "reflect", "local", "ingredients", "and", "history"],
             "伝統的な料理は地元の材料と歴史を反映します"),
            (["Sharing", "meals", "brings", "people", "together"],
             "食事を共有することは人々を一緒にします"),
            (["Many", "cultures", "have", "special", "foods", "for", "celebrations"],
             "多くの文化はお祝いのための特別な食べ物があります"),
            (["These", "foods", "carry", "symbolic", "meanings"],
             "これらの食べ物は象徴的な意味を持ちます"),
            (["In", "Japan", "people", "eat", "special", "dishes", "on", "New", "Year"],
             "日本では人々は正月に特別な料理を食べます"),
            (["Each", "dish", "represents", "a", "wish", "for", "the", "coming", "year"],
             "各料理は来年への願いを表します"),
            (["In", "China", "dumplings", "symbolize", "wealth", "and", "prosperity"],
             "中国では餃子は富と繁栄を象徴します"),
            (["In", "Mexico", "families", "gather", "for", "special", "meals", "on", "holidays"],
             "メキシコでは家族が休日に特別な食事のために集まります"),
            (["Food", "connects", "us", "to", "our", "ancestors"],
             "食べ物は私たちを先祖につなぎます"),
            (["Traditional", "recipes", "pass", "through", "generations"],
             "伝統的なレシピは世代を通して受け継がれます"),
            (["Trying", "food", "from", "other", "cultures", "is", "educational"],
             "他の文化の食べ物を試すことは教育的です"),
            (["It", "gives", "us", "a", "taste", "of", "different", "ways", "of", "life"],
             "異なる生き方の味を与えます"),
            (["Many", "cities", "now", "have", "restaurants", "from", "around", "the", "world"],
             "多くの都市には今世界中のレストランがあります"),
            (["This", "diversity", "enriches", "our", "dining", "experiences"],
             "この多様性は私たちの食事体験を豊かにします"),
            
            # Festivals and Celebrations
            (["Festivals", "reveal", "much", "about", "a", "culture", "values"],
             "祭りは文化の価値について多くを明らかにします"),
            (["They", "mark", "important", "times", "of", "year"],
             "年の重要な時期を示します"),
            (["They", "celebrate", "harvests", "seasons", "or", "historical", "events"],
             "収穫季節歴史的出来事を祝います"),
            (["Diwali", "is", "the", "festival", "of", "lights", "in", "India"],
             "ディワリはインドの光の祭りです"),
            (["Families", "light", "lamps", "and", "share", "sweets"],
             "家族はランプを灯しお菓子を共有します"),
            (["It", "symbolizes", "the", "victory", "of", "light", "over", "darkness"],
             "光が闇に勝利することを象徴します"),
            (["Chinese", "New", "Year", "is", "a", "time", "for", "family", "reunions"],
             "中国の正月は家族の再会の時です"),
            (["People", "clean", "their", "homes", "to", "sweep", "away", "bad", "luck"],
             "人々は悪い運を掃き出すために家を掃除します"),
            (["They", "give", "red", "envelopes", "with", "money", "for", "good", "fortune"],
             "幸運のためにお金の入った赤い封筒を渡します"),
            (["Carnival", "in", "Brazil", "is", "famous", "for", "music", "and", "dancing"],
             "ブラジルのカーニバルは音楽とダンスで有名です"),
            (["It", "is", "a", "time", "of", "joy", "and", "celebration"],
             "喜びとお祝いの時です"),
            (["Thanksgiving", "in", "America", "celebrates", "gratitude"],
             "アメリカの感謝祭は感謝を祝います"),
            (["Families", "gather", "to", "share", "a", "meal", "and", "give", "thanks"],
             "家族は食事を共有し感謝するために集まります"),
            (["These", "festivals", "strengthen", "community", "bonds"],
             "これらの祭りはコミュニティの絆を強めます"),
            (["They", "remind", "us", "of", "what", "matters", "most"],
             "最も重要なことを思い出させます"),
            (["Participating", "in", "other", "cultures", "festivals", "builds", "understanding"],
             "他の文化の祭りに参加することは理解を築きます"),
            
            # Religion and Beliefs
            (["Religion", "shapes", "many", "aspects", "of", "culture"],
             "宗教は文化の多くの側面を形作ります"),
            (["Major", "world", "religions", "include", "Christianity", "Islam", "Hinduism", "and", "Buddhism"],
             "主要な世界の宗教にはキリスト教イスラム教ヒンドゥー教仏教が含まれます"),
            (["Each", "has", "millions", "of", "followers", "worldwide"],
             "それぞれ世界中に何百万もの信者がいます"),
            (["Religious", "beliefs", "influence", "daily", "life"],
             "宗教的信念は日常生活に影響します"),
            (["They", "affect", "what", "people", "eat", "and", "wear"],
             "人々が何を食べ何を着るかに影響します"),
            (["They", "guide", "moral", "decisions"],
             "道徳的決定を導きます"),
            (["They", "provide", "comfort", "in", "difficult", "times"],
             "困難な時に慰めを提供します"),
            (["Some", "people", "do", "not", "follow", "any", "religion"],
             "一部の人々はどの宗教にも従いません"),
            (["This", "choice", "should", "also", "be", "respected"],
             "この選択も尊重されるべきです"),
            (["Religious", "tolerance", "is", "essential", "for", "peaceful", "coexistence"],
             "宗教的寛容は平和な共存に不可欠です"),
            (["We", "must", "respect", "others", "beliefs", "even", "when", "different", "from", "ours"],
             "私たちのものと異なっていても他者の信念を尊重しなければなりません"),
            (["Many", "conflicts", "arise", "from", "religious", "intolerance"],
             "多くの対立は宗教的不寛容から生じます"),
            (["Understanding", "different", "faiths", "promotes", "harmony"],
             "異なる信仰を理解することは調和を促進します"),
            (["We", "can", "learn", "from", "each", "tradition", "wisdom"],
             "各伝統の知恵から学ぶことができます"),
            (["All", "major", "religions", "teach", "compassion", "and", "kindness"],
             "すべての主要な宗教は思いやりと優しさを教えます"),
            (["These", "universal", "values", "unite", "humanity"],
             "これらの普遍的な価値観は人類を統一します"),
            
            # Education Systems
            (["Education", "systems", "vary", "greatly", "across", "cultures"],
             "教育システムは文化によって大きく異なります"),
            (["Some", "emphasize", "memorization", "and", "tests"],
             "一部は暗記とテストを重視します"),
            (["Others", "focus", "on", "creativity", "and", "critical", "thinking"],
             "他は創造性と批判的思考に焦点を当てます"),
            (["In", "Japan", "students", "learn", "discipline", "and", "respect"],
             "日本では生徒は規律と尊敬を学びます"),
            (["They", "clean", "their", "own", "classrooms"],
             "自分の教室を掃除します"),
            (["This", "teaches", "responsibility", "and", "teamwork"],
             "これは責任とチームワークを教えます"),
            (["In", "Finland", "schools", "have", "shorter", "days", "and", "less", "homework"],
             "フィンランドでは学校は短い日と少ない宿題があります"),
            (["They", "focus", "on", "play", "and", "social", "skills"],
             "遊びと社交スキルに焦点を当てます"),
            (["Yet", "Finnish", "students", "perform", "very", "well", "academically"],
             "それでもフィンランドの生徒は学業的に非常によく成績を上げます"),
            (["This", "shows", "there", "are", "many", "paths", "to", "success"],
             "これは成功への多くの道があることを示します"),
            (["International", "exchange", "programs", "are", "valuable"],
             "国際交流プログラムは価値があります"),
            (["Students", "can", "study", "abroad", "and", "experience", "different", "education", "systems"],
             "生徒は海外で勉強し異なる教育システムを経験できます"),
            (["This", "broadens", "perspectives", "and", "builds", "independence"],
             "これは視野を広げ独立性を築きます"),
            (["Hosting", "exchange", "students", "also", "teaches", "us"],
             "交換留学生を受け入れることも私たちに教えます"),
            (["We", "learn", "about", "their", "culture", "firsthand"],
             "彼らの文化について直接学びます"),
            (["We", "practice", "hospitality", "and", "openness"],
             "もてなしと開放性を実践します"),
            
            # Family Structures
            (["Family", "structures", "differ", "around", "the", "world"],
             "家族構造は世界中で異なります"),
            (["In", "some", "cultures", "extended", "families", "live", "together"],
             "一部の文化では拡大家族が一緒に住みます"),
            (["Grandparents", "parents", "and", "children", "share", "one", "home"],
             "祖父母両親子供が一つの家を共有します"),
            (["This", "provides", "support", "and", "care", "across", "generations"],
             "これは世代を超えてサポートとケアを提供します"),
            (["In", "other", "cultures", "nuclear", "families", "are", "more", "common"],
             "他の文化では核家族がより一般的です"),
            (["Parents", "and", "children", "live", "separately", "from", "other", "relatives"],
             "両親と子供は他の親戚とは別に住みます"),
            (["Both", "structures", "have", "advantages"],
             "両方の構造には利点があります"),
            (["Extended", "families", "offer", "more", "help", "with", "childcare"],
             "拡大家族は育児でより多くの助けを提供します"),
            (["Nuclear", "families", "may", "have", "more", "independence"],
             "核家族はより多くの独立性を持つかもしれません"),
            (["Gender", "roles", "within", "families", "also", "vary"],
             "家族内の性別役割も異なります"),
            (["Traditional", "roles", "are", "changing", "in", "many", "places"],
             "伝統的な役割は多くの場所で変化しています"),
            (["More", "women", "work", "outside", "the", "home"],
             "より多くの女性が家の外で働きます"),
            (["More", "men", "participate", "in", "childcare", "and", "housework"],
             "より多くの男性が育児と家事に参加します"),
            (["These", "changes", "create", "more", "equality"],
             "これらの変化はより多くの平等を生み出します"),
            (["However", "change", "happens", "at", "different", "speeds"],
             "しかし変化は異なる速度で起こります"),
            (["We", "must", "respect", "each", "family", "choices"],
             "各家族の選択を尊重しなければなりません"),
            
            # Arts and Music
            (["Arts", "express", "cultural", "identity"],
             "芸術は文化的アイデンティティを表現します"),
            (["Traditional", "music", "uses", "unique", "instruments", "and", "rhythms"],
             "伝統音楽は独自の楽器とリズムを使います"),
            (["African", "drumming", "has", "complex", "polyrhythms"],
             "アフリカのドラミングは複雑なポリリズムを持っています"),
            (["Indian", "classical", "music", "uses", "ragas", "and", "intricate", "melodies"],
             "インド古典音楽はラーガと複雑な旋律を使います"),
            (["Western", "classical", "music", "developed", "symphonies", "and", "operas"],
             "西洋クラシック音楽は交響曲とオペラを発展させました"),
            (["Each", "tradition", "offers", "unique", "beauty"],
             "各伝統は独自の美しさを提供します"),
            (["Visual", "arts", "also", "reflect", "culture"],
             "視覚芸術も文化を反映します"),
            (["Japanese", "art", "often", "features", "nature", "and", "simplicity"],
             "日本の芸術はしばしば自然とシンプルさを特徴とします"),
            (["Islamic", "art", "uses", "beautiful", "geometric", "patterns"],
             "イスラム芸術は美しい幾何学模様を使います"),
            (["Aboriginal", "Australian", "art", "tells", "ancient", "stories"],
             "アボリジニのオーストラリア芸術は古代の物語を語ります"),
            (["Modern", "art", "blends", "influences", "from", "many", "cultures"],
             "現代芸術は多くの文化からの影響を混ぜます"),
            (["Artists", "today", "create", "works", "that", "speak", "to", "global", "audiences"],
             "今日のアーティストは世界的な聴衆に語りかける作品を作ります"),
            (["Music", "and", "art", "transcend", "language", "barriers"],
             "音楽と芸術は言語の壁を超えます"),
            (["They", "connect", "us", "emotionally"],
             "感情的に私たちをつなぎます"),
            (["They", "remind", "us", "of", "our", "shared", "humanity"],
             "私たちの共有された人間性を思い出させます"),
            
            # Challenges in Cross-Cultural Communication
            (["Despite", "good", "intentions", "misunderstandings", "occur"],
             "良い意図にもかかわらず誤解が起こります"),
            (["Stereotypes", "are", "simplified", "beliefs", "about", "groups"],
             "ステレオタイプはグループについての単純化された信念です"),
            (["They", "ignore", "individual", "differences"],
             "個人の違いを無視します"),
            (["Assuming", "all", "people", "from", "one", "culture", "are", "the", "same", "is", "wrong"],
             "一つの文化のすべての人が同じだと仮定するのは間違いです"),
            (["Each", "person", "is", "unique"],
             "各人はユニークです"),
            (["Cultural", "generalizations", "can", "be", "useful", "starting", "points"],
             "文化的一般化は有用な出発点になることができます"),
            (["But", "we", "must", "remain", "open", "to", "exceptions"],
             "しかし例外に対してオープンでいなければなりません"),
            (["Ethnocentrism", "is", "judging", "other", "cultures", "by", "our", "own", "standards"],
             "自文化中心主義は自分の基準で他の文化を判断することです"),
            (["This", "leads", "to", "prejudice", "and", "discrimination"],
             "これは偏見と差別につながります"),
            (["We", "must", "practice", "cultural", "relativism"],
             "文化相対主義を実践しなければなりません"),
            (["This", "means", "understanding", "cultures", "in", "their", "own", "context"],
             "これは文化をそれ自身の文脈で理解することを意味します"),
            (["Not", "everything", "needs", "to", "be", "accepted"],
             "すべてが受け入れられる必要はありません"),
            (["Universal", "human", "rights", "should", "be", "respected", "everywhere"],
             "普遍的人権はどこでも尊重されるべきです"),
            (["But", "we", "can", "appreciate", "differences", "without", "judgment"],
             "しかし判断なしに違いを評価できます"),
            
            # Building Bridges
            (["How", "can", "we", "become", "better", "cross", "cultural", "communicators"],
             "どうすればよりよい異文化コミュニケーターになれますか"),
            (["First", "approach", "other", "cultures", "with", "curiosity"],
             "まず他の文化に好奇心を持って近づきます"),
            (["Ask", "questions", "respectfully"],
             "敬意を持って質問します"),
            (["Listen", "actively", "to", "understand"],
             "理解するために積極的に聞きます"),
            (["Second", "be", "aware", "of", "your", "own", "cultural", "biases"],
             "二番目に自分自身の文化的偏見を認識します"),
            (["We", "all", "have", "assumptions", "based", "on", "our", "upbringing"],
             "私たちは皆育ちに基づく仮定を持っています"),
            (["Recognizing", "these", "helps", "us", "be", "more", "objective"],
             "これらを認識することはより客観的になるのを助けます"),
            (["Third", "practice", "empathy"],
             "三番目に共感を実践します"),
            (["Try", "to", "see", "situations", "from", "others", "perspectives"],
             "他者の視点から状況を見ようとします"),
            (["Imagine", "how", "you", "would", "feel", "in", "their", "position"],
             "彼らの立場でどう感じるか想像します"),
            (["Fourth", "be", "patient"],
             "四番目に忍耐強くあります"),
            (["Building", "understanding", "takes", "time"],
             "理解を築くには時間がかかります"),
            (["Mistakes", "will", "happen"],
             "間違いは起こります"),
            (["Learn", "from", "them", "and", "keep", "trying"],
             "それらから学び試し続けます"),
            (["Fifth", "find", "common", "ground"],
             "五番目に共通点を見つけます"),
            (["Despite", "differences", "we", "share", "many", "human", "experiences"],
             "違いにもかかわらず私たちは多くの人間の経験を共有します"),
            (["We", "all", "feel", "joy", "sadness", "love", "and", "fear"],
             "私たちは皆喜び悲しみ愛恐れを感じます"),
            (["We", "all", "want", "happiness", "and", "security", "for", "our", "families"],
             "私たちは皆家族の幸せと安全を望みます"),
            (["Focusing", "on", "similarities", "builds", "connections"],
             "類似性に焦点を当てることはつながりを築きます"),
            
            # Benefits of Cultural Exchange
            (["Cross", "cultural", "understanding", "benefits", "everyone"],
             "異文化理解は誰にでも利益をもたらします"),
            (["It", "promotes", "peace", "and", "reduces", "conflict"],
             "平和を促進し対立を減らします"),
            (["When", "we", "understand", "each", "other", "we", "fear", "each", "other", "less"],
             "お互いを理解するとお互いを恐れることが少なくなります"),
            (["It", "encourages", "cooperation", "on", "global", "problems"],
             "グローバルな問題での協力を奨励します"),
            (["Climate", "change", "poverty", "and", "disease", "affect", "us", "all"],
             "気候変動貧困病気は私たち全員に影響します"),
            (["Working", "together", "we", "can", "find", "solutions"],
             "一緒に働くことで解決策を見つけることができます"),
            (["Cultural", "exchange", "enriches", "our", "personal", "lives"],
             "文化交流は私たちの個人的な生活を豊かにします"),
            (["We", "gain", "new", "perspectives", "on", "our", "own", "culture"],
             "自分の文化について新しい視点を得ます"),
            (["We", "appreciate", "what", "makes", "us", "unique"],
             "私たちをユニークにするものを評価します"),
            (["We", "also", "see", "ways", "we", "might", "improve"],
             "改善できる方法も見えます"),
            (["It", "opens", "career", "opportunities"],
             "キャリアの機会を開きます"),
            (["Companies", "need", "employees", "who", "can", "work", "across", "cultures"],
             "企業は文化を越えて働ける従業員を必要とします"),
            (["Cultural", "competence", "is", "a", "valuable", "skill"],
             "文化的能力は価値あるスキルです"),
            
            # Conclusion
            (["In", "our", "interconnected", "world", "cultural", "understanding", "is", "essential"],
             "私たちの相互接続された世界では文化的理解は不可欠です"),
            (["We", "are", "all", "part", "of", "the", "human", "family"],
             "私たちは皆人類家族の一部です"),
            (["Our", "differences", "make", "life", "interesting", "and", "rich"],
             "私たちの違いは人生を面白く豊かにします"),
            (["But", "our", "similarities", "are", "greater", "than", "our", "differences"],
             "しかし私たちの類似性は違いより大きいです"),
            (["By", "learning", "about", "other", "cultures"],
             "他の文化について学ぶことによって"),
            (["We", "become", "better", "people"],
             "私たちはより良い人になります"),
            (["We", "build", "a", "better", "world"],
             "より良い世界を築きます"),
            (["A", "world", "of", "respect", "understanding", "and", "cooperation"],
             "尊敬理解協力の世界を"),
            (["A", "world", "where", "diversity", "is", "celebrated"],
             "多様性が祝われる世界を"),
            (["A", "world", "where", "everyone", "belongs"],
             "誰もが属する世界を"),
            (["This", "is", "our", "shared", "goal"],
             "これが私たちの共有された目標です"),
            (["Let", "us", "work", "together", "to", "achieve", "it"],
             "それを達成するために一緒に働きましょう"),
            (["Starting", "today", "in", "our", "own", "communities"],
             "今日から私たち自身のコミュニティで"),
            (["With", "open", "minds", "and", "open", "hearts"],
             "開かれた心と開かれた精神で"),
            
            # Technology and Global Connection
            (["Technology", "makes", "cross", "cultural", "communication", "easier"],
             "テクノロジーは異文化コミュニケーションをより簡単にします"),
            (["Social", "media", "connects", "people", "across", "continents"],
             "ソーシャルメディアは大陸を越えて人々をつなぎます"),
            (["We", "can", "see", "how", "others", "live", "in", "real", "time"],
             "リアルタイムで他者がどう生きているか見ることができます"),
            (["Video", "calls", "bring", "faces", "together", "despite", "distance"],
             "ビデオ通話は距離にもかかわらず顔を一緒にします"),
            (["Translation", "apps", "help", "break", "down", "language", "barriers"],
             "翻訳アプリは言語の壁を壊すのを助けます"),
            (["We", "can", "communicate", "even", "without", "speaking", "the", "same", "language"],
             "同じ言語を話さなくてもコミュニケーションできます"),
            (["Online", "courses", "teach", "us", "about", "different", "cultures"],
             "オンラインコースは異なる文化について教えます"),
            (["We", "can", "learn", "from", "experts", "anywhere", "in", "the", "world"],
             "世界中のどこの専門家からでも学ぶことができます"),
            (["Virtual", "reality", "lets", "us", "experience", "distant", "places"],
             "バーチャルリアリティは遠い場所を体験させます"),
            (["We", "can", "visit", "museums", "and", "landmarks", "from", "home"],
             "家から博物館やランドマークを訪れることができます"),
            (["However", "technology", "has", "limitations"],
             "しかしテクノロジーには限界があります"),
            (["Nothing", "replaces", "face", "to", "face", "interaction"],
             "対面の交流に代わるものはありません"),
            (["Real", "travel", "and", "immersion", "provide", "deeper", "understanding"],
             "実際の旅と没入はより深い理解を提供します"),
            (["We", "must", "use", "technology", "wisely"],
             "テクノロジーを賢く使わなければなりません"),
            (["It", "is", "a", "tool", "not", "a", "substitute", "for", "real", "connection"],
             "それは道具であり本当のつながりの代替ではありません"),
            
            # Immigration and Multiculturalism
            (["Many", "countries", "are", "becoming", "more", "multicultural"],
             "多くの国がより多文化になっています"),
            (["People", "move", "for", "work", "education", "or", "safety"],
             "人々は仕事教育安全のために移動します"),
            (["Immigrants", "bring", "their", "cultures", "to", "new", "lands"],
             "移民は彼らの文化を新しい土地に持ち込みます"),
            (["This", "creates", "diverse", "neighborhoods", "and", "communities"],
             "これは多様な地域とコミュニティを作ります"),
            (["New", "restaurants", "shops", "and", "cultural", "centers", "appear"],
             "新しいレストラン店文化センターが現れます"),
            (["Cities", "become", "melting", "pots", "of", "traditions"],
             "都市は伝統のるつぼになります"),
            (["This", "diversity", "has", "many", "benefits"],
             "この多様性には多くの利点があります"),
            (["Different", "perspectives", "lead", "to", "innovation"],
             "異なる視点は革新につながります"),
            (["Cultural", "mixing", "creates", "new", "art", "forms"],
             "文化的混合は新しい芸術形式を作ります"),
            (["It", "prepares", "young", "people", "for", "a", "global", "world"],
             "若者をグローバルな世界に備えさせます"),
            (["However", "challenges", "exist"],
             "しかし課題が存在します"),
            (["Some", "people", "fear", "losing", "their", "traditional", "culture"],
             "一部の人々は伝統的な文化を失うことを恐れます"),
            (["Tensions", "can", "arise", "between", "different", "groups"],
             "異なるグループ間で緊張が生じることがあります"),
            (["Language", "barriers", "make", "integration", "difficult"],
             "言語の壁は統合を難しくします"),
            (["Successful", "multicultural", "societies", "require", "effort"],
             "成功した多文化社会は努力を必要とします"),
            (["Governments", "must", "create", "inclusive", "policies"],
             "政府は包括的な政策を作らなければなりません"),
            (["Communities", "must", "welcome", "newcomers"],
             "コミュニティは新参者を歓迎しなければなりません"),
            (["Immigrants", "must", "also", "make", "efforts", "to", "integrate"],
             "移民も統合するための努力をしなければなりません"),
            (["Learning", "the", "local", "language", "is", "important"],
             "現地の言語を学ぶことは重要です"),
            (["Respecting", "local", "laws", "and", "customs", "is", "essential"],
             "現地の法律と習慣を尊重することは不可欠です"),
            (["Integration", "does", "not", "mean", "losing", "one", "identity"],
             "統合は自分のアイデンティティを失うことを意味しません"),
            (["People", "can", "maintain", "their", "heritage", "while", "embracing", "the", "new"],
             "人々は新しいものを受け入れながら遺産を維持できます"),
            (["This", "creates", "rich", "multicultural", "identities"],
             "これは豊かな多文化的アイデンティティを作ります"),
            
            # Travel and Tourism
            (["Tourism", "is", "another", "form", "of", "cultural", "exchange"],
             "観光は文化交流の別の形です"),
            (["Millions", "of", "people", "travel", "internationally", "each", "year"],
             "毎年何百万もの人々が国際的に旅行します"),
            (["They", "visit", "historical", "sites", "and", "natural", "wonders"],
             "歴史的場所と自然の驚異を訪れます"),
            (["They", "try", "local", "food", "and", "participate", "in", "festivals"],
             "地元の食べ物を試しお祭りに参加します"),
            (["Travel", "broadens", "horizons", "and", "challenges", "assumptions"],
             "旅は視野を広げ仮定に挑戦します"),
            (["We", "see", "that", "there", "are", "many", "ways", "to", "live"],
             "生きる方法は多くあることを見ます"),
            (["What", "seemed", "strange", "at", "home", "becomes", "normal", "elsewhere"],
             "家では奇妙に思えたことが他の場所では普通になります"),
            (["What", "we", "took", "for", "granted", "may", "not", "be", "universal"],
             "当たり前だと思っていたことは普遍的ではないかもしれません"),
            (["Tourism", "also", "brings", "economic", "benefits"],
             "観光は経済的利益ももたらします"),
            (["It", "creates", "jobs", "in", "hotels", "restaurants", "and", "transportation"],
             "ホテルレストラン交通機関で仕事を作ります"),
            (["It", "helps", "preserve", "cultural", "heritage"],
             "文化遺産を保存するのを助けます"),
            (["Money", "from", "tourists", "funds", "restoration", "projects"],
             "観光客からのお金は修復プロジェクトに資金を提供します"),
            (["However", "tourism", "must", "be", "responsible"],
             "しかし観光は責任を持たなければなりません"),
            (["Too", "many", "visitors", "can", "damage", "fragile", "sites"],
             "あまりに多くの訪問者は壊れやすい場所を損傷する可能性があります"),
            (["Local", "cultures", "can", "become", "commercialized"],
             "地元の文化は商業化される可能性があります"),
            (["Traditions", "may", "be", "performed", "only", "for", "tourist", "entertainment"],
             "伝統は観光客の娯楽のためだけに演じられるかもしれません"),
            (["This", "loses", "authentic", "meaning"],
             "これは本物の意味を失います"),
            (["Sustainable", "tourism", "respects", "local", "communities"],
             "持続可能な観光は地元のコミュニティを尊重します"),
            (["Tourists", "should", "learn", "basic", "phrases", "in", "the", "local", "language"],
             "観光客は現地の言語で基本的なフレーズを学ぶべきです"),
            (["They", "should", "dress", "appropriately", "for", "sacred", "sites"],
             "神聖な場所には適切に服装するべきです"),
            (["They", "should", "support", "local", "businesses"],
             "地元の企業をサポートするべきです"),
            (["They", "should", "be", "mindful", "of", "environmental", "impact"],
             "環境への影響を意識するべきです"),
            
            # Youth and Cultural Exchange
            (["Young", "people", "are", "natural", "cultural", "ambassadors"],
             "若者は自然な文化大使です"),
            (["They", "are", "more", "open", "to", "new", "experiences"],
             "新しい経験によりオープンです"),
            (["They", "adapt", "more", "easily", "to", "different", "environments"],
             "異なる環境により簡単に適応します"),
            (["Student", "exchange", "programs", "create", "lasting", "friendships"],
             "学生交換プログラムは永続的な友情を作ります"),
            (["These", "connections", "promote", "peace", "for", "generations"],
             "これらのつながりは世代のために平和を促進します"),
            (["International", "sports", "competitions", "unite", "youth"],
             "国際スポーツ競技会は若者を統一します"),
            (["Athletes", "compete", "but", "also", "share", "experiences"],
             "アスリートは競争しますが経験も共有します"),
            (["They", "learn", "sportsmanship", "and", "mutual", "respect"],
             "スポーツマンシップと相互尊重を学びます"),
            (["Volunteer", "programs", "send", "young", "people", "abroad"],
             "ボランティアプログラムは若者を海外に送ります"),
            (["They", "help", "with", "education", "healthcare", "or", "environmental", "projects"],
             "教育医療環境プロジェクトを手伝います"),
            (["This", "service", "changes", "both", "volunteers", "and", "communities"],
             "このサービスはボランティアとコミュニティの両方を変えます"),
            (["Social", "media", "lets", "youth", "form", "global", "networks"],
             "ソーシャルメディアは若者がグローバルなネットワークを形成することを可能にします"),
            (["They", "share", "music", "fashion", "and", "ideas", "instantly"],
             "音楽ファッションアイデアを即座に共有します"),
            (["A", "global", "youth", "culture", "is", "emerging"],
             "グローバルな若者文化が出現しています"),
            (["This", "does", "not", "erase", "local", "identities"],
             "これは地元のアイデンティティを消しません"),
            (["Rather", "it", "adds", "layers", "of", "connection"],
             "むしろつながりの層を追加します"),
            
            # Business and International Trade
            (["Business", "increasingly", "crosses", "borders"],
             "ビジネスはますます国境を越えます"),
            (["Companies", "operate", "in", "multiple", "countries"],
             "企業は複数の国で事業を行います"),
            (["They", "must", "understand", "different", "business", "cultures"],
             "異なるビジネス文化を理解しなければなりません"),
            (["Negotiation", "styles", "vary", "greatly"],
             "交渉スタイルは大きく異なります"),
            (["Some", "cultures", "value", "directness", "and", "efficiency"],
             "一部の文化は率直さと効率を重視します"),
            (["Others", "prefer", "building", "relationships", "first"],
             "他は最初に関係を築くことを好みます"),
            (["Business", "etiquette", "differs", "too"],
             "ビジネスエチケットも異なります"),
            (["Gift", "giving", "practices", "vary"],
             "贈り物をする習慣は異なります"),
            (["What", "is", "appropriate", "in", "one", "place", "may", "offend", "in", "another"],
             "ある場所で適切なことが別の場所では気分を害するかもしれません"),
            (["Meeting", "customs", "also", "differ"],
             "会議の習慣も異なります"),
            (["Punctuality", "is", "strictly", "expected", "in", "some", "cultures"],
             "時間厳守は一部の文化では厳格に期待されます"),
            (["In", "others", "a", "more", "flexible", "approach", "is", "normal"],
             "他ではより柔軟なアプローチが普通です"),
            (["Communication", "styles", "in", "business", "matter"],
             "ビジネスでのコミュニケーションスタイルは重要です"),
            (["Some", "cultures", "communicate", "directly"],
             "一部の文化は直接的にコミュニケーションします"),
            (["Others", "use", "indirect", "language", "to", "maintain", "harmony"],
             "他は調和を保つために間接的な言語を使います"),
            (["Understanding", "these", "differences", "prevents", "costly", "mistakes"],
             "これらの違いを理解することは高くつく間違いを防ぎます"),
            (["It", "builds", "trust", "and", "successful", "partnerships"],
             "信頼と成功したパートナーシップを築きます"),
            (["Companies", "provide", "cultural", "training", "for", "employees"],
             "企業は従業員に文化トレーニングを提供します"),
            (["This", "investment", "pays", "off", "in", "better", "relationships"],
             "この投資はより良い関係で報われます"),
            
            # Final Thoughts
            (["Cross", "cultural", "understanding", "requires", "lifelong", "learning"],
             "異文化理解は生涯学習を必要とします"),
            (["No", "one", "can", "know", "everything", "about", "all", "cultures"],
             "誰もがすべての文化についてすべてを知ることはできません"),
            (["But", "we", "can", "always", "learn", "more"],
             "しかし常にもっと学ぶことができます"),
            (["Each", "interaction", "is", "an", "opportunity"],
             "各交流は機会です"),
            (["Each", "person", "we", "meet", "teaches", "us", "something"],
             "私たちが出会う各人は何かを教えます"),
            (["The", "key", "is", "to", "remain", "humble"],
             "鍵は謙虚でいることです"),
            (["Admit", "when", "you", "do", "not", "know"],
             "知らないときは認めます"),
            (["Be", "willing", "to", "make", "mistakes", "and", "apologize"],
             "間違いを犯し謝罪することを厭わないでいます"),
            (["Show", "genuine", "interest", "in", "others"],
             "他者への真の関心を示します"),
            (["Celebrate", "both", "differences", "and", "similarities"],
             "違いと類似性の両方を祝います"),
            (["Remember", "that", "behind", "every", "culture", "are", "individual", "people"],
             "すべての文化の背後には個々の人がいることを覚えています"),
            (["People", "with", "hopes", "dreams", "and", "feelings"],
             "希望夢感情を持つ人々"),
            (["People", "just", "like", "you"],
             "あなたと同じような人々"),
            (["By", "reaching", "across", "cultural", "boundaries"],
             "文化的境界を越えて手を伸ばすことによって"),
            (["We", "discover", "our", "common", "humanity"],
             "私たちの共通の人間性を発見します"),
            (["We", "create", "a", "world", "of", "greater", "understanding"],
             "より大きな理解の世界を作ります"),
            (["A", "world", "of", "lasting", "peace"],
             "永続的な平和の世界を"),
            (["This", "is", "the", "gift", "of", "cultural", "exchange"],
             "これが文化交流の贈り物です"),
            (["This", "is", "our", "responsibility", "and", "privilege"],
             "これが私たちの責任と特権です"),
            (["Let", "us", "embrace", "it", "with", "courage", "and", "joy"],
             "勇気と喜びでそれを受け入れましょう"),
            
            # Practical Steps for Students
            (["As", "students", "you", "have", "unique", "opportunities"],
             "学生として皆さんには独特の機会があります"),
            (["Your", "school", "may", "have", "international", "students"],
             "あなたの学校には留学生がいるかもしれません"),
            (["Introduce", "yourself", "and", "make", "them", "feel", "welcome"],
             "自己紹介をして彼らを歓迎してください"),
            (["Invite", "them", "to", "join", "your", "activities"],
             "あなたの活動に参加するよう招待してください"),
            (["Show", "them", "around", "your", "community"],
             "あなたのコミュニティを案内してください"),
            (["Ask", "about", "their", "home", "country"],
             "彼らの母国について尋ねてください"),
            (["Share", "about", "your", "own", "culture", "too"],
             "自分の文化についても共有してください"),
            (["Join", "cultural", "clubs", "at", "school"],
             "学校の文化クラブに参加してください"),
            (["Many", "schools", "have", "international", "student", "associations"],
             "多くの学校には国際学生協会があります"),
            (["They", "organize", "events", "and", "activities"],
             "イベントや活動を企画します"),
            (["Participate", "in", "cultural", "festivals"],
             "文化祭に参加してください"),
            (["Try", "traditional", "dances", "or", "games"],
             "伝統的なダンスやゲームを試してください"),
            (["Study", "a", "foreign", "language", "seriously"],
             "外国語を真剣に勉強してください"),
            (["Language", "learning", "opens", "doors"],
             "言語学習は扉を開きます"),
            (["Practice", "with", "native", "speakers", "when", "possible"],
             "可能な時はネイティブスピーカーと練習してください"),
            (["Watch", "movies", "and", "shows", "from", "other", "countries"],
             "他の国の映画やショーを見てください"),
            (["Read", "books", "by", "international", "authors"],
             "国際的な著者の本を読んでください"),
            (["Listen", "to", "music", "from", "different", "cultures"],
             "異なる文化の音楽を聴いてください"),
            (["Follow", "social", "media", "accounts", "from", "other", "countries"],
             "他の国のソーシャルメディアアカウントをフォローしてください"),
            (["Read", "international", "news", "sources"],
             "国際ニュースソースを読んでください"),
            (["Understand", "global", "events", "from", "multiple", "perspectives"],
             "複数の視点からグローバルな出来事を理解してください"),
            (["If", "possible", "travel", "during", "school", "breaks"],
             "可能なら学校の休み中に旅行してください"),
            (["Even", "short", "trips", "provide", "valuable", "experiences"],
             "短い旅行でも貴重な経験を提供します"),
            (["Stay", "with", "host", "families", "rather", "than", "hotels"],
             "ホテルよりホストファミリーと滞在してください"),
            (["This", "gives", "authentic", "cultural", "immersion"],
             "これは本物の文化的没入を与えます"),
            
            # Cultural Symbols and Their Meanings
            (["Every", "culture", "has", "important", "symbols"],
             "すべての文化には重要なシンボルがあります"),
            (["National", "flags", "represent", "country", "values", "and", "history"],
             "国旗は国の価値観と歴史を表します"),
            (["Colors", "often", "carry", "special", "meanings"],
             "色はしばしば特別な意味を持ちます"),
            (["In", "China", "red", "means", "good", "luck", "and", "happiness"],
             "中国では赤は幸運と幸福を意味します"),
            (["In", "Western", "cultures", "white", "often", "represents", "purity"],
             "西洋文化では白はしばしば純粋さを表します"),
            (["In", "some", "Asian", "cultures", "white", "is", "associated", "with", "mourning"],
             "一部のアジア文化では白は喪に関連しています"),
            (["Numbers", "can", "be", "lucky", "or", "unlucky"],
             "数字は幸運または不運になることができます"),
            (["In", "Japan", "and", "China", "the", "number", "four", "is", "avoided"],
             "日本と中国では数字の4は避けられます"),
            (["It", "sounds", "like", "the", "word", "for", "death"],
             "死という言葉のように聞こえます"),
            (["In", "Western", "cultures", "thirteen", "is", "considered", "unlucky"],
             "西洋文化では13は不運と考えられます"),
            (["Animals", "have", "symbolic", "meanings", "too"],
             "動物も象徴的な意味を持っています"),
            (["Dragons", "are", "feared", "in", "Western", "stories"],
             "ドラゴンは西洋の物語では恐れられています"),
            (["But", "they", "are", "respected", "and", "revered", "in", "Asian", "cultures"],
             "しかしアジア文化では尊敬され崇拝されています"),
            (["Understanding", "these", "symbols", "prevents", "unintentional", "offense"],
             "これらのシンボルを理解することは意図しない不快感を防ぎます"),
            (["It", "shows", "respect", "for", "cultural", "values"],
             "文化的価値観への敬意を示します"),
            
            # The Role of Humor
            (["Humor", "varies", "greatly", "across", "cultures"],
             "ユーモアは文化によって大きく異なります"),
            (["What", "is", "funny", "in", "one", "place", "may", "not", "translate"],
             "ある場所で面白いことは翻訳できないかもしれません"),
            (["Jokes", "often", "rely", "on", "cultural", "knowledge"],
             "ジョークはしばしば文化的知識に依存します"),
            (["Wordplay", "and", "puns", "do", "not", "cross", "languages", "easily"],
             "言葉遊びとだじゃれは言語を簡単に越えません"),
            (["Some", "cultures", "use", "self", "deprecating", "humor"],
             "一部の文化は自虐的なユーモアを使います"),
            (["Others", "find", "this", "confusing", "or", "inappropriate"],
             "他はこれを混乱させるまたは不適切と思います"),
            (["Sarcasm", "is", "common", "in", "some", "English", "speaking", "countries"],
             "皮肉は一部の英語圏の国で一般的です"),
            (["But", "it", "can", "be", "misunderstood", "by", "non", "native", "speakers"],
             "しかし非ネイティブスピーカーには誤解されることがあります"),
            (["Physical", "comedy", "tends", "to", "be", "more", "universal"],
             "身体的なコメディはより普遍的である傾向があります"),
            (["Laughter", "brings", "people", "together"],
             "笑いは人々を一緒にします"),
            (["Sharing", "humor", "builds", "bonds"],
             "ユーモアを共有することは絆を築きます"),
            (["But", "be", "careful", "with", "jokes", "about", "culture", "or", "religion"],
             "しかし文化や宗教についてのジョークには注意してください"),
            (["What", "you", "intend", "as", "harmless", "may", "offend"],
             "無害と意図したものが気分を害するかもしれません"),
            (["When", "in", "doubt", "laugh", "with", "people", "not", "at", "them"],
             "疑わしい時は人々と一緒に笑い彼らを笑わないでください"),
            
            # Building Your Cultural Competence
            (["Cultural", "competence", "is", "a", "skill", "you", "can", "develop"],
             "文化的能力は開発できるスキルです"),
            (["Start", "by", "examining", "your", "own", "cultural", "identity"],
             "自分の文化的アイデンティティを調べることから始めてください"),
            (["What", "traditions", "does", "your", "family", "follow"],
             "あなたの家族はどんな伝統に従っていますか"),
            (["What", "values", "were", "you", "taught", "as", "a", "child"],
             "子供の頃どんな価値観を教えられましたか"),
            (["How", "does", "your", "culture", "shape", "your", "worldview"],
             "あなたの文化はあなたの世界観をどう形作りますか"),
            (["Understanding", "yourself", "helps", "you", "understand", "others"],
             "自分を理解することは他者を理解するのを助けます"),
            (["Read", "about", "different", "cultures", "systematically"],
             "異なる文化について体系的に読んでください"),
            (["Choose", "one", "culture", "to", "study", "deeply"],
             "深く勉強する一つの文化を選んでください"),
            (["Learn", "its", "history", "geography", "and", "current", "issues"],
             "その歴史地理現在の問題を学んでください"),
            (["Practice", "perspective", "taking", "exercises"],
             "視点を取る練習をしてください"),
            (["Imagine", "situations", "from", "another", "cultural", "viewpoint"],
             "別の文化的視点から状況を想像してください"),
            (["Keep", "a", "journal", "of", "your", "cultural", "learning"],
             "あなたの文化学習の日記をつけてください"),
            (["Record", "new", "things", "you", "discover"],
             "発見した新しいことを記録してください"),
            (["Note", "your", "reactions", "and", "reflections"],
             "あなたの反応と内省を記してください"),
            (["This", "helps", "track", "your", "growth"],
             "これは成長を追跡するのを助けます"),
            (["Seek", "out", "diverse", "friendships"],
             "多様な友情を求めてください"),
            (["Real", "relationships", "teach", "more", "than", "books"],
             "本より実際の関係の方が多くを教えます"),
            (["Be", "patient", "with", "yourself"],
             "自分に対して忍耐強くいてください"),
            (["Cultural", "learning", "is", "a", "lifelong", "journey"],
             "文化学習は生涯の旅です"),
            (["You", "will", "make", "mistakes"],
             "間違いを犯すでしょう"),
            (["Learn", "from", "them", "and", "continue", "growing"],
             "それらから学び成長し続けてください"),
            (["The", "effort", "is", "worthwhile"],
             "努力は価値があります"),
            (["You", "become", "a", "bridge", "between", "worlds"],
             "世界間の橋になります"),
            (["You", "help", "create", "understanding"],
             "理解を作るのを助けます"),
            (["You", "contribute", "to", "a", "more", "peaceful", "world"],
             "より平和な世界に貢献します"),
            (["This", "is", "meaningful", "work"],
             "これは意味のある仕事です"),
            (["This", "is", "how", "we", "change", "the", "world"],
             "これが私たちが世界を変える方法です"),
            (["One", "connection", "at", "a", "time"],
             "一度に一つのつながりで"),
        ]
        
        for words, meaning in content:
            phrases.append(self.create_phrase(f"phrase-{pid}", words, meaning))
            pid += 1
        
        word_count = sum(len(p['words']) for p in phrases)
        
        return {
            "id": "intermediate-4",
            "title": "Cross-Cultural Understanding",
            "level": "中級",
            "theme": "異文化理解",
            "targetWordCount": 2500,
            "actualWordCount": word_count,
            "phrases": phrases
        }
    
    def generate_intermediate_5(self):
        """中級5: Future Careers (3,000語目標)"""
        phrases = []
        pid = 1
        
        content = [
            # Introduction
            (["Choosing", "a", "career", "is", "one", "of", "life", "most", "important", "decisions"],
             "キャリアを選ぶことは人生で最も重要な決定の一つです"),
            (["Your", "career", "affects", "your", "lifestyle", "income", "and", "happiness"],
             "あなたのキャリアはライフスタイル収入幸福に影響します"),
            (["It", "shapes", "who", "you", "become"],
             "それはあなたが誰になるかを形作ります"),
            (["The", "world", "of", "work", "is", "changing", "rapidly"],
             "仕事の世界は急速に変化しています"),
            (["New", "jobs", "are", "created", "while", "others", "disappear"],
             "新しい仕事が作られ他は消えます"),
            (["Technology", "transforms", "how", "we", "work"],
             "テクノロジーは私たちがどう働くかを変えます"),
            (["Globalization", "creates", "new", "opportunities"],
             "グローバル化は新しい機会を作ります"),
            (["Understanding", "these", "changes", "helps", "you", "prepare"],
             "これらの変化を理解することは準備するのを助けます"),
            (["Let", "us", "explore", "careers", "and", "how", "to", "plan", "for", "them"],
             "キャリアとそれらのための計画方法を探りましょう"),
            
            # Understanding Yourself
            (["Career", "planning", "starts", "with", "self", "understanding"],
             "キャリア計画は自己理解から始まります"),
            (["What", "are", "your", "interests"],
             "あなたの興味は何ですか"),
            (["What", "subjects", "do", "you", "enjoy", "studying"],
             "どの科目を勉強するのが好きですか"),
            (["What", "activities", "make", "you", "lose", "track", "of", "time"],
             "どの活動が時間を忘れさせますか"),
            (["Your", "interests", "point", "toward", "suitable", "careers"],
             "あなたの興味は適切なキャリアを指し示します"),
            (["If", "you", "love", "science", "consider", "research", "or", "medicine"],
             "科学が好きなら研究や医学を考えてください"),
            (["If", "you", "enjoy", "helping", "others", "look", "at", "education", "or", "social", "work"],
             "他者を助けるのが好きなら教育や社会福祉を見てください"),
            (["What", "are", "your", "strengths"],
             "あなたの強みは何ですか"),
            (["Are", "you", "good", "with", "numbers"],
             "数字が得意ですか"),
            (["Do", "you", "communicate", "well"],
             "よくコミュニケーションしますか"),
            (["Are", "you", "creative", "or", "analytical"],
             "創造的ですか分析的ですか"),
            (["Do", "you", "prefer", "working", "alone", "or", "in", "teams"],
             "一人で働くのとチームで働くのどちらが好きですか"),
            (["Knowing", "your", "strengths", "guides", "career", "choices"],
             "自分の強みを知ることはキャリア選択を導きます"),
            (["What", "are", "your", "values"],
             "あなたの価値観は何ですか"),
            (["Do", "you", "value", "helping", "society"],
             "社会を助けることを大切にしますか"),
            (["Is", "financial", "security", "important"],
             "経済的安定は重要ですか"),
            (["Do", "you", "want", "work", "life", "balance"],
             "ワークライフバランスが欲しいですか"),
            (["Do", "you", "seek", "adventure", "and", "change"],
             "冒険と変化を求めますか"),
            (["Your", "values", "determine", "career", "satisfaction"],
             "あなたの価値観はキャリアの満足度を決定します"),
            (["A", "high", "paying", "job", "may", "not", "satisfy", "if", "it", "conflicts", "with", "values"],
             "高給の仕事も価値観と対立すれば満足しないかもしれません"),
            
            # Types of Careers
            (["There", "are", "countless", "career", "paths", "available"],
             "無数のキャリアパスが利用可能です"),
            (["Healthcare", "careers", "help", "people", "stay", "healthy"],
             "ヘルスケアのキャリアは人々が健康でいるのを助けます"),
            (["Doctors", "diagnose", "and", "treat", "illnesses"],
             "医師は病気を診断し治療します"),
            (["Nurses", "provide", "direct", "patient", "care"],
             "看護師は直接的な患者ケアを提供します"),
            (["Pharmacists", "dispense", "medications"],
             "薬剤師は薬を調剤します"),
            (["Physical", "therapists", "help", "people", "recover", "from", "injuries"],
             "理学療法士は人々が怪我から回復するのを助けます"),
            (["Healthcare", "workers", "are", "always", "in", "demand"],
             "ヘルスケア労働者は常に需要があります"),
            (["Education", "careers", "shape", "future", "generations"],
             "教育のキャリアは将来の世代を形作ります"),
            (["Teachers", "educate", "students", "in", "various", "subjects"],
             "教師はさまざまな科目で生徒を教育します"),
            (["Principals", "manage", "schools"],
             "校長は学校を管理します"),
            (["Counselors", "guide", "students", "through", "challenges"],
             "カウンセラーは生徒が課題を乗り越えるのを導きます"),
            (["Education", "technology", "specialists", "integrate", "tech", "in", "learning"],
             "教育テクノロジー専門家は学習にテクノロジーを統合します"),
            (["Teaching", "is", "rewarding", "but", "challenging"],
             "教えることはやりがいがありますが困難です"),
            (["Technology", "careers", "are", "growing", "rapidly"],
             "テクノロジーのキャリアは急速に成長しています"),
            (["Software", "developers", "create", "applications", "and", "programs"],
             "ソフトウェア開発者はアプリケーションとプログラムを作ります"),
            (["Data", "scientists", "analyze", "large", "datasets"],
             "データサイエンティストは大規模なデータセットを分析します"),
            (["Cybersecurity", "experts", "protect", "digital", "information"],
             "サイバーセキュリティ専門家はデジタル情報を保護します"),
            (["AI", "specialists", "develop", "artificial", "intelligence", "systems"],
             "AI専門家は人工知能システムを開発します"),
            (["Tech", "jobs", "often", "pay", "well", "and", "offer", "flexibility"],
             "テクノロジーの仕事はしばしば良い給料と柔軟性を提供します"),
            (["Business", "careers", "keep", "organizations", "running"],
             "ビジネスのキャリアは組織を運営し続けます"),
            (["Accountants", "manage", "financial", "records"],
             "会計士は財務記録を管理します"),
            (["Marketing", "specialists", "promote", "products", "and", "services"],
             "マーケティング専門家は製品とサービスを宣伝します"),
            (["Human", "resources", "managers", "handle", "employee", "relations"],
             "人事マネージャーは従業員関係を扱います"),
            (["Entrepreneurs", "start", "their", "own", "businesses"],
             "起業家は自分のビジネスを始めます"),
            (["Business", "skills", "are", "useful", "in", "any", "field"],
             "ビジネススキルはどの分野でも有用です"),
            (["Creative", "careers", "let", "you", "express", "yourself"],
             "クリエイティブなキャリアは自分を表現させます"),
            (["Graphic", "designers", "create", "visual", "content"],
             "グラフィックデザイナーは視覚的なコンテンツを作ります"),
            (["Writers", "produce", "books", "articles", "and", "scripts"],
             "ライターは本記事脚本を制作します"),
            (["Musicians", "and", "artists", "create", "works", "of", "art"],
             "音楽家とアーティストは芸術作品を作ります"),
            (["Filmmakers", "tell", "stories", "through", "video"],
             "映画製作者はビデオを通して物語を語ります"),
            (["Creative", "work", "can", "be", "competitive"],
             "クリエイティブな仕事は競争的になることがあります"),
            (["But", "it", "offers", "great", "personal", "fulfillment"],
             "しかし大きな個人的満足を提供します"),
            (["Science", "and", "research", "careers", "advance", "knowledge"],
             "科学と研究のキャリアは知識を進歩させます"),
            (["Biologists", "study", "living", "organisms"],
             "生物学者は生物を研究します"),
            (["Chemists", "explore", "matter", "and", "its", "properties"],
             "化学者は物質とその性質を探求します"),
            (["Physicists", "investigate", "the", "laws", "of", "nature"],
             "物理学者は自然の法則を調査します"),
            (["Environmental", "scientists", "work", "on", "sustainability"],
             "環境科学者は持続可能性に取り組みます"),
            (["Research", "requires", "patience", "and", "curiosity"],
             "研究は忍耐と好奇心を必要とします"),
            
            # Skills for the Future
            (["Future", "careers", "require", "new", "skills"],
             "将来のキャリアは新しいスキルを必要とします"),
            (["Technical", "skills", "are", "increasingly", "important"],
             "技術的スキルはますます重要になっています"),
            (["Basic", "coding", "knowledge", "helps", "in", "many", "fields"],
             "基本的なコーディング知識は多くの分野で役立ちます"),
            (["Data", "literacy", "is", "essential"],
             "データリテラシーは不可欠です"),
            (["Understanding", "how", "to", "interpret", "data", "matters"],
             "データを解釈する方法を理解することは重要です"),
            (["Digital", "communication", "tools", "are", "everywhere"],
             "デジタルコミュニケーションツールはどこにでもあります"),
            (["Knowing", "how", "to", "use", "them", "effectively", "is", "crucial"],
             "それらを効果的に使う方法を知ることは重要です"),
            (["Soft", "skills", "remain", "vital"],
             "ソフトスキルは重要なままです"),
            (["Communication", "skills", "are", "always", "needed"],
             "コミュニケーションスキルは常に必要です"),
            (["You", "must", "explain", "ideas", "clearly"],
             "アイデアを明確に説明しなければなりません"),
            (["You", "must", "listen", "to", "understand", "others"],
             "他者を理解するために聞かなければなりません"),
            (["Teamwork", "is", "essential", "in", "most", "workplaces"],
             "チームワークはほとんどの職場で不可欠です"),
            (["You", "collaborate", "with", "colleagues", "on", "projects"],
             "プロジェクトで同僚と協力します"),
            (["Different", "perspectives", "lead", "to", "better", "solutions"],
             "異なる視点はより良い解決策につながります"),
            (["Problem", "solving", "abilities", "are", "highly", "valued"],
             "問題解決能力は高く評価されます"),
            (["You", "face", "challenges", "in", "any", "job"],
             "どの仕事でも課題に直面します"),
            (["Finding", "creative", "solutions", "sets", "you", "apart"],
             "創造的な解決策を見つけることがあなたを際立たせます"),
            (["Critical", "thinking", "helps", "you", "analyze", "situations"],
             "批判的思考は状況を分析するのを助けます"),
            (["You", "evaluate", "information", "objectively"],
             "情報を客観的に評価します"),
            (["You", "make", "informed", "decisions"],
             "情報に基づいた決定を下します"),
            (["Adaptability", "is", "crucial", "in", "changing", "times"],
             "変化する時代には適応性が重要です"),
            (["Jobs", "evolve", "constantly"],
             "仕事は常に進化します"),
            (["You", "must", "be", "willing", "to", "learn", "new", "things"],
             "新しいことを学ぶ意欲が必要です"),
            (["Emotional", "intelligence", "matters", "more", "than", "ever"],
             "感情知能がこれまで以上に重要です"),
            (["Understanding", "your", "own", "emotions", "helps"],
             "自分の感情を理解することは助けになります"),
            (["Recognizing", "others", "feelings", "builds", "better", "relationships"],
             "他者の感情を認識することはより良い関係を築きます"),
            
            # Education and Training
            (["Different", "careers", "require", "different", "education"],
             "異なるキャリアは異なる教育を必要とします"),
            (["Some", "jobs", "need", "university", "degrees"],
             "一部の仕事は大学の学位を必要とします"),
            (["Doctors", "and", "lawyers", "study", "for", "many", "years"],
             "医師と弁護士は何年も勉強します"),
            (["Engineers", "and", "scientists", "need", "specialized", "knowledge"],
             "エンジニアと科学者は専門知識を必要とします"),
            (["Teachers", "require", "education", "degrees", "and", "certification"],
             "教師は教育学位と資格を必要とします"),
            (["Other", "careers", "value", "skills", "over", "formal", "degrees"],
             "他のキャリアは正式な学位より技能を重視します"),
            (["Many", "tech", "companies", "hire", "based", "on", "ability"],
             "多くのテクノロジー企業は能力に基づいて雇用します"),
            (["Portfolios", "and", "projects", "demonstrate", "skills"],
             "ポートフォリオとプロジェクトはスキルを実証します"),
            (["Online", "courses", "and", "certifications", "are", "valuable"],
             "オンラインコースと資格は価値があります"),
            (["Vocational", "training", "prepares", "you", "for", "specific", "trades"],
             "職業訓練は特定の職業のために準備します"),
            (["Electricians", "plumbers", "and", "carpenters", "learn", "through", "apprenticeships"],
             "電気技師配管工大工は見習いを通して学びます"),
            (["These", "skilled", "trades", "are", "well", "paid"],
             "これらの熟練した職業は良い給料です"),
            (["They", "are", "also", "in", "high", "demand"],
             "高い需要もあります"),
            (["Continuing", "education", "is", "becoming", "the", "norm"],
             "継続教育が標準になっています"),
            (["Your", "learning", "does", "not", "stop", "after", "school"],
             "学校の後も学習は止まりません"),
            (["You", "take", "courses", "throughout", "your", "career"],
             "キャリアを通してコースを受講します"),
            (["You", "attend", "workshops", "and", "conferences"],
             "ワークショップと会議に参加します"),
            (["You", "stay", "updated", "with", "industry", "changes"],
             "業界の変化に遅れないようにします"),
            (["Lifelong", "learning", "keeps", "you", "competitive"],
             "生涯学習はあなたを競争力のある状態に保ちます"),
            
            # Work Environment Changes
            (["The", "workplace", "is", "transforming"],
             "職場は変革しています"),
            (["Remote", "work", "is", "increasingly", "common"],
             "リモートワークはますます一般的です"),
            (["Many", "people", "now", "work", "from", "home"],
             "多くの人が今家から働きます"),
            (["Video", "conferences", "replace", "in", "person", "meetings"],
             "ビデオ会議が対面会議に取って代わります"),
            (["This", "offers", "flexibility"],
             "これは柔軟性を提供します"),
            (["You", "can", "live", "anywhere", "with", "internet"],
             "インターネットがあればどこにでも住めます"),
            (["You", "save", "commuting", "time"],
             "通勤時間を節約します"),
            (["However", "remote", "work", "has", "challenges"],
             "しかしリモートワークには課題があります"),
            (["Maintaining", "work", "life", "boundaries", "becomes", "harder"],
             "仕事と生活の境界を維持することが難しくなります"),
            (["Feeling", "isolated", "is", "common"],
             "孤立感を感じることは一般的です"),
            (["Building", "relationships", "with", "colleagues", "requires", "effort"],
             "同僚との関係を築くには努力が必要です"),
            (["The", "gig", "economy", "is", "growing"],
             "ギグエコノミーは成長しています"),
            (["More", "people", "work", "as", "freelancers", "or", "contractors"],
             "より多くの人々がフリーランサーや請負業者として働きます"),
            (["They", "have", "multiple", "clients", "instead", "of", "one", "employer"],
             "一人の雇用主の代わりに複数のクライアントがいます"),
            (["This", "provides", "freedom", "and", "variety"],
             "これは自由と多様性を提供します"),
            (["But", "it", "lacks", "job", "security", "and", "benefits"],
             "しかし仕事の安定と福利厚生がありません"),
            (["Traditional", "career", "ladders", "are", "changing"],
             "伝統的なキャリアラダーは変化しています"),
            (["People", "no", "longer", "work", "for", "one", "company", "their", "whole", "life"],
             "人々はもはや一生一つの会社で働きません"),
            (["Job", "hopping", "is", "more", "acceptable"],
             "転職はより受け入れられています"),
            (["You", "might", "change", "careers", "several", "times"],
             "何度かキャリアを変えるかもしれません"),
            (["This", "requires", "adaptability", "and", "continuous", "learning"],
             "これは適応性と継続的な学習を必要とします"),
            
            # Emerging Careers
            (["New", "careers", "emerge", "as", "technology", "advances"],
             "テクノロジーが進歩するにつれて新しいキャリアが出現します"),
            (["Renewable", "energy", "technicians", "install", "solar", "panels", "and", "wind", "turbines"],
             "再生可能エネルギー技術者はソーラーパネルと風力タービンを設置します"),
            (["As", "we", "shift", "to", "clean", "energy", "these", "jobs", "grow"],
             "クリーンエネルギーに移行するにつれてこれらの仕事は成長します"),
            (["Drone", "operators", "pilot", "unmanned", "aircraft"],
             "ドローンオペレーターは無人航空機を操縦します"),
            (["They", "work", "in", "photography", "delivery", "and", "agriculture"],
             "写真配送農業で働きます"),
            (["Virtual", "reality", "designers", "create", "immersive", "experiences"],
             "バーチャルリアリティデザイナーは没入型体験を作ります"),
            (["VR", "is", "used", "in", "gaming", "training", "and", "therapy"],
             "VRはゲームトレーニング治療に使われます"),
            (["Genetic", "counselors", "help", "people", "understand", "DNA", "tests"],
             "遺伝カウンセラーは人々がDNA検査を理解するのを助けます"),
            (["As", "genetic", "medicine", "advances", "their", "role", "grows"],
             "遺伝医学が進歩するにつれて彼らの役割は成長します"),
            (["Sustainability", "consultants", "help", "companies", "reduce", "environmental", "impact"],
             "持続可能性コンサルタントは企業が環境への影響を減らすのを助けます"),
            (["Green", "jobs", "will", "be", "crucial", "for", "our", "future"],
             "グリーンジョブは私たちの未来にとって重要です"),
            (["Social", "media", "managers", "handle", "online", "presence"],
             "ソーシャルメディアマネージャーはオンラインプレゼンスを扱います"),
            (["This", "career", "did", "not", "exist", "twenty", "years", "ago"],
             "このキャリアは20年前には存在しませんでした"),
            (["Now", "every", "company", "needs", "digital", "marketing"],
             "今ではすべての企業がデジタルマーケティングを必要とします"),
            (["App", "developers", "create", "mobile", "applications"],
             "アプリ開発者はモバイルアプリケーションを作ります"),
            (["With", "billions", "of", "smartphone", "users", "demand", "is", "high"],
             "何十億ものスマートフォンユーザーがいるため需要は高いです"),
            
            # Preparing Now
            (["You", "can", "start", "preparing", "for", "your", "career", "today"],
             "今日からキャリアの準備を始めることができます"),
            (["Study", "hard", "in", "all", "subjects"],
             "すべての科目を一生懸命勉強してください"),
            (["Math", "and", "science", "open", "many", "doors"],
             "数学と科学は多くの扉を開きます"),
            (["Languages", "help", "in", "global", "careers"],
             "言語はグローバルなキャリアで役立ちます"),
            (["Even", "subjects", "you", "dislike", "teach", "valuable", "skills"],
             "好きでない科目でさえ価値あるスキルを教えます"),
            (["Explore", "your", "interests", "through", "clubs", "and", "activities"],
             "クラブや活動を通して興味を探求してください"),
            (["Join", "robotics", "club", "if", "you", "like", "engineering"],
             "エンジニアリングが好きならロボティクスクラブに参加してください"),
            (["Participate", "in", "debate", "to", "improve", "communication"],
             "コミュニケーションを改善するためにディベートに参加してください"),
            (["Volunteer", "to", "discover", "if", "you", "enjoy", "helping", "others"],
             "他者を助けることが好きかどうか発見するためにボランティアをしてください"),
            (["Seek", "out", "mentors"],
             "メンターを探してください"),
            (["Talk", "to", "adults", "in", "careers", "that", "interest", "you"],
             "興味のあるキャリアの大人と話してください"),
            (["Ask", "about", "their", "education", "and", "experiences"],
             "彼らの教育と経験について尋ねてください"),
            (["Learn", "from", "their", "successes", "and", "mistakes"],
             "彼らの成功と失敗から学んでください"),
            (["Get", "work", "experience", "early"],
             "早く仕事経験を得てください"),
            (["Part", "time", "jobs", "teach", "responsibility"],
             "アルバイトは責任を教えます"),
            (["Internships", "provide", "industry", "exposure"],
             "インターンシップは業界への露出を提供します"),
            (["Even", "unpaid", "experience", "builds", "your", "resume"],
             "無給の経験でさえ履歴書を作ります"),
            (["Develop", "a", "growth", "mindset"],
             "成長マインドセットを発展させてください"),
            (["Believe", "that", "abilities", "can", "be", "developed"],
             "能力は発展させることができると信じてください"),
            (["Embrace", "challenges", "as", "learning", "opportunities"],
             "学習の機会として挑戦を受け入れてください"),
            (["Do", "not", "fear", "failure"],
             "失敗を恐れないでください"),
            (["It", "is", "part", "of", "the", "learning", "process"],
             "それは学習プロセスの一部です"),
            
            # Conclusion
            (["Your", "career", "journey", "is", "uniquely", "yours"],
             "あなたのキャリアの旅はあなた独自のものです"),
            (["There", "is", "no", "single", "right", "path"],
             "唯一の正しい道はありません"),
            (["What", "matters", "is", "finding", "work", "that", "fulfills", "you"],
             "重要なのはあなたを満たす仕事を見つけることです"),
            (["Work", "that", "uses", "your", "talents"],
             "あなたの才能を使う仕事"),
            (["Work", "that", "aligns", "with", "your", "values"],
             "あなたの価値観と一致する仕事"),
            (["Work", "that", "contributes", "to", "something", "larger"],
             "より大きな何かに貢献する仕事"),
            (["The", "future", "of", "work", "is", "uncertain"],
             "仕事の未来は不確実です"),
            (["But", "this", "brings", "excitement", "and", "possibility"],
             "しかしこれは興奮と可能性をもたらします"),
            (["You", "have", "opportunities", "previous", "generations", "never", "had"],
             "以前の世代が決して持たなかった機会があります"),
            (["Technology", "enables", "innovation"],
             "テクノロジーは革新を可能にします"),
            (["Globalization", "expands", "horizons"],
             "グローバル化は視野を広げます"),
            (["The", "key", "is", "preparation"],
             "鍵は準備です"),
            (["Build", "strong", "foundations", "now"],
             "今強い基盤を築いてください"),
            (["Develop", "both", "technical", "and", "soft", "skills"],
             "技術的スキルとソフトスキルの両方を発展させてください"),
            (["Stay", "curious", "and", "keep", "learning"],
             "好奇心を持ち続け学び続けてください"),
            (["Be", "flexible", "and", "adapt", "to", "change"],
             "柔軟で変化に適応してください"),
            (["Your", "career", "will", "likely", "take", "unexpected", "turns"],
             "あなたのキャリアはおそらく予期しない転機を迎えます"),
            (["That", "is", "not", "failure"],
             "それは失敗ではありません"),
            (["It", "is", "growth", "and", "evolution"],
             "それは成長と進化です"),
            (["Embrace", "the", "journey"],
             "旅を受け入れてください"),
            (["Each", "experience", "teaches", "you", "something"],
             "各経験は何かを教えます"),
            (["Each", "challenge", "makes", "you", "stronger"],
             "各挑戦はあなたを強くします"),
            (["Your", "career", "is", "not", "just", "about", "earning", "money"],
             "あなたのキャリアはただお金を稼ぐことだけではありません"),
            (["It", "is", "about", "making", "a", "difference"],
             "違いを生み出すことです"),
            (["Contributing", "your", "unique", "gifts", "to", "the", "world"],
             "あなたのユニークな才能を世界に貢献することです"),
            (["Finding", "meaning", "and", "purpose"],
             "意味と目的を見つけることです"),
            (["The", "world", "needs", "your", "talents"],
             "世界はあなたの才能を必要としています"),
            (["Whatever", "career", "you", "choose"],
             "どのキャリアを選んでも"),
            (["Give", "it", "your", "best"],
             "最善を尽くしてください"),
            (["Work", "with", "integrity", "and", "passion"],
             "誠実さと情熱を持って働いてください"),
            (["Your", "future", "is", "bright"],
             "あなたの未来は明るいです"),
            (["It", "is", "full", "of", "possibilities"],
             "可能性に満ちています"),
            (["Start", "building", "it", "today"],
             "今日それを築き始めてください"),
            
            # Finding Balance
            (["Work", "life", "balance", "is", "increasingly", "important"],
             "ワークライフバランスはますます重要になっています"),
            (["Many", "people", "work", "long", "hours"],
             "多くの人々は長時間働きます"),
            (["This", "can", "lead", "to", "stress", "and", "burnout"],
             "これはストレスと燃え尽きにつながる可能性があります"),
            (["Your", "health", "matters", "more", "than", "your", "job"],
             "あなたの健康は仕事より重要です"),
            (["Make", "time", "for", "family", "and", "friends"],
             "家族と友人のための時間を作ってください"),
            (["Pursue", "hobbies", "and", "interests", "outside", "work"],
             "仕事以外の趣味と興味を追求してください"),
            (["Take", "vacations", "to", "recharge"],
             "充電するために休暇を取ってください"),
            (["Some", "careers", "offer", "better", "balance", "than", "others"],
             "一部のキャリアは他よりも良いバランスを提供します"),
            (["Consider", "this", "when", "choosing", "your", "path"],
             "あなたの道を選ぶときにこれを考慮してください"),
            (["High", "paying", "jobs", "may", "require", "more", "hours"],
             "高給の仕事はより多くの時間を必要とするかもしれません"),
            (["Lower", "stress", "jobs", "may", "pay", "less"],
             "ストレスが少ない仕事は給料が少ないかもしれません"),
            (["Only", "you", "can", "decide", "what", "matters", "most"],
             "何が最も重要か決められるのはあなただけです"),
            (["Money", "is", "important", "for", "security"],
             "お金は安全のために重要です"),
            (["But", "happiness", "comes", "from", "more", "than", "wealth"],
             "しかし幸福は富以上のものから来ます"),
            (["Job", "satisfaction", "affects", "overall", "well", "being"],
             "仕事の満足度は全体的な幸福に影響します"),
            (["If", "you", "hate", "your", "work", "no", "salary", "compensates"],
             "仕事が嫌いならどんな給料も補償しません"),
            (["Find", "work", "that", "energizes", "you"],
             "あなたに活力を与える仕事を見つけてください"),
            (["Work", "that", "you", "look", "forward", "to"],
             "楽しみにする仕事"),
            (["This", "makes", "life", "more", "enjoyable"],
             "これは人生をより楽しくします"),
            
            # Overcoming Obstacles
            (["Your", "career", "path", "will", "have", "obstacles"],
             "あなたのキャリアパスには障害があります"),
            (["You", "may", "face", "rejection"],
             "拒否に直面するかもしれません"),
            (["Job", "applications", "get", "turned", "down"],
             "求人応募は断られます"),
            (["Interviews", "do", "not", "always", "go", "well"],
             "面接は常にうまくいくわけではありません"),
            (["Do", "not", "take", "it", "personally"],
             "個人的に受け取らないでください"),
            (["Each", "rejection", "teaches", "you", "something"],
             "各拒否は何かを教えます"),
            (["It", "helps", "you", "improve"],
             "改善するのを助けます"),
            (["Persistence", "is", "key"],
             "粘り強さが鍵です"),
            (["You", "may", "face", "discrimination"],
             "差別に直面するかもしれません"),
            (["Unfortunately", "bias", "still", "exists"],
             "残念ながら偏見はまだ存在します"),
            (["Some", "face", "barriers", "due", "to", "gender", "race", "or", "background"],
             "性別人種背景による障壁に直面する人もいます"),
            (["This", "is", "unfair", "and", "wrong"],
             "これは不公平で間違っています"),
            (["But", "do", "not", "let", "it", "stop", "you"],
             "しかしそれがあなたを止めさせないでください"),
            (["Your", "talent", "and", "hard", "work", "will", "shine", "through"],
             "あなたの才能と努力は輝きます"),
            (["Seek", "out", "supportive", "environments"],
             "支援的な環境を求めてください"),
            (["Find", "mentors", "who", "believe", "in", "you"],
             "あなたを信じるメンターを見つけてください"),
            (["Join", "professional", "organizations", "that", "support", "diversity"],
             "多様性を支援する専門組織に参加してください"),
            (["Financial", "constraints", "are", "another", "obstacle"],
             "経済的制約は別の障害です"),
            (["Not", "everyone", "can", "afford", "expensive", "education"],
             "誰もが高価な教育を受ける余裕があるわけではありません"),
            (["Look", "for", "scholarships", "and", "grants"],
             "奨学金と助成金を探してください"),
            (["Consider", "community", "colleges", "for", "affordable", "education"],
             "手頃な教育のためにコミュニティカレッジを検討してください"),
            (["Work", "part", "time", "while", "studying"],
             "勉強しながらアルバイトをしてください"),
            (["Many", "successful", "people", "overcame", "financial", "hardship"],
             "多くの成功した人々は経済的困難を克服しました"),
            (["Your", "determination", "matters", "more", "than", "your", "starting", "point"],
             "あなたの決意は出発点より重要です"),
            
            # Networking and Relationships
            (["Networking", "is", "crucial", "for", "career", "success"],
             "ネットワーキングはキャリアの成功に重要です"),
            (["Many", "jobs", "are", "filled", "through", "connections"],
             "多くの仕事はつながりを通して埋められます"),
            (["Who", "you", "know", "can", "open", "doors"],
             "誰を知っているかが扉を開くことができます"),
            (["Start", "building", "your", "network", "now"],
             "今ネットワークを構築し始めてください"),
            (["Connect", "with", "classmates", "and", "teachers"],
             "クラスメートと教師とつながってください"),
            (["They", "may", "help", "you", "later"],
             "彼らは後であなたを助けるかもしれません"),
            (["Attend", "industry", "events", "and", "conferences"],
             "業界のイベントと会議に参加してください"),
            (["Introduce", "yourself", "to", "professionals"],
             "プロフェッショナルに自己紹介してください"),
            (["Ask", "thoughtful", "questions"],
             "思慮深い質問をしてください"),
            (["Follow", "up", "with", "thank", "you", "messages"],
             "感謝のメッセージでフォローアップしてください"),
            (["Use", "social", "media", "professionally"],
             "ソーシャルメディアをプロフェッショナルに使ってください"),
            (["LinkedIn", "is", "essential", "for", "professionals"],
             "LinkedInはプロフェッショナルにとって不可欠です"),
            (["Create", "a", "strong", "profile"],
             "強力なプロフィールを作成してください"),
            (["Share", "your", "achievements", "and", "interests"],
             "あなたの業績と興味を共有してください"),
            (["Connect", "with", "people", "in", "your", "field"],
             "あなたの分野の人々とつながってください"),
            (["Networking", "is", "not", "just", "about", "taking"],
             "ネットワーキングは受け取るだけではありません"),
            (["Offer", "help", "to", "others"],
             "他者に助けを提供してください"),
            (["Share", "useful", "information"],
             "有用な情報を共有してください"),
            (["Make", "introductions", "between", "people"],
             "人々の間で紹介をしてください"),
            (["Building", "genuine", "relationships", "matters"],
             "本物の関係を築くことが重要です"),
            (["People", "can", "tell", "if", "you", "are", "sincere"],
             "あなたが誠実かどうか人々は分かります"),
            (["Be", "authentic", "and", "interested"],
             "本物で興味を持ってください"),
            
            # Personal Branding
            (["In", "today", "world", "you", "are", "a", "brand"],
             "今日の世界ではあなたはブランドです"),
            (["Your", "reputation", "precedes", "you"],
             "あなたの評判があなたに先行します"),
            (["Build", "a", "positive", "online", "presence"],
             "ポジティブなオンラインプレゼンスを構築してください"),
            (["Google", "yourself", "regularly"],
             "定期的に自分自身をググってください"),
            (["See", "what", "others", "find"],
             "他者が何を見つけるか見てください"),
            (["Remove", "or", "hide", "inappropriate", "content"],
             "不適切なコンテンツを削除または非表示にしてください"),
            (["Share", "content", "that", "reflects", "your", "interests"],
             "あなたの興味を反映するコンテンツを共有してください"),
            (["Write", "blog", "posts", "or", "articles"],
             "ブログ投稿や記事を書いてください"),
            (["This", "demonstrates", "expertise"],
             "これは専門知識を示します"),
            (["Create", "projects", "to", "showcase", "skills"],
             "スキルを披露するプロジェクトを作成してください"),
            (["Build", "a", "portfolio", "website"],
             "ポートフォリオウェブサイトを構築してください"),
            (["Display", "your", "best", "work"],
             "あなたの最高の作品を表示してください"),
            (["Your", "personal", "brand", "should", "be", "consistent"],
             "あなたの個人ブランドは一貫しているべきです"),
            (["How", "you", "present", "yourself", "online", "and", "offline", "should", "match"],
             "オンラインとオフラインでの自己表現は一致するべきです"),
            (["Be", "professional", "in", "all", "interactions"],
             "すべての交流でプロフェッショナルでいてください"),
            (["Your", "behavior", "reflects", "on", "your", "brand"],
             "あなたの行動はあなたのブランドを反映します"),
            
            # Interview Skills
            (["Eventually", "you", "will", "face", "job", "interviews"],
             "最終的に就職面接に直面します"),
            (["Preparation", "is", "essential"],
             "準備は不可欠です"),
            (["Research", "the", "company", "thoroughly"],
             "会社を徹底的に調査してください"),
            (["Understand", "their", "mission", "and", "values"],
             "彼らの使命と価値観を理解してください"),
            (["Know", "their", "products", "and", "services"],
             "彼らの製品とサービスを知ってください"),
            (["Prepare", "answers", "to", "common", "questions"],
             "一般的な質問への回答を準備してください"),
            (["Why", "do", "you", "want", "this", "job"],
             "なぜこの仕事が欲しいのですか"),
            (["What", "are", "your", "strengths", "and", "weaknesses"],
             "あなたの強みと弱みは何ですか"),
            (["Where", "do", "you", "see", "yourself", "in", "five", "years"],
             "5年後にどこにいると思いますか"),
            (["Practice", "your", "answers", "out", "loud"],
             "答えを声に出して練習してください"),
            (["But", "do", "not", "memorize", "word", "for", "word"],
             "しかし一語一語暗記しないでください"),
            (["Sound", "natural", "and", "genuine"],
             "自然で本物に聞こえてください"),
            (["Dress", "appropriately", "for", "the", "interview"],
             "面接に適切に服装してください"),
            (["Different", "industries", "have", "different", "dress", "codes"],
             "異なる業界には異なるドレスコードがあります"),
            (["When", "in", "doubt", "dress", "more", "formally"],
             "疑わしい時はよりフォーマルに服装してください"),
            (["Arrive", "early"],
             "早く到着してください"),
            (["Being", "late", "creates", "a", "bad", "impression"],
             "遅刻は悪い印象を与えます"),
            (["Bring", "copies", "of", "your", "resume"],
             "履歴書のコピーを持参してください"),
            (["During", "the", "interview", "make", "eye", "contact"],
             "面接中はアイコンタクトをしてください"),
            (["Smile", "and", "show", "enthusiasm"],
             "笑顔で熱意を示してください"),
            (["Listen", "carefully", "to", "questions"],
             "質問を注意深く聞いてください"),
            (["Take", "a", "moment", "to", "think", "before", "answering"],
             "答える前に考える瞬間を取ってください"),
            (["Ask", "thoughtful", "questions", "about", "the", "role"],
             "役割について思慮深い質問をしてください"),
            (["This", "shows", "genuine", "interest"],
             "これは本物の興味を示します"),
            (["After", "the", "interview", "send", "a", "thank", "you", "email"],
             "面接後に感謝のメールを送ってください"),
            (["Reiterate", "your", "interest", "in", "the", "position"],
             "ポジションへの興味を繰り返してください"),
            (["Mention", "something", "specific", "from", "the", "conversation"],
             "会話から具体的な何かに言及してください"),
            (["This", "keeps", "you", "memorable"],
             "これはあなたを記憶に残します"),
            
            # Career Success Principles
            (["Once", "you", "start", "your", "career", "certain", "principles", "lead", "to", "success"],
             "キャリアを始めたら特定の原則が成功につながります"),
            (["Always", "be", "learning"],
             "常に学び続けてください"),
            (["The", "most", "successful", "people", "never", "stop", "growing"],
             "最も成功した人々は決して成長を止めません"),
            (["Take", "initiative"],
             "イニシアチブを取ってください"),
            (["Do", "not", "wait", "to", "be", "told", "what", "to", "do"],
             "何をすべきか言われるのを待たないでください"),
            (["Identify", "problems", "and", "solve", "them"],
             "問題を特定して解決してください"),
            (["Be", "reliable"],
             "信頼できる人でいてください"),
            (["Meet", "deadlines", "consistently"],
             "締め切りを一貫して守ってください"),
            (["Follow", "through", "on", "commitments"],
             "約束を守り抜いてください"),
            (["People", "value", "dependability"],
             "人々は信頼性を評価します"),
            (["Communicate", "clearly"],
             "明確にコミュニケーションしてください"),
            (["Express", "ideas", "concisely"],
             "アイデアを簡潔に表現してください"),
            (["Listen", "actively", "to", "colleagues"],
             "同僚に積極的に耳を傾けてください"),
            (["Good", "communication", "prevents", "many", "problems"],
             "良いコミュニケーションは多くの問題を防ぎます"),
            (["Build", "strong", "relationships", "at", "work"],
             "職場で強い関係を築いてください"),
            (["Help", "your", "colleagues"],
             "同僚を助けてください"),
            (["Be", "positive", "and", "supportive"],
             "ポジティブで支援的でいてください"),
            (["Office", "politics", "exist"],
             "オフィス政治は存在します"),
            (["But", "focus", "on", "your", "work", "and", "integrity"],
             "しかし自分の仕事と誠実さに焦点を当ててください"),
            (["Seek", "feedback", "regularly"],
             "定期的にフィードバックを求めてください"),
            (["Ask", "your", "supervisor", "how", "you", "can", "improve"],
             "どう改善できるか上司に尋ねてください"),
            (["Do", "not", "be", "defensive"],
             "防御的にならないでください"),
            (["Use", "criticism", "constructively"],
             "批判を建設的に使ってください"),
            (["Set", "goals", "for", "your", "career"],
             "キャリアの目標を設定してください"),
            (["Where", "do", "you", "want", "to", "be", "in", "one", "year"],
             "1年後にどこにいたいですか"),
            (["In", "five", "years"],
             "5年後には"),
            (["Create", "a", "plan", "to", "reach", "those", "goals"],
             "それらの目標に到達する計画を作成してください"),
            (["Review", "and", "adjust", "regularly"],
             "定期的に見直して調整してください"),
            (["Most", "importantly", "maintain", "your", "ethics"],
             "最も重要なのは倫理を維持することです"),
            (["Never", "compromise", "your", "values", "for", "success"],
             "成功のために価値観を妥協しないでください"),
            (["Shortcuts", "and", "dishonesty", "catch", "up", "eventually"],
             "近道と不正直は最終的に追いつきます"),
            (["Your", "reputation", "is", "invaluable"],
             "あなたの評判は貴重です"),
            (["Protect", "it"],
             "それを守ってください"),
            (["Success", "built", "on", "integrity", "lasts"],
             "誠実さの上に築かれた成功は持続します"),
            (["That", "is", "true", "achievement"],
             "それが真の達成です"),
        ]
        
        for words, meaning in content:
            phrases.append(self.create_phrase(f"phrase-{pid}", words, meaning))
            pid += 1
        
        word_count = sum(len(p['words']) for p in phrases)
        
        return {
            "id": "intermediate-5",
            "title": "Future Careers",
            "level": "中級",
            "theme": "将来のキャリア",
            "targetWordCount": 3000,
            "actualWordCount": word_count,
            "phrases": phrases
        }
    
    def save_passage(self, passage):
        """パッセージをJSONファイルに保存"""
        output_path = self.output_dir / f"{passage['id']}.json"
        with open(output_path, 'w', encoding='utf-8') as f:
            json.dump(passage, f, ensure_ascii=False, indent=2)
        print(f"✓ {passage['id']}: {passage['actualWordCount']}語 - {output_path}")


def main():
    print("="*70)
    print("残りパッセージ生成 - intermediate-4, 5")
    print("="*70)
    print()
    
    generator = RemainingPassagesGenerator()
    
    print("生成中: intermediate-4...")
    passage4 = generator.generate_intermediate_4()
    generator.save_passage(passage4)
    
    print("生成中: intermediate-5...")
    passage5 = generator.generate_intermediate_5()
    generator.save_passage(passage5)
    
    total = passage4['actualWordCount'] + passage5['actualWordCount']
    
    print()
    print("="*70)
    print(f"✓ 生成完了: 合計{total}語")
    print(f"  intermediate-4: {passage4['actualWordCount']}語")
    print(f"  intermediate-5: {passage5['actualWordCount']}語")
    print("="*70)


if __name__ == "__main__":
    main()
