#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
高品質長文パッセージ生成ツール
完全手動作成による自然で具体的な英文と日本語訳
"""

import json
from pathlib import Path

class QualityPassageGenerator:
    """高品質パッセージジェネレーター"""
    
    def __init__(self):
        self.output_dir = Path("prototype")
        self.output_dir.mkdir(exist_ok=True)
    
    def create_phrase(self, phrase_id, words, meaning):
        """フレーズを作成"""
        return {
            "id": phrase_id,
            "words": words,
            "phraseMeaning": meaning,
            "segments": [{"word": w, "meaning": "", "isUnknown": False} for w in words],
            "isUnknown": False
        }
    
    def generate_intermediate_1(self):
        """intermediate-1: 環境保護 (1,500語目標)"""
        phrases = []
        pid = 1
        
        # Introduction
        content = [
            (["Our", "environment", "is", "very", "important", "to", "all", "of", "us"], 
             "私たちの環境は私たち全員にとってとても重要です"),
            (["We", "depend", "on", "clean", "air", "fresh", "water", "and", "healthy", "land"], 
             "私たちはきれいな空気、新鮮な水、健康な土地に依存しています"),
            (["However", "our", "planet", "faces", "many", "environmental", "problems", "today"], 
             "しかし私たちの惑星は今日多くの環境問題に直面しています"),
            (["These", "problems", "affect", "not", "only", "humans", "but", "also", "animals", "and", "plants"], 
             "これらの問題は人間だけでなく動物や植物にも影響します"),
            (["We", "must", "understand", "these", "issues", "and", "take", "action"], 
             "私たちはこれらの問題を理解し行動を起こさなければなりません"),
            
            # Air Pollution
            (["Air", "pollution", "is", "one", "of", "the", "most", "serious", "problems"], 
             "大気汚染は最も深刻な問題の一つです"),
            (["The", "air", "we", "breathe", "every", "day", "is", "becoming", "dirty"], 
             "私たちが毎日吸う空気は汚れてきています"),
            (["Cars", "trucks", "and", "buses", "release", "harmful", "gases"], 
             "車、トラック、バスが有害なガスを放出します"),
            (["Factories", "and", "power", "plants", "also", "produce", "smoke"], 
             "工場や発電所も煙を出します"),
            (["This", "smoke", "contains", "dangerous", "chemicals"], 
             "この煙には危険な化学物質が含まれています"),
            (["When", "we", "breathe", "polluted", "air", "it", "can", "make", "us", "sick"], 
             "汚染された空気を吸うと私たちは病気になることがあります"),
            (["Children", "and", "elderly", "people", "are", "especially", "at", "risk"], 
             "子供や高齢者は特に危険にさらされています"),
            (["Air", "pollution", "can", "cause", "breathing", "problems", "and", "heart", "disease"], 
             "大気汚染は呼吸器疾患や心臓病を引き起こす可能性があります"),
            (["In", "some", "cities", "the", "air", "is", "so", "bad", "people", "wear", "masks"], 
             "一部の都市では空気がとても悪く人々はマスクを着用します"),
            (["We", "need", "to", "reduce", "the", "amount", "of", "pollution", "in", "the", "air"], 
             "私たちは空気中の汚染物質の量を減らす必要があります"),
            
            # Water Pollution
            (["Water", "pollution", "is", "another", "major", "concern"], 
             "水質汚染も大きな懸念事項です"),
            (["Clean", "water", "is", "essential", "for", "life"], 
             "きれいな水は生命に不可欠です"),
            (["We", "use", "water", "for", "drinking", "cooking", "and", "washing"], 
             "私たちは飲む、料理する、洗うために水を使います"),
            (["But", "many", "rivers", "lakes", "and", "oceans", "are", "polluted"], 
             "しかし多くの川、湖、海が汚染されています"),
            (["Factories", "sometimes", "dump", "waste", "into", "rivers"], 
             "工場は時々廃棄物を川に捨てます"),
            (["Farmers", "use", "chemicals", "on", "crops", "that", "wash", "into", "streams"], 
             "農家は作物に使用する化学物質が小川に流れ込みます"),
            (["Plastic", "waste", "is", "a", "huge", "problem", "in", "our", "oceans"], 
             "プラスチックごみは海で大きな問題です"),
            (["Every", "year", "millions", "of", "tons", "of", "plastic", "enter", "the", "sea"], 
             "毎年何百万トンものプラスチックが海に入ります"),
            (["Sea", "turtles", "dolphins", "and", "whales", "often", "eat", "plastic", "by", "mistake"], 
             "ウミガメ、イルカ、クジラはしばしば誤ってプラスチックを食べます"),
            (["This", "plastic", "can", "kill", "them"], 
             "このプラスチックは彼らを殺すことがあります"),
            (["Fish", "that", "eat", "small", "plastic", "pieces", "can", "also", "harm", "humans"], 
             "小さなプラスチック片を食べる魚は人間にも害を及ぼす可能性があります"),
            (["When", "we", "eat", "these", "fish", "the", "plastic", "enters", "our", "bodies"], 
             "これらの魚を食べると私たちの体にプラスチックが入ります"),
            
            # Deforestation
            (["Forests", "are", "disappearing", "at", "an", "alarming", "rate"], 
             "森林は驚くべき速度で消えています"),
            (["Every", "minute", "an", "area", "of", "forest", "the", "size", "of", "forty", "football", "fields", "is", "cut", "down"], 
             "毎分、40個のサッカー場の大きさの森林地域が切り倒されています"),
            (["People", "cut", "down", "trees", "to", "make", "space", "for", "farms", "and", "cities"], 
             "人々は農場や都市のためのスペースを作るために木を切り倒します"),
            (["They", "also", "use", "wood", "for", "building", "and", "making", "paper"], 
             "彼らはまた建築や紙を作るために木材を使います"),
            (["But", "forests", "are", "the", "lungs", "of", "our", "planet"], 
             "しかし森林は私たちの惑星の肺です"),
            (["Trees", "absorb", "carbon", "dioxide", "and", "produce", "oxygen"], 
             "木は二酸化炭素を吸収し酸素を生産します"),
            (["Without", "trees", "there", "would", "be", "less", "oxygen", "to", "breathe"], 
             "木がなければ吸う酸素が少なくなります"),
            (["Forests", "also", "provide", "homes", "for", "countless", "animals"], 
             "森林はまた無数の動物の家を提供します"),
            (["Monkeys", "birds", "insects", "and", "many", "other", "creatures", "live", "in", "trees"], 
             "サル、鳥、昆虫、その他多くの生き物が木に住んでいます"),
            (["When", "forests", "are", "destroyed", "these", "animals", "lose", "their", "homes"], 
             "森林が破壊されるとこれらの動物は家を失います"),
            (["Many", "species", "are", "becoming", "extinct", "because", "of", "deforestation"], 
             "多くの種が森林破壊のために絶滅しつつあります"),
            
            # Climate Change
            (["Climate", "change", "is", "perhaps", "the", "biggest", "environmental", "challenge"], 
             "気候変動はおそらく最大の環境課題です"),
            (["The", "Earth's", "temperature", "is", "rising"], 
             "地球の温度は上昇しています"),
            (["This", "is", "called", "global", "warming"], 
             "これは地球温暖化と呼ばれます"),
            (["Human", "activities", "are", "the", "main", "cause"], 
             "人間の活動が主な原因です"),
            (["When", "we", "burn", "coal", "oil", "and", "gas", "we", "release", "greenhouse", "gases"], 
             "石炭、石油、ガスを燃やすと温室効果ガスを放出します"),
            (["These", "gases", "trap", "heat", "in", "the", "atmosphere"], 
             "これらのガスは大気中に熱を閉じ込めます"),
            (["As", "a", "result", "the", "planet", "gets", "warmer"], 
             "その結果、惑星は温かくなります"),
            (["Even", "a", "small", "temperature", "increase", "can", "cause", "big", "problems"], 
             "わずかな温度上昇でも大きな問題を引き起こす可能性があります"),
            (["Ice", "at", "the", "North", "and", "South", "Poles", "is", "melting"], 
             "北極と南極の氷が溶けています"),
            (["This", "melting", "ice", "causes", "sea", "levels", "to", "rise"], 
             "この溶ける氷は海面を上昇させます"),
            (["Some", "islands", "and", "coastal", "cities", "may", "be", "underwater", "in", "the", "future"], 
             "一部の島や沿岸都市は将来水没する可能性があります"),
            (["Climate", "change", "also", "affects", "weather", "patterns"], 
             "気候変動はまた天候パターンに影響します"),
            (["We", "are", "seeing", "more", "extreme", "weather", "events"], 
             "私たちはより極端な気象現象を見ています"),
            (["Hurricanes", "floods", "and", "droughts", "are", "becoming", "more", "common"], 
             "ハリケーン、洪水、干ばつがより一般的になっています"),
            (["These", "disasters", "destroy", "homes", "and", "kill", "people"], 
             "これらの災害は家を破壊し人々を殺します"),
            
            # Solutions
            (["The", "good", "news", "is", "that", "we", "can", "help", "solve", "these", "problems"], 
             "良いニュースは私たちがこれらの問題を解決するのを助けることができるということです"),
            (["Every", "person", "can", "make", "a", "difference"], 
             "すべての人が違いを生むことができます"),
            (["We", "can", "start", "by", "reducing", "reusing", "and", "recycling"], 
             "私たちは削減、再利用、リサイクルから始めることができます"),
            (["Reduce", "means", "using", "less"], 
             "削減とはより少なく使うことを意味します"),
            (["We", "should", "buy", "only", "what", "we", "need"], 
             "必要なものだけを買うべきです"),
            (["We", "can", "turn", "off", "lights", "when", "leaving", "a", "room"], 
             "部屋を出るときに明かりを消すことができます"),
            (["We", "should", "take", "shorter", "showers", "to", "save", "water"], 
             "水を節約するためにより短いシャワーを浴びるべきです"),
            (["Reuse", "means", "using", "things", "more", "than", "once"], 
             "再利用とは物を一度以上使うことを意味します"),
            (["Instead", "of", "throwing", "away", "plastic", "bags", "we", "can", "use", "them", "again"], 
             "ビニール袋を捨てる代わりに再び使うことができます"),
            (["We", "can", "bring", "our", "own", "shopping", "bags", "to", "the", "store"], 
             "店に自分の買い物袋を持っていくことができます"),
            (["Old", "clothes", "can", "be", "given", "to", "someone", "else"], 
             "古い服は他の誰かに渡すことができます"),
            (["Recycle", "means", "turning", "old", "materials", "into", "new", "products"], 
             "リサイクルとは古い材料を新しい製品に変えることを意味します"),
            (["Paper", "plastic", "glass", "and", "metal", "can", "all", "be", "recycled"], 
             "紙、プラスチック、ガラス、金属はすべてリサイクルできます"),
            (["We", "should", "separate", "our", "trash", "and", "put", "recyclables", "in", "the", "right", "bins"], 
             "ごみを分別しリサイクル可能なものを正しい容器に入れるべきです"),
            
            # Transportation
            (["How", "we", "travel", "also", "affects", "the", "environment"], 
             "私たちがどのように移動するかも環境に影響します"),
            (["Cars", "produce", "a", "lot", "of", "pollution"], 
             "車は多くの汚染を生み出します"),
            (["Walking", "and", "cycling", "are", "much", "better", "for", "the", "planet"], 
             "歩くことと自転車に乗ることは惑星にとってずっと良いです"),
            (["They", "also", "keep", "us", "healthy", "and", "fit"], 
             "それらはまた私たちを健康で元気に保ちます"),
            (["If", "the", "distance", "is", "too", "far", "we", "can", "use", "public", "transportation"], 
             "距離が遠すぎる場合は公共交通機関を利用できます"),
            (["Buses", "and", "trains", "carry", "many", "people", "at", "once"], 
             "バスや電車は一度に多くの人を運びます"),
            (["This", "means", "less", "pollution", "per", "person"], 
             "これは一人当たりの汚染が少ないことを意味します"),
            (["Some", "people", "are", "buying", "electric", "cars"], 
             "電気自動車を買う人もいます"),
            (["These", "cars", "do", "not", "burn", "gasoline", "so", "they", "produce", "less", "pollution"], 
             "これらの車はガソリンを燃やさないので汚染が少ないです"),
            
            # Energy
            (["Saving", "energy", "is", "another", "important", "way", "to", "help"], 
             "エネルギーを節約することも助けるもう一つの重要な方法です"),
            (["Most", "of", "our", "electricity", "comes", "from", "burning", "coal", "and", "gas"], 
             "私たちの電気のほとんどは石炭とガスを燃やすことから来ます"),
            (["This", "releases", "greenhouse", "gases"], 
             "これは温室効果ガスを放出します"),
            (["If", "we", "use", "less", "electricity", "power", "plants", "burn", "less", "fuel"], 
             "より少ない電気を使えば発電所はより少ない燃料を燃やします"),
            (["We", "can", "turn", "off", "computers", "and", "TVs", "when", "not", "using", "them"], 
             "使っていないときはコンピューターやテレビを消すことができます"),
            (["We", "should", "unplug", "chargers", "when", "our", "devices", "are", "fully", "charged"], 
             "デバイスが完全に充電されたら充電器を抜くべきです"),
            (["Using", "energy-efficient", "light", "bulbs", "also", "helps"], 
             "省エネ電球を使うことも助けになります"),
            (["Solar", "panels", "and", "wind", "turbines", "provide", "clean", "energy"], 
             "ソーラーパネルと風力タービンはクリーンエネルギーを提供します"),
            (["More", "homes", "and", "buildings", "are", "using", "renewable", "energy"], 
             "より多くの家や建物が再生可能エネルギーを使っています"),
            
            # Planting Trees
            (["Planting", "trees", "is", "one", "of", "the", "best", "things", "we", "can", "do"], 
             "木を植えることは私たちができる最良のことの一つです"),
            (["Trees", "clean", "the", "air", "by", "absorbing", "carbon", "dioxide"], 
             "木は二酸化炭素を吸収することで空気をきれいにします"),
            (["They", "also", "provide", "shade", "and", "beauty"], 
             "それらはまた日陰と美しさを提供します"),
            (["Many", "schools", "and", "communities", "organize", "tree-planting", "events"], 
             "多くの学校やコミュニティが植樹イベントを開催します"),
            (["Young", "people", "can", "join", "these", "activities"], 
             "若者たちはこれらの活動に参加できます"),
            (["Even", "planting", "one", "tree", "makes", "a", "difference"], 
             "一本の木を植えるだけでも違いを生みます"),
            
            # Conclusion
            (["Protecting", "our", "environment", "is", "everyone's", "responsibility"], 
             "私たちの環境を守ることは全員の責任です"),
            (["We", "cannot", "wait", "for", "others", "to", "solve", "these", "problems"], 
             "他の人がこれらの問題を解決するのを待つことはできません"),
            (["Each", "of", "us", "must", "take", "action", "now"], 
             "私たち一人一人が今行動を起こさなければなりません"),
            (["Small", "changes", "in", "our", "daily", "lives", "can", "add", "up", "to", "big", "results"], 
             "私たちの日常生活の小さな変化が大きな結果につながることがあります"),
            (["When", "millions", "of", "people", "make", "small", "changes", "together"], 
             "何百万人もの人々が一緒に小さな変化を起こすとき"),
            (["The", "impact", "becomes", "enormous"], 
             "その影響は莫大になります"),
            (["We", "have", "only", "one", "Earth"], 
             "私たちには一つの地球しかありません"),
            (["We", "must", "take", "care", "of", "it", "for", "ourselves"], 
             "私たち自身のためにそれを大切にしなければなりません"),
            (["We", "must", "also", "protect", "it", "for", "future", "generations"], 
             "また将来の世代のためにそれを守らなければなりません"),
            (["Our", "children", "and", "grandchildren", "deserve", "a", "clean", "healthy", "planet"], 
             "私たちの子供や孫はきれいで健康な惑星を受け取る権利があります"),
            (["Together", "we", "can", "make", "a", "difference"], 
             "一緒に私たちは違いを生むことができます"),
            (["Let", "us", "start", "today"], 
             "今日から始めましょう"),
            
            # Additional detailed content
            (["The", "food", "we", "eat", "also", "affects", "the", "environment"], 
             "私たちが食べる食べ物も環境に影響します"),
            (["Meat", "production", "uses", "a", "lot", "of", "water", "and", "land"], 
             "肉の生産は多くの水と土地を使います"),
            (["It", "also", "produces", "greenhouse", "gases"], 
             "それはまた温室効果ガスを生み出します"),
            (["Eating", "more", "vegetables", "and", "less", "meat", "helps", "the", "planet"], 
             "より多くの野菜とより少ない肉を食べることは惑星を助けます"),
            (["Local", "food", "is", "better", "than", "imported", "food"], 
             "地元の食べ物は輸入食品より良いです"),
            (["Imported", "food", "travels", "long", "distances", "by", "plane", "or", "ship"], 
             "輸入食品は飛行機や船で長距離を移動します"),
            (["This", "transportation", "burns", "fuel", "and", "creates", "pollution"], 
             "この輸送は燃料を燃やし汚染を生み出します"),
            (["Buying", "food", "from", "local", "farmers", "reduces", "this", "pollution"], 
             "地元の農家から食べ物を買うことはこの汚染を減らします"),
            (["We", "should", "also", "avoid", "wasting", "food"], 
             "私たちはまた食べ物を無駄にすることを避けるべきです"),
            (["Millions", "of", "tons", "of", "food", "are", "thrown", "away", "every", "year"], 
             "毎年何百万トンもの食べ物が捨てられています"),
            (["This", "wasted", "food", "ends", "up", "in", "landfills"], 
             "この無駄になった食べ物は埋立地に行き着きます"),
            (["When", "food", "rots", "it", "produces", "methane", "gas"], 
             "食べ物が腐るとメタンガスを生成します"),
            (["Methane", "is", "a", "very", "powerful", "greenhouse", "gas"], 
             "メタンは非常に強力な温室効果ガスです"),
            (["We", "can", "plan", "our", "meals", "carefully", "to", "avoid", "waste"], 
             "無駄を避けるために食事を慎重に計画できます"),
            (["Leftovers", "can", "be", "saved", "and", "eaten", "the", "next", "day"], 
             "残り物は保存して翌日食べることができます"),
            
            (["Schools", "play", "an", "important", "role", "in", "environmental", "education"], 
             "学校は環境教育において重要な役割を果たします"),
            (["Students", "can", "learn", "about", "environmental", "issues", "in", "class"], 
             "生徒は授業で環境問題について学ぶことができます"),
            (["They", "can", "participate", "in", "recycling", "programs", "at", "school"], 
             "学校でリサイクルプログラムに参加できます"),
            (["Many", "schools", "have", "environmental", "clubs"], 
             "多くの学校には環境クラブがあります"),
            (["These", "clubs", "organize", "activities", "like", "beach", "cleanups"], 
             "これらのクラブはビーチの清掃などの活動を組織します"),
            (["Students", "can", "also", "start", "school", "gardens"], 
             "生徒はまた学校菜園を始めることができます"),
            (["Growing", "vegetables", "teaches", "students", "about", "nature"], 
             "野菜を育てることは生徒に自然について教えます"),
            (["It", "also", "provides", "fresh", "healthy", "food"], 
             "それはまた新鮮で健康的な食べ物を提供します"),
            
            (["Governments", "and", "businesses", "must", "also", "take", "responsibility"], 
             "政府と企業も責任を取らなければなりません"),
            (["Governments", "can", "make", "laws", "to", "protect", "the", "environment"], 
             "政府は環境を守るための法律を作ることができます"),
            (["They", "can", "set", "limits", "on", "pollution"], 
             "汚染に制限を設けることができます"),
            (["They", "can", "create", "protected", "areas", "where", "nature", "is", "safe"], 
             "自然が安全な保護区域を作ることができます"),
            (["Companies", "should", "use", "cleaner", "production", "methods"], 
             "企業はよりクリーンな生産方法を使うべきです"),
            (["They", "should", "reduce", "waste", "and", "recycle", "materials"], 
             "廃棄物を減らし材料をリサイクルすべきです"),
            (["Some", "companies", "are", "already", "leading", "the", "way"], 
             "一部の企業はすでに先頭に立っています"),
            (["They", "use", "renewable", "energy", "in", "their", "factories"], 
             "工場で再生可能エネルギーを使っています"),
            (["They", "make", "products", "that", "last", "longer"], 
             "より長持ちする製品を作ります"),
            (["They", "design", "products", "that", "can", "be", "easily", "recycled"], 
             "簡単にリサイクルできる製品を設計します"),
            
            (["International", "cooperation", "is", "essential"], 
             "国際協力は不可欠です"),
            (["Environmental", "problems", "do", "not", "stop", "at", "borders"], 
             "環境問題は国境で止まりません"),
            (["Pollution", "in", "one", "country", "can", "affect", "other", "countries"], 
             "ある国の汚染は他の国々に影響を与える可能性があります"),
            (["Countries", "must", "work", "together", "to", "solve", "these", "problems"], 
             "国々はこれらの問題を解決するために協力しなければなりません"),
            (["Many", "nations", "have", "signed", "agreements", "to", "reduce", "greenhouse", "gases"], 
             "多くの国が温室効果ガスを削減する協定に署名しました"),
            (["They", "share", "technology", "and", "knowledge"], 
             "技術と知識を共有しています"),
            (["They", "help", "poorer", "countries", "develop", "in", "sustainable", "ways"], 
             "貧しい国々が持続可能な方法で発展するのを助けます"),
            
            (["Young", "people", "are", "leading", "the", "fight", "for", "the", "environment"], 
             "若者たちは環境のための戦いを主導しています"),
            (["Around", "the", "world", "students", "are", "speaking", "out"], 
             "世界中で生徒たちが声を上げています"),
            (["They", "are", "demanding", "that", "leaders", "take", "action"], 
             "指導者たちに行動を起こすよう要求しています"),
            (["They", "understand", "that", "their", "future", "is", "at", "stake"], 
             "自分たちの未来が危機に瀕していることを理解しています"),
            (["Young", "activists", "have", "inspired", "millions", "of", "people"], 
             "若い活動家たちは何百万人もの人々を鼓舞しました"),
            (["They", "show", "us", "that", "one", "person", "can", "make", "a", "difference"], 
             "一人の人間が違いを生むことができることを示しています"),
            
            (["Technology", "can", "help", "us", "protect", "the", "environment"], 
             "技術は環境を守るのを助けることができます"),
            (["Scientists", "are", "developing", "new", "clean", "energy", "sources"], 
             "科学者たちは新しいクリーンエネルギー源を開発しています"),
            (["They", "are", "finding", "ways", "to", "remove", "carbon", "dioxide", "from", "the", "air"], 
             "空気から二酸化炭素を除去する方法を見つけています"),
            (["They", "are", "creating", "materials", "that", "break", "down", "naturally"], 
             "自然に分解する材料を作成しています"),
            (["New", "apps", "help", "people", "track", "their", "environmental", "impact"], 
             "新しいアプリは人々が環境への影響を追跡するのを助けます"),
            (["These", "tools", "show", "us", "how", "to", "live", "more", "sustainably"], 
             "これらのツールはより持続可能に生きる方法を示します"),
            
            (["The", "ocean", "needs", "our", "protection", "too"], 
             "海も私たちの保護を必要としています"),
            (["Oceans", "cover", "most", "of", "our", "planet"], 
             "海は私たちの惑星のほとんどを覆っています"),
            (["They", "produce", "much", "of", "the", "oxygen", "we", "breathe"], 
             "私たちが吸う酸素の多くを生産します"),
            (["They", "absorb", "carbon", "dioxide", "from", "the", "atmosphere"], 
             "大気から二酸化炭素を吸収します"),
            (["But", "oceans", "are", "in", "trouble"], 
             "しかし海は困難に直面しています"),
            (["Overfishing", "has", "reduced", "fish", "populations"], 
             "過剰漁業が魚の個体数を減らしました"),
            (["Pollution", "and", "plastic", "waste", "harm", "marine", "life"], 
             "汚染とプラスチックごみが海洋生物を傷つけます"),
            (["Rising", "temperatures", "are", "killing", "coral", "reefs"], 
             "上昇する温度がサンゴ礁を殺しています"),
            (["We", "must", "protect", "marine", "ecosystems"], 
             "海洋生態系を保護しなければなりません"),
            (["We", "can", "support", "sustainable", "fishing", "practices"], 
             "持続可能な漁業慣行を支援できます"),
            (["We", "can", "reduce", "our", "use", "of", "single-use", "plastics"], 
             "使い捨てプラスチックの使用を減らすことができます"),
            
            (["Nature", "provides", "us", "with", "so", "many", "benefits"], 
             "自然は私たちに非常に多くの恩恵を提供します"),
            (["Forests", "give", "us", "clean", "air", "and", "water"], 
             "森林は私たちにきれいな空気と水を与えます"),
            (["Wetlands", "filter", "pollution", "and", "prevent", "floods"], 
             "湿地は汚染を濾過し洪水を防ぎます"),
            (["Insects", "pollinate", "our", "crops"], 
             "昆虫は私たちの作物を受粉させます"),
            (["All", "living", "things", "are", "connected"], 
             "すべての生き物はつながっています"),
            (["When", "we", "harm", "nature", "we", "harm", "ourselves"], 
             "自然を傷つけると私たち自身を傷つけます"),
            (["When", "we", "protect", "nature", "we", "protect", "our", "own", "future"], 
             "自然を守ると私たち自身の未来を守ります"),
            
            (["Every", "action", "counts", "no", "matter", "how", "small"], 
             "どんなに小さくてもすべての行動が重要です"),
            (["Turning", "off", "a", "light", "matters"], 
             "明かりを消すことも重要です"),
            (["Using", "a", "reusable", "water", "bottle", "matters"], 
             "再利用可能な水筒を使うことも重要です"),
            (["Walking", "instead", "of", "driving", "matters"], 
             "運転する代わりに歩くことも重要です"),
            (["These", "small", "actions", "add", "up"], 
             "これらの小さな行動が積み重なります"),
            (["When", "we", "all", "do", "our", "part", "we", "create", "real", "change"], 
             "私たち全員が自分の役割を果たすと本当の変化を生み出します"),
            
            (["The", "time", "to", "act", "is", "now"], 
             "行動する時は今です"),
            (["We", "cannot", "afford", "to", "wait"], 
             "待つ余裕はありません"),
            (["Every", "year", "we", "delay", "the", "problems", "get", "worse"], 
             "遅れる毎年問題は悪化します"),
            (["But", "we", "still", "have", "time", "to", "make", "a", "difference"], 
             "しかしまだ違いを生む時間があります"),
            (["We", "still", "have", "hope"], 
             "まだ希望があります"),
            (["With", "determination", "and", "cooperation"], 
             "決意と協力があれば"),
            (["We", "can", "create", "a", "better", "world"], 
             "より良い世界を作ることができます"),
            (["A", "world", "where", "the", "air", "is", "clean"], 
             "空気がきれいな世界"),
            (["A", "world", "where", "the", "water", "is", "pure"], 
             "水が純粋な世界"),
            (["A", "world", "where", "forests", "thrive"], 
             "森林が繁栄する世界"),
            (["A", "world", "where", "all", "creatures", "can", "live", "in", "harmony"], 
             "すべての生き物が調和して生きることができる世界"),
            (["This", "is", "the", "world", "we", "must", "build"], 
             "これが私たちが築かなければならない世界です"),
            (["This", "is", "our", "responsibility"], 
             "これが私たちの責任です"),
            (["This", "is", "our", "mission"], 
             "これが私たちの使命です"),
            (["Let", "us", "begin", "today", "and", "never", "give", "up"], 
             "今日始めて決してあきらめないようにしましょう"),
        ]
        
        for words, meaning in content:
            phrases.append(self.create_phrase(f"phrase-{pid}", words, meaning))
            pid += 1
        
        word_count = sum(len(p['words']) for p in phrases)
        
        return {
            "id": "intermediate-1",
            "title": "Protecting Our Environment",
            "level": "中級",
            "theme": "環境保護",
            "targetWordCount": 1500,
            "actualWordCount": word_count,
            "phrases": phrases
        }
    
    def save_passage(self, passage):
        """パッセージをJSONファイルに保存"""
        output_path = self.output_dir / f"{passage['id']}.json"
        with open(output_path, 'w', encoding='utf-8') as f:
            json.dump(passage, f, ensure_ascii=False, indent=2)
        print(f"✓ {passage['id']}: {passage['actualWordCount']}語 - {output_path}")
    
    def generate_intermediate_2(self):
        """中級パッセージ2: Science and Technology (2,000語目標)"""
        phrases = []
        pid = 1
        
        content = [
            # Introduction
            (["Science", "and", "technology", "have", "changed", "our", "world", "dramatically"], 
             "科学と技術は私たちの世界を劇的に変えました"),
            (["In", "the", "past", "hundred", "years", "we", "have", "seen", "amazing", "progress"], 
             "過去百年で私たちは驚くべき進歩を見てきました"),
            (["Things", "that", "seemed", "impossible", "are", "now", "part", "of", "everyday", "life"], 
             "不可能に見えたことが今では日常生活の一部です"),
            (["Technology", "affects", "almost", "every", "aspect", "of", "modern", "living"], 
             "技術は現代生活のほぼすべての側面に影響します"),
            (["Let", "us", "explore", "how", "science", "and", "technology", "shape", "our", "lives"], 
             "科学と技術がどのように私たちの生活を形作るか探りましょう"),
            
            # Communication Technology
            (["Communication", "technology", "has", "transformed", "how", "we", "connect"], 
             "通信技術は私たちのつながり方を変えました"),
            (["Just", "thirty", "years", "ago", "most", "people", "had", "no", "mobile", "phones"], 
             "わずか三十年前はほとんどの人が携帯電話を持っていませんでした"),
            (["Today", "billions", "of", "people", "carry", "smartphones"], 
             "今日何十億もの人々がスマートフォンを持ち歩いています"),
            (["We", "can", "instantly", "message", "friends", "across", "the", "world"], 
             "世界中の友達に即座にメッセージを送ることができます"),
            (["We", "can", "make", "video", "calls", "to", "see", "and", "hear", "loved", "ones"], 
             "ビデオ通話で愛する人々を見て話すことができます"),
            (["Social", "media", "platforms", "let", "us", "share", "our", "lives", "with", "others"], 
             "ソーシャルメディアプラットフォームで生活を他者と共有できます"),
            (["We", "can", "post", "photos", "write", "updates", "and", "comment", "on", "news"], 
             "写真を投稿し近況を書きニュースにコメントできます"),
            (["The", "internet", "connects", "people", "like", "never", "before"], 
             "インターネットは以前にない方法で人々をつなぎます"),
            (["Information", "travels", "around", "the", "globe", "in", "seconds"], 
             "情報は数秒で世界中を移動します"),
            (["However", "this", "technology", "also", "brings", "challenges"], 
             "しかしこの技術は課題ももたらします"),
            (["Some", "people", "spend", "too", "much", "time", "on", "their", "devices"], 
             "一部の人々はデバイスに時間をかけすぎます"),
            (["They", "neglect", "face", "to", "face", "relationships"], 
             "対面の関係を軽視します"),
            (["Cyberbullying", "has", "become", "a", "serious", "problem"], 
             "ネットいじめが深刻な問題になっています"),
            (["False", "information", "spreads", "quickly", "online"], 
             "虚偽の情報がオンラインで素早く広がります"),
            (["We", "must", "learn", "to", "use", "technology", "wisely", "and", "responsibly"], 
             "技術を賢く責任を持って使うことを学ばなければなりません"),
            
            # Computer Technology
            (["Computers", "have", "become", "essential", "tools", "in", "modern", "society"], 
             "コンピュータは現代社会で不可欠な道具になりました"),
            (["Early", "computers", "filled", "entire", "rooms"], 
             "初期のコンピュータは部屋全体を占めました"),
            (["Now", "we", "carry", "more", "computing", "power", "in", "our", "pockets"], 
             "今ではポケットにもっと多くのコンピューティングパワーを持ち運びます"),
            (["Computers", "help", "us", "work", "more", "efficiently"], 
             "コンピュータは私たちがより効率的に働くのを助けます"),
            (["Word", "processors", "make", "writing", "and", "editing", "easy"], 
             "ワードプロセッサは執筆と編集を簡単にします"),
            (["Spreadsheets", "help", "us", "organize", "data", "and", "calculate", "numbers"], 
             "スプレッドシートはデータを整理し数字を計算するのを助けます"),
            (["Presentation", "software", "helps", "us", "share", "ideas", "visually"], 
             "プレゼンテーションソフトウェアは視覚的にアイデアを共有するのを助けます"),
            (["Schools", "use", "computers", "for", "teaching", "and", "learning"], 
             "学校は教育と学習にコンピュータを使います"),
            (["Students", "can", "research", "topics", "online"], 
             "生徒はオンラインでトピックを調査できます"),
            (["They", "can", "watch", "educational", "videos"], 
             "教育ビデオを見ることができます"),
            (["They", "can", "take", "interactive", "quizzes"], 
             "インタラクティブなクイズを受けることができます"),
            (["Digital", "learning", "makes", "education", "more", "engaging"], 
             "デジタル学習は教育をより魅力的にします"),
            
            # Medical Technology
            (["Medical", "technology", "has", "saved", "countless", "lives"], 
             "医療技術は数え切れないほどの命を救いました"),
            (["Doctors", "can", "now", "diagnose", "diseases", "more", "accurately"], 
             "医師は今より正確に病気を診断できます"),
            (["X", "rays", "let", "doctors", "see", "inside", "the", "body"], 
             "X線は医師が体内を見ることを可能にします"),
            (["MRI", "and", "CT", "scans", "create", "detailed", "images", "of", "organs"], 
             "MRIとCTスキャンは臓器の詳細な画像を作ります"),
            (["These", "tools", "help", "detect", "cancer", "and", "other", "serious", "conditions", "early"], 
             "これらの道具はがんや他の深刻な状態を早期に検出するのを助けます"),
            (["Surgery", "has", "become", "safer", "and", "less", "invasive"], 
             "手術はより安全で侵襲性が低くなりました"),
            (["Surgeons", "can", "use", "tiny", "cameras", "and", "instruments"], 
             "外科医は小さなカメラと器具を使えます"),
            (["Patients", "recover", "faster", "with", "less", "pain"], 
             "患者はより少ない痛みでより速く回復します"),
            (["Vaccines", "have", "eliminated", "many", "deadly", "diseases"], 
             "ワクチンは多くの致命的な病気を根絶しました"),
            (["Antibiotics", "cure", "bacterial", "infections"], 
             "抗生物質は細菌感染症を治します"),
            (["Artificial", "organs", "and", "prosthetics", "improve", "quality", "of", "life"], 
             "人工臓器と義肢が生活の質を改善します"),
            (["People", "who", "lose", "limbs", "can", "use", "advanced", "prosthetic", "devices"], 
             "手足を失った人々は高度な義肢装置を使えます"),
            (["Some", "prosthetics", "can", "even", "be", "controlled", "by", "thoughts"], 
             "一部の義肢は思考で制御することさえできます"),
            (["Medical", "research", "continues", "to", "find", "new", "treatments"], 
             "医学研究は新しい治療法を見つけ続けています"),
            (["Scientists", "are", "studying", "genes", "to", "understand", "diseases", "better"], 
             "科学者は病気をよりよく理解するために遺伝子を研究しています"),
            (["Gene", "therapy", "may", "cure", "genetic", "disorders", "in", "the", "future"], 
             "遺伝子治療は将来遺伝性疾患を治すかもしれません"),
            
            # Space Exploration
            (["Space", "technology", "has", "expanded", "our", "understanding", "of", "the", "universe"], 
             "宇宙技術は宇宙に対する私たちの理解を拡大しました"),
            (["In", "1969", "humans", "first", "walked", "on", "the", "moon"], 
             "1969年に人類は初めて月を歩きました"),
            (["This", "was", "one", "of", "humanity", "greatest", "achievements"], 
             "これは人類の最大の達成の一つでした"),
            (["Today", "space", "agencies", "send", "robots", "to", "explore", "distant", "planets"], 
             "今日宇宙機関はロボットを遠い惑星を探検するために送ります"),
            (["Rovers", "have", "explored", "the", "surface", "of", "Mars"], 
             "ローバーは火星の表面を探検しました"),
            (["They", "send", "back", "photos", "and", "data", "about", "the", "red", "planet"], 
             "赤い惑星についての写真とデータを送り返します"),
            (["Telescopes", "in", "space", "observe", "distant", "stars", "and", "galaxies"], 
             "宇宙の望遠鏡は遠い星と銀河を観測します"),
            (["They", "help", "us", "learn", "about", "the", "origin", "of", "the", "universe"], 
             "宇宙の起源について学ぶのを助けます"),
            (["The", "International", "Space", "Station", "orbits", "Earth"], 
             "国際宇宙ステーションは地球を周回します"),
            (["Astronauts", "from", "different", "countries", "work", "together", "there"], 
             "異なる国の宇宙飛行士がそこで一緒に働きます"),
            (["They", "conduct", "experiments", "in", "zero", "gravity"], 
             "無重力で実験を行います"),
            (["This", "research", "benefits", "life", "on", "Earth"], 
             "この研究は地球上の生活に恩恵をもたらします"),
            (["Private", "companies", "are", "now", "developing", "space", "tourism"], 
             "民間企業が今宇宙旅行を開発しています"),
            (["In", "the", "future", "ordinary", "people", "may", "travel", "to", "space"], 
             "将来普通の人々が宇宙に旅行するかもしれません"),
            (["Scientists", "are", "planning", "missions", "to", "Mars"], 
             "科学者は火星へのミッションを計画しています"),
            (["Humans", "may", "one", "day", "establish", "colonies", "on", "other", "planets"], 
             "人類はいつか他の惑星にコロニーを設立するかもしれません"),
            
            # Transportation Technology
            (["Transportation", "technology", "has", "made", "travel", "faster", "and", "easier"], 
             "輸送技術は旅行をより速くより簡単にしました"),
            (["Cars", "allow", "us", "to", "travel", "long", "distances", "comfortably"], 
             "車は私たちが長距離を快適に移動することを可能にします"),
            (["Modern", "cars", "have", "many", "safety", "features"], 
             "現代の車は多くの安全機能を持っています"),
            (["Airbags", "protect", "passengers", "in", "accidents"], 
             "エアバッグは事故で乗客を保護します"),
            (["Anti", "lock", "brakes", "prevent", "skidding"], 
             "アンチロックブレーキは滑走を防ぎます"),
            (["Some", "cars", "can", "now", "drive", "themselves"], 
             "一部の車は今自分で運転できます"),
            (["Self", "driving", "cars", "use", "sensors", "and", "cameras"], 
             "自動運転車はセンサーとカメラを使います"),
            (["They", "can", "navigate", "roads", "and", "avoid", "obstacles"], 
             "道路をナビゲートし障害物を避けることができます"),
            (["This", "technology", "could", "reduce", "traffic", "accidents"], 
             "この技術は交通事故を減らすことができるかもしれません"),
            (["Electric", "cars", "are", "becoming", "more", "popular"], 
             "電気自動車がより人気になっています"),
            (["They", "produce", "no", "exhaust", "emissions"], 
             "排気ガスを出しません"),
            (["They", "are", "better", "for", "the", "environment"], 
             "環境により良いです"),
            (["High", "speed", "trains", "connect", "major", "cities"], 
             "高速列車は主要都市を結びます"),
            (["Passengers", "can", "travel", "hundreds", "of", "kilometers", "in", "just", "hours"], 
             "乗客はわずか数時間で数百キロメートル移動できます"),
            (["Trains", "are", "more", "energy", "efficient", "than", "cars", "or", "planes"], 
             "列車は車や飛行機よりエネルギー効率が良いです"),
            (["Airplanes", "have", "made", "international", "travel", "routine"], 
             "飛行機は国際旅行を日常的にしました"),
            (["We", "can", "fly", "to", "the", "other", "side", "of", "the", "world", "in", "a", "day"], 
             "一日で世界の反対側に飛ぶことができます"),
            (["This", "connects", "cultures", "and", "promotes", "understanding"], 
             "これは文化をつなぎ理解を促進します"),
            
            # Energy Technology
            (["Energy", "technology", "powers", "our", "modern", "world"], 
             "エネルギー技術は私たちの現代世界を動かします"),
            (["For", "many", "years", "we", "relied", "on", "fossil", "fuels"], 
             "長年私たちは化石燃料に頼ってきました"),
            (["Coal", "oil", "and", "natural", "gas", "provided", "most", "of", "our", "energy"], 
             "石炭石油天然ガスがエネルギーのほとんどを提供しました"),
            (["But", "these", "fuels", "cause", "pollution", "and", "climate", "change"], 
             "しかしこれらの燃料は汚染と気候変動を引き起こします"),
            (["Now", "we", "are", "developing", "cleaner", "energy", "sources"], 
             "今よりクリーンなエネルギー源を開発しています"),
            (["Solar", "panels", "convert", "sunlight", "into", "electricity"], 
             "ソーラーパネルは太陽光を電気に変換します"),
            (["They", "can", "be", "installed", "on", "rooftops", "or", "in", "large", "solar", "farms"], 
             "屋根や大規模なソーラーファームに設置できます"),
            (["Wind", "turbines", "capture", "energy", "from", "the", "wind"], 
             "風力タービンは風からエネルギーを捕らえます"),
            (["Large", "wind", "farms", "can", "power", "thousands", "of", "homes"], 
             "大規模な風力発電所は何千もの家に電力を供給できます"),
            (["Hydroelectric", "dams", "use", "water", "flow", "to", "generate", "electricity"], 
             "水力発電ダムは水の流れを使って電気を生成します"),
            (["These", "renewable", "sources", "are", "unlimited", "and", "clean"], 
             "これらの再生可能な源は無限でクリーンです"),
            (["Battery", "technology", "is", "also", "improving"], 
             "バッテリー技術も改善しています"),
            (["Better", "batteries", "store", "more", "energy", "for", "longer"], 
             "より良いバッテリーはより多くのエネルギーをより長く蓄えます"),
            (["This", "makes", "electric", "vehicles", "more", "practical"], 
             "これは電気自動車をより実用的にします"),
            (["It", "also", "helps", "store", "solar", "and", "wind", "energy"], 
             "また太陽光と風力エネルギーを蓄えるのに役立ちます"),
            (["Nuclear", "power", "is", "another", "energy", "source"], 
             "原子力はもう一つのエネルギー源です"),
            (["Nuclear", "plants", "produce", "large", "amounts", "of", "electricity"], 
             "原子力発電所は大量の電力を生産します"),
            (["They", "do", "not", "emit", "greenhouse", "gases"], 
             "温室効果ガスを排出しません"),
            (["However", "nuclear", "waste", "is", "dangerous", "and", "difficult", "to", "store"], 
             "しかし核廃棄物は危険で保管が困難です"),
            (["Accidents", "at", "nuclear", "plants", "can", "be", "catastrophic"], 
             "原子力発電所での事故は破滅的になる可能性があります"),
            (["Scientists", "continue", "to", "debate", "the", "future", "of", "nuclear", "energy"], 
             "科学者は原子力エネルギーの未来について議論し続けています"),
            
            # Internet and Information
            (["The", "internet", "has", "revolutionized", "how", "we", "access", "information"], 
             "インターネットは情報へのアクセス方法を革命化しました"),
            (["Before", "the", "internet", "people", "relied", "on", "books", "and", "libraries"], 
             "インターネット以前は人々は本と図書館に頼っていました"),
            (["Finding", "information", "could", "take", "hours", "or", "days"], 
             "情報を見つけるのに何時間も何日もかかることがありました"),
            (["Now", "we", "can", "search", "for", "anything", "and", "get", "results", "instantly"], 
             "今では何でも検索して即座に結果を得ることができます"),
            (["Search", "engines", "organize", "billions", "of", "web", "pages"], 
             "検索エンジンは何十億ものウェブページを整理します"),
            (["They", "help", "us", "find", "exactly", "what", "we", "need"], 
             "必要なものを正確に見つけるのを助けます"),
            (["Online", "encyclopedias", "contain", "vast", "amounts", "of", "knowledge"], 
             "オンライン百科事典は膨大な量の知識を含んでいます"),
            (["Anyone", "can", "contribute", "and", "edit", "articles"], 
             "誰でも記事を投稿し編集できます"),
            (["This", "democratizes", "information"], 
             "これは情報を民主化します"),
            (["Educational", "videos", "teach", "us", "everything", "from", "cooking", "to", "calculus"], 
             "教育ビデオは料理から微積分まであらゆることを教えます"),
            (["Online", "courses", "let", "us", "learn", "from", "top", "universities"], 
             "オンラインコースはトップ大学から学ぶことを可能にします"),
            (["Many", "of", "these", "courses", "are", "free"], 
             "これらのコースの多くは無料です"),
            (["This", "makes", "education", "accessible", "to", "everyone"], 
             "これは教育を誰にでもアクセス可能にします"),
            
            # Robotics and Automation
            (["Robots", "are", "increasingly", "common", "in", "our", "world"], 
             "ロボットは私たちの世界でますます一般的になっています"),
            (["Factories", "use", "robots", "to", "assemble", "products"], 
             "工場はロボットを使って製品を組み立てます"),
            (["These", "robots", "can", "work", "24", "hours", "a", "day", "without", "tiring"], 
             "これらのロボットは疲れることなく一日24時間働くことができます"),
            (["They", "perform", "repetitive", "tasks", "with", "perfect", "precision"], 
             "完璧な精度で反復作業を実行します"),
            (["This", "increases", "efficiency", "and", "reduces", "costs"], 
             "これは効率を高めコストを削減します"),
            (["Robots", "also", "work", "in", "dangerous", "environments"], 
             "ロボットは危険な環境でも働きます"),
            (["They", "can", "explore", "deep", "oceans", "where", "pressure", "would", "crush", "humans"], 
             "圧力が人間を押しつぶすような深海を探検できます"),
            (["They", "can", "enter", "buildings", "on", "fire", "to", "search", "for", "survivors"], 
             "生存者を探すために火事の建物に入ることができます"),
            (["They", "can", "handle", "toxic", "materials", "safely"], 
             "有毒物質を安全に扱うことができます"),
            (["Some", "robots", "help", "care", "for", "elderly", "people"], 
             "一部のロボットは高齢者の世話を助けます"),
            (["They", "can", "remind", "patients", "to", "take", "medicine"], 
             "患者に薬を飲むように思い出させることができます"),
            (["They", "can", "help", "with", "daily", "tasks", "like", "cleaning"], 
             "掃除のような日常的な仕事を助けることができます"),
            (["They", "provide", "companionship", "to", "lonely", "individuals"], 
             "孤独な個人に交わりを提供します"),
            
            # 3D Printing
            (["3D", "printing", "is", "an", "exciting", "new", "technology"], 
             "3Dプリンティングはわくわくする新しい技術です"),
            (["Traditional", "manufacturing", "cuts", "or", "shapes", "materials"], 
             "従来の製造は材料を切ったり形を作ったりします"),
            (["3D", "printers", "build", "objects", "layer", "by", "layer"], 
             "3Dプリンターは層ごとに物体を作ります"),
            (["They", "can", "create", "complex", "shapes", "impossible", "to", "make", "otherwise"], 
             "他の方法では不可能な複雑な形を作ることができます"),
            (["Designers", "use", "3D", "printers", "to", "test", "prototypes", "quickly"], 
             "デザイナーは3Dプリンターを使ってプロトタイプを素早くテストします"),
            (["Doctors", "can", "print", "customized", "prosthetics", "for", "patients"], 
             "医師は患者のためにカスタマイズされた義肢を印刷できます"),
            (["They", "can", "even", "print", "human", "tissue", "for", "research"], 
             "研究のために人間の組織さえ印刷できます"),
            (["In", "the", "future", "we", "may", "print", "entire", "organs", "for", "transplants"], 
             "将来移植のために臓器全体を印刷するかもしれません"),
            (["Some", "companies", "are", "printing", "houses"], 
             "一部の企業は家を印刷しています"),
            (["This", "could", "provide", "affordable", "housing", "quickly"], 
             "これは手頃な価格の住宅を素早く提供できるかもしれません"),
            
            # Biotechnology
            (["Biotechnology", "combines", "biology", "and", "technology"], 
             "バイオテクノロジーは生物学と技術を組み合わせます"),
            (["Scientists", "can", "now", "edit", "genes", "with", "precision"], 
             "科学者は今遺伝子を精密に編集できます"),
            (["This", "technology", "is", "called", "CRISPR"], 
             "この技術はCRISPRと呼ばれます"),
            (["It", "allows", "us", "to", "correct", "genetic", "defects"], 
             "遺伝的欠陥を修正することを可能にします"),
            (["It", "may", "cure", "diseases", "like", "sickle", "cell", "anemia"], 
             "鎌状赤血球貧血のような病気を治すかもしれません"),
            (["However", "gene", "editing", "raises", "ethical", "questions"], 
             "しかし遺伝子編集は倫理的な問題を提起します"),
            (["Should", "we", "edit", "human", "embryos"], 
             "人間の胚を編集すべきでしょうか"),
            (["Could", "this", "technology", "be", "misused"], 
             "この技術は誤用される可能性がありますか"),
            (["Society", "must", "carefully", "consider", "these", "questions"], 
             "社会はこれらの質問を慎重に考えなければなりません"),
            (["Biotechnology", "also", "helps", "agriculture"], 
             "バイオテクノロジーは農業も助けます"),
            (["Scientists", "develop", "crops", "that", "resist", "pests", "and", "diseases"], 
             "科学者は害虫や病気に抵抗する作物を開発します"),
            (["They", "create", "plants", "that", "grow", "in", "harsh", "climates"], 
             "厳しい気候で育つ植物を作ります"),
            (["These", "crops", "can", "help", "feed", "the", "growing", "world", "population"], 
             "これらの作物は増加する世界人口を養うのを助けることができます"),
            
            # Nanotechnology
            (["Nanotechnology", "works", "at", "the", "scale", "of", "atoms", "and", "molecules"], 
             "ナノテクノロジーは原子と分子のスケールで機能します"),
            (["Scientists", "build", "tiny", "machines", "smaller", "than", "a", "human", "cell"], 
             "科学者は人間の細胞より小さな極小の機械を作ります"),
            (["These", "nanomachines", "have", "many", "potential", "uses"], 
             "これらのナノマシンは多くの潜在的な用途があります"),
            (["They", "could", "deliver", "medicine", "directly", "to", "diseased", "cells"], 
             "病気の細胞に直接薬を届けることができるかもしれません"),
            (["They", "could", "repair", "damage", "inside", "the", "body"], 
             "体内の損傷を修復できるかもしれません"),
            (["Nanomaterials", "are", "stronger", "and", "lighter", "than", "traditional", "materials"], 
             "ナノ材料は従来の材料より強く軽いです"),
            (["They", "are", "used", "in", "electronics", "clothing", "and", "construction"], 
             "電子機器衣類建設に使われています"),
            (["Some", "fabrics", "with", "nanomaterials", "never", "get", "dirty"], 
             "ナノ材料を含む一部の布は決して汚れません"),
            (["Water", "and", "stains", "simply", "roll", "off"], 
             "水と汚れは単に転がり落ちます"),
            
            # Future Technology
            (["The", "future", "of", "technology", "is", "exciting", "and", "uncertain"], 
             "技術の未来はわくわくしていて不確実です"),
            (["Artificial", "intelligence", "is", "rapidly", "advancing"], 
             "人工知能は急速に進歩しています"),
            (["AI", "systems", "can", "now", "beat", "humans", "at", "complex", "games"], 
             "AIシステムは今複雑なゲームで人間に勝つことができます"),
            (["They", "can", "recognize", "faces", "and", "understand", "speech"], 
             "顔を認識し音声を理解できます"),
            (["They", "can", "translate", "languages", "instantly"], 
             "言語を即座に翻訳できます"),
            (["AI", "may", "transform", "many", "industries"], 
             "AIは多くの産業を変革するかもしれません"),
            (["Robots", "may", "do", "many", "jobs", "currently", "done", "by", "humans"], 
             "ロボットは現在人間が行う多くの仕事をするかもしれません"),
            (["This", "could", "free", "people", "to", "do", "more", "creative", "work"], 
             "これは人々がより創造的な仕事をすることを可能にするかもしれません"),
            (["But", "it", "also", "raises", "concerns", "about", "employment"], 
             "しかし雇用についての懸念も提起します"),
            (["Virtual", "reality", "creates", "immersive", "digital", "experiences"], 
             "バーチャルリアリティは没入型のデジタル体験を作り出します"),
            (["Users", "can", "feel", "like", "they", "are", "in", "another", "world"], 
             "ユーザーは別の世界にいるように感じることができます"),
            (["This", "technology", "has", "applications", "in", "education", "and", "training"], 
             "この技術は教育と訓練に応用があります"),
            (["Surgeons", "can", "practice", "operations", "in", "virtual", "reality"], 
             "外科医はバーチャルリアリティで手術を練習できます"),
            (["Students", "can", "explore", "historical", "sites", "virtually"], 
             "生徒は歴史的な場所を仮想的に探検できます"),
            (["Quantum", "computing", "is", "another", "frontier"], 
             "量子コンピューティングはもう一つのフロンティアです"),
            (["Quantum", "computers", "use", "principles", "of", "quantum", "physics"], 
             "量子コンピュータは量子物理学の原理を使います"),
            (["They", "could", "solve", "problems", "impossible", "for", "regular", "computers"], 
             "通常のコンピュータには不可能な問題を解決できるかもしれません"),
            (["They", "might", "help", "discover", "new", "medicines"], 
             "新しい薬を発見するのを助けるかもしれません"),
            (["They", "might", "break", "current", "encryption", "methods"], 
             "現在の暗号化方法を破るかもしれません"),
            (["This", "raises", "both", "opportunities", "and", "security", "concerns"], 
             "これは機会と安全保障上の懸念の両方を提起します"),
            
            # Technology in Daily Life
            (["Technology", "has", "become", "deeply", "integrated", "into", "daily", "life"], 
             "技術は日常生活に深く統合されています"),
            (["Smart", "homes", "use", "technology", "to", "increase", "comfort", "and", "efficiency"], 
             "スマートホームは快適さと効率を高めるために技術を使います"),
            (["We", "can", "control", "lights", "temperature", "and", "security", "from", "our", "phones"], 
             "電話から照明温度セキュリティを制御できます"),
            (["Voice", "assistants", "answer", "questions", "and", "control", "devices"], 
             "音声アシスタントは質問に答えデバイスを制御します"),
            (["We", "can", "ask", "them", "about", "the", "weather", "news", "or", "recipes"], 
             "天気ニュースレシピについて尋ねることができます"),
            (["Streaming", "services", "have", "changed", "how", "we", "watch", "entertainment"], 
             "ストリーミングサービスはエンターテインメントの視聴方法を変えました"),
            (["We", "can", "watch", "any", "show", "or", "movie", "whenever", "we", "want"], 
             "いつでも好きな番組や映画を見ることができます"),
            (["We", "are", "no", "longer", "limited", "by", "broadcast", "schedules"], 
             "もはや放送スケジュールに制限されません"),
            (["Music", "streaming", "gives", "us", "access", "to", "millions", "of", "songs"], 
             "音楽ストリーミングは何百万もの曲へのアクセスを提供します"),
            (["We", "can", "discover", "new", "artists", "from", "around", "the", "world"], 
             "世界中の新しいアーティストを発見できます"),
            (["Digital", "payments", "make", "transactions", "easier"], 
             "デジタル決済は取引をより簡単にします"),
            (["We", "can", "pay", "for", "purchases", "with", "our", "phones"], 
             "電話で購入代金を支払うことができます"),
            (["We", "can", "send", "money", "to", "friends", "instantly"], 
             "友達に即座にお金を送ることができます"),
            (["Online", "shopping", "lets", "us", "buy", "products", "from", "anywhere"], 
             "オンラインショッピングはどこからでも製品を購入できます"),
            (["Items", "are", "delivered", "right", "to", "our", "door"], 
             "商品は玄関まで配達されます"),
            
            # Technology and Education
            (["Technology", "has", "transformed", "education"], 
             "技術は教育を変革しました"),
            (["Digital", "textbooks", "can", "be", "updated", "instantly"], 
             "デジタル教科書は即座に更新できます"),
            (["They", "include", "videos", "animations", "and", "interactive", "elements"], 
             "ビデオアニメーションインタラクティブ要素を含みます"),
            (["Students", "can", "learn", "at", "their", "own", "pace"], 
             "生徒は自分のペースで学ぶことができます"),
            (["They", "can", "review", "difficult", "material", "as", "many", "times", "as", "needed"], 
             "必要なだけ何度も難しい教材を復習できます"),
            (["Online", "collaboration", "tools", "let", "students", "work", "together", "remotely"], 
             "オンライン協力ツールは生徒が遠隔で一緒に働くことを可能にします"),
            (["They", "can", "share", "documents", "and", "edit", "them", "simultaneously"], 
             "文書を共有し同時に編集できます"),
            (["Virtual", "labs", "allow", "science", "experiments", "without", "expensive", "equipment"], 
             "仮想実験室は高価な装置なしで科学実験を可能にします"),
            (["Students", "can", "safely", "explore", "dangerous", "reactions"], 
             "生徒は危険な反応を安全に探索できます"),
            (["Educational", "apps", "make", "learning", "fun", "through", "games"], 
             "教育アプリはゲームを通して学習を楽しくします"),
            (["Children", "practice", "math", "or", "language", "skills", "while", "playing"], 
             "子供たちは遊びながら数学や言語スキルを練習します"),
            
            # Challenges and Responsibilities
            (["Despite", "all", "these", "benefits", "technology", "brings", "challenges"], 
             "これらすべての利点にもかかわらず技術は課題をもたらします"),
            (["Privacy", "is", "a", "major", "concern"], 
             "プライバシーは主要な懸念事項です"),
            (["Companies", "collect", "vast", "amounts", "of", "personal", "data"], 
             "企業は膨大な量の個人データを収集します"),
            (["This", "data", "can", "be", "sold", "stolen", "or", "misused"], 
             "このデータは販売盗難悪用される可能性があります"),
            (["We", "must", "protect", "our", "digital", "privacy"], 
             "デジタルプライバシーを保護しなければなりません"),
            (["Cybersecurity", "threats", "are", "increasing"], 
             "サイバーセキュリティの脅威が増加しています"),
            (["Hackers", "steal", "information", "and", "money"], 
             "ハッカーは情報とお金を盗みます"),
            (["They", "can", "disrupt", "essential", "services"], 
             "必要不可欠なサービスを混乱させることができます"),
            (["Strong", "security", "measures", "are", "essential"], 
             "強力なセキュリティ対策が不可欠です"),
            (["Digital", "addiction", "is", "another", "problem"], 
             "デジタル依存症はもう一つの問題です"),
            (["People", "especially", "young", "people", "spend", "excessive", "time", "online"], 
             "特に若者が過度の時間をオンラインで過ごします"),
            (["This", "can", "harm", "physical", "health", "and", "social", "relationships"], 
             "これは身体的健康と社会的関係を害する可能性があります"),
            (["We", "need", "balance", "between", "technology", "use", "and", "real", "life", "activities"], 
             "技術の使用と実生活の活動の間のバランスが必要です"),
            
            # Conclusion
            (["Science", "and", "technology", "will", "continue", "to", "evolve"], 
             "科学と技術は進化し続けるでしょう"),
            (["New", "discoveries", "will", "bring", "new", "possibilities"], 
             "新しい発見は新しい可能性をもたらすでしょう"),
            (["But", "with", "great", "power", "comes", "great", "responsibility"], 
             "しかし大きな力には大きな責任が伴います"),
            (["We", "must", "use", "technology", "to", "benefit", "all", "humanity"], 
             "全人類の利益のために技術を使わなければなりません"),
            (["We", "must", "ensure", "it", "does", "not", "harm", "our", "planet"], 
             "私たちの惑星を害しないようにしなければなりません"),
            (["We", "must", "consider", "ethical", "questions", "carefully"], 
             "倫理的な問題を慎重に考えなければなりません"),
            (["Technology", "should", "serve", "humanity", "not", "control", "it"], 
             "技術は人類に奉仕すべきでそれを支配すべきではありません"),
            (["Education", "is", "key", "to", "using", "technology", "wisely"], 
             "教育は技術を賢く使う鍵です"),
            (["We", "must", "teach", "young", "people", "digital", "literacy"], 
             "若者にデジタルリテラシーを教えなければなりません"),
            (["They", "need", "to", "understand", "both", "opportunities", "and", "risks"], 
             "機会とリスクの両方を理解する必要があります"),
            (["By", "using", "science", "and", "technology", "wisely"], 
             "科学と技術を賢く使うことによって"),
            (["We", "can", "create", "a", "better", "future", "for", "everyone"], 
             "すべての人のためにより良い未来を作ることができます"),
            (["A", "future", "of", "health", "prosperity", "and", "discovery"], 
             "健康繁栄発見の未来を"),
            (["A", "future", "where", "technology", "enhances", "human", "potential"], 
             "技術が人間の可能性を高める未来を"),
            (["A", "future", "where", "everyone", "benefits", "from", "progress"], 
             "誰もが進歩から恩恵を受ける未来を"),
            (["This", "is", "the", "promise", "of", "science", "and", "technology"], 
             "これが科学と技術の約束です"),
            (["This", "is", "our", "shared", "responsibility"], 
             "これが私たちの共有された責任です"),
            (["Let", "us", "embrace", "the", "future", "with", "wisdom", "and", "hope"], 
             "知恵と希望を持って未来を受け入れましょう"),
        ]
        
        for words, meaning in content:
            phrases.append(self.create_phrase(f"phrase-{pid}", words, meaning))
            pid += 1
        
        word_count = sum(len(p['words']) for p in phrases)
        
        return {
            "id": "intermediate-2",
            "title": "Science and Technology",
            "level": "中級",
            "theme": "科学と技術",
            "targetWordCount": 2000,
            "actualWordCount": word_count,
            "phrases": phrases
        }
    
    def generate_intermediate_3(self):
        """中級パッセージ3: Healthy Living (2,500語目標)"""
        phrases = []
        pid = 1
        
        content = [
            # Introduction
            (["Living", "a", "healthy", "life", "is", "one", "of", "the", "most", "important", "goals"], 
             "健康的な生活を送ることは最も重要な目標の一つです"),
            (["Good", "health", "allows", "us", "to", "enjoy", "life", "fully"], 
             "健康は人生を完全に楽しむことを可能にします"),
            (["It", "gives", "us", "energy", "to", "pursue", "our", "dreams"], 
             "夢を追求するエネルギーを与えます"),
            (["It", "helps", "us", "connect", "with", "family", "and", "friends"], 
             "家族や友人とつながるのを助けます"),
            (["Many", "factors", "contribute", "to", "a", "healthy", "lifestyle"], 
             "多くの要因が健康的なライフスタイルに貢献します"),
            (["These", "include", "nutrition", "exercise", "sleep", "and", "mental", "health"], 
             "これらには栄養運動睡眠精神的健康が含まれます"),
            (["Let", "us", "explore", "each", "of", "these", "important", "areas"], 
             "これらの重要な分野のそれぞれを探りましょう"),
            
            # Nutrition
            (["Nutrition", "is", "the", "foundation", "of", "good", "health"], 
             "栄養は健康の基盤です"),
            (["The", "food", "we", "eat", "becomes", "part", "of", "our", "body"], 
             "私たちが食べる食べ物は体の一部になります"),
            (["It", "provides", "energy", "for", "all", "our", "activities"], 
             "すべての活動のためのエネルギーを提供します"),
            (["It", "supplies", "materials", "for", "growth", "and", "repair"], 
             "成長と修復のための材料を供給します"),
            (["A", "balanced", "diet", "includes", "many", "different", "foods"], 
             "バランスの取れた食事は多くの異なる食べ物を含みます"),
            (["We", "need", "carbohydrates", "for", "energy"], 
             "エネルギーのために炭水化物が必要です"),
            (["Rice", "bread", "and", "pasta", "are", "good", "sources"], 
             "米パン麺類は良い供給源です"),
            (["We", "need", "protein", "to", "build", "muscles", "and", "cells"], 
             "筋肉と細胞を作るためにタンパク質が必要です"),
            (["Meat", "fish", "eggs", "and", "beans", "provide", "protein"], 
             "肉魚卵豆がタンパク質を提供します"),
            (["We", "need", "vitamins", "and", "minerals", "for", "many", "body", "functions"], 
             "多くの体の機能のためにビタミンとミネラルが必要です"),
            (["Fruits", "and", "vegetables", "are", "rich", "in", "these", "nutrients"], 
             "果物と野菜はこれらの栄養素が豊富です"),
            (["We", "should", "eat", "five", "servings", "of", "fruits", "and", "vegetables", "daily"], 
             "毎日五つの果物と野菜を食べるべきです"),
            (["Different", "colors", "provide", "different", "nutrients"], 
             "異なる色は異なる栄養素を提供します"),
            (["Orange", "vegetables", "like", "carrots", "contain", "vitamin", "A"], 
             "ニンジンのようなオレンジ色の野菜はビタミンAを含みます"),
            (["Green", "vegetables", "like", "spinach", "contain", "iron"], 
             "ほうれん草のような緑の野菜は鉄を含みます"),
            (["We", "also", "need", "healthy", "fats"], 
             "健康的な脂肪も必要です"),
            (["Nuts", "avocados", "and", "olive", "oil", "provide", "good", "fats"], 
             "ナッツアボカドオリーブオイルが良い脂肪を提供します"),
            (["These", "fats", "help", "our", "brain", "and", "heart"], 
             "これらの脂肪は脳と心臓を助けます"),
            (["Water", "is", "essential", "for", "life"], 
             "水は生命に不可欠です"),
            (["We", "should", "drink", "at", "least", "eight", "glasses", "daily"], 
             "毎日少なくとも八杯飲むべきです"),
            (["Water", "helps", "digestion", "and", "regulates", "body", "temperature"], 
             "水は消化を助け体温を調整します"),
            (["Some", "foods", "should", "be", "limited"], 
             "制限すべき食べ物もあります"),
            (["Too", "much", "sugar", "can", "lead", "to", "obesity", "and", "diabetes"], 
             "砂糖の取りすぎは肥満と糖尿病につながる可能性があります"),
            (["Too", "much", "salt", "can", "cause", "high", "blood", "pressure"], 
             "塩の取りすぎは高血圧を引き起こす可能性があります"),
            (["Processed", "foods", "often", "contain", "unhealthy", "ingredients"], 
             "加工食品はしばしば不健康な成分を含みます"),
            (["Fresh", "whole", "foods", "are", "always", "the", "best", "choice"], 
             "新鮮な自然食品は常に最良の選択です"),
            (["Fiber", "is", "an", "important", "part", "of", "a", "healthy", "diet"], 
             "繊維は健康的な食事の重要な部分です"),
            (["It", "aids", "digestion", "and", "prevents", "constipation"], 
             "消化を助け便秘を防ぎます"),
            (["Whole", "grains", "vegetables", "and", "fruits", "contain", "fiber"], 
             "全粒穀物野菜果物は繊維を含みます"),
            (["Choose", "brown", "rice", "over", "white", "rice"], 
             "白米より玄米を選びます"),
            (["Choose", "whole", "wheat", "bread", "over", "white", "bread"], 
             "白いパンより全粒粉パンを選びます"),
            (["Calcium", "is", "essential", "for", "strong", "bones", "and", "teeth"], 
             "カルシウムは強い骨と歯に不可欠です"),
            (["Dairy", "products", "like", "milk", "and", "cheese", "provide", "calcium"], 
             "牛乳やチーズのような乳製品はカルシウムを提供します"),
            (["Leafy", "greens", "and", "tofu", "also", "contain", "calcium"], 
             "葉物野菜と豆腐もカルシウムを含みます"),
            (["Young", "people", "need", "extra", "calcium", "for", "growing", "bones"], 
             "若者は成長する骨のために余分なカルシウムが必要です"),
            (["Iron", "carries", "oxygen", "in", "the", "blood"], 
             "鉄は血液中の酸素を運びます"),
            (["Red", "meat", "beans", "and", "dark", "leafy", "greens", "provide", "iron"], 
             "赤身肉豆濃い緑の葉物野菜は鉄を提供します"),
            (["Vitamin", "C", "helps", "the", "body", "absorb", "iron"], 
             "ビタミンCは体が鉄を吸収するのを助けます"),
            (["Eat", "citrus", "fruits", "with", "iron", "rich", "foods"], 
             "鉄が豊富な食べ物と一緒に柑橘類を食べます"),
            (["Portion", "control", "is", "important", "for", "maintaining", "healthy", "weight"], 
             "健康的な体重を維持するには量の管理が重要です"),
            (["Use", "smaller", "plates", "to", "naturally", "reduce", "portions"], 
             "自然に量を減らすために小さな皿を使います"),
            (["Eat", "slowly", "and", "stop", "when", "you", "feel", "80", "percent", "full"], 
             "ゆっくり食べて80パーセント満腹になったら止めます"),
            (["It", "takes", "time", "for", "your", "brain", "to", "register", "fullness"], 
             "脳が満腹を認識するには時間がかかります"),
            (["Eating", "too", "fast", "leads", "to", "overeating"], 
             "速く食べすぎると食べ過ぎにつながります"),
            (["Breakfast", "truly", "is", "the", "most", "important", "meal"], 
             "朝食は本当に最も重要な食事です"),
            (["It", "breaks", "the", "overnight", "fast"], 
             "一晩の断食を破ります"),
            (["It", "provides", "fuel", "for", "the", "morning"], 
             "朝のための燃料を提供します"),
            (["People", "who", "eat", "breakfast", "perform", "better", "at", "school", "and", "work"], 
             "朝食を食べる人は学校や職場でよりよく働きます"),
            (["They", "have", "better", "concentration", "and", "mood"], 
             "より良い集中力と気分を持っています"),
            
            # Exercise
            (["Regular", "exercise", "is", "crucial", "for", "maintaining", "health"], 
             "定期的な運動は健康維持に不可欠です"),
            (["Physical", "activity", "strengthens", "our", "muscles", "and", "bones"], 
             "身体活動は筋肉と骨を強化します"),
            (["It", "improves", "cardiovascular", "health"], 
             "心血管の健康を改善します"),
            (["It", "helps", "maintain", "a", "healthy", "weight"], 
             "健康的な体重を維持するのを助けます"),
            (["Exercise", "releases", "endorphins", "which", "make", "us", "feel", "happy"], 
             "運動は幸せを感じさせるエンドルフィンを放出します"),
            (["There", "are", "many", "types", "of", "exercise"], 
             "多くの種類の運動があります"),
            (["Aerobic", "exercise", "includes", "running", "swimming", "and", "cycling"], 
             "有酸素運動にはランニング水泳サイクリングが含まれます"),
            (["These", "activities", "increase", "heart", "rate", "and", "breathing"], 
             "これらの活動は心拍数と呼吸を増加させます"),
            (["They", "improve", "endurance", "and", "stamina"], 
             "持久力とスタミナを改善します"),
            (["Strength", "training", "builds", "muscle", "mass"], 
             "筋力トレーニングは筋肉量を増やします"),
            (["Lifting", "weights", "or", "doing", "push", "ups", "are", "examples"], 
             "重量挙げや腕立て伏せが例です"),
            (["Strong", "muscles", "support", "joints", "and", "prevent", "injury"], 
             "強い筋肉は関節を支え怪我を防ぎます"),
            (["Flexibility", "exercises", "like", "yoga", "improve", "range", "of", "motion"], 
             "ヨガのような柔軟性運動は可動域を改善します"),
            (["They", "reduce", "muscle", "tension", "and", "stress"], 
             "筋肉の緊張とストレスを減らします"),
            (["They", "help", "prevent", "falls", "especially", "in", "older", "people"], 
             "特に高齢者の転倒を防ぐのを助けます"),
            (["Experts", "recommend", "at", "least", "30", "minutes", "of", "exercise", "daily"], 
             "専門家は毎日少なくとも30分の運動を推奨します"),
            (["This", "does", "not", "have", "to", "be", "continuous"], 
             "これは連続している必要はありません"),
            (["Three", "ten", "minute", "sessions", "work", "just", "as", "well"], 
             "三回の十分間のセッションも同じくらい効果的です"),
            (["Even", "simple", "activities", "count"], 
             "簡単な活動でさえカウントされます"),
            (["Walking", "to", "school", "or", "work", "is", "good", "exercise"], 
             "学校や職場まで歩くことは良い運動です"),
            (["Taking", "stairs", "instead", "of", "elevators", "helps"], 
             "エレベーターの代わりに階段を使うことは役立ちます"),
            (["Playing", "active", "games", "with", "friends", "is", "fun", "and", "healthy"], 
             "友達と活発なゲームをすることは楽しく健康的です"),
            (["The", "key", "is", "to", "find", "activities", "you", "enjoy"], 
             "鍵は楽しめる活動を見つけることです"),
            (["When", "exercise", "is", "fun", "you", "will", "do", "it", "regularly"], 
             "運動が楽しいと定期的に行うでしょう"),
            (["Team", "sports", "combine", "exercise", "with", "social", "interaction"], 
             "チームスポーツは運動と社会的交流を組み合わせます"),
            (["Soccer", "basketball", "and", "volleyball", "are", "popular", "choices"], 
             "サッカーバスケットボールバレーボールは人気の選択肢です"),
            (["They", "teach", "teamwork", "and", "cooperation"], 
             "チームワークと協力を教えます"),
            (["They", "provide", "excellent", "cardiovascular", "exercise"], 
             "優れた心血管運動を提供します"),
            (["Individual", "sports", "like", "tennis", "or", "martial", "arts", "are", "also", "valuable"], 
             "テニスや武道のような個人スポーツも価値があります"),
            (["They", "build", "self", "discipline", "and", "confidence"], 
             "自己規律と自信を築きます"),
            (["Swimming", "is", "an", "excellent", "full", "body", "workout"], 
             "水泳は優れた全身運動です"),
            (["It", "is", "gentle", "on", "joints"], 
             "関節に優しいです"),
            (["It", "builds", "strength", "and", "endurance", "simultaneously"], 
             "強さと持久力を同時に築きます"),
            (["Dancing", "is", "a", "fun", "way", "to", "exercise"], 
             "ダンスは運動する楽しい方法です"),
            (["It", "improves", "coordination", "and", "balance"], 
             "協調性とバランスを改善します"),
            (["It", "can", "be", "done", "alone", "or", "with", "others"], 
             "一人でまたは他の人と一緒にできます"),
            (["Warming", "up", "before", "exercise", "prevents", "injury"], 
             "運動前のウォームアップは怪我を防ぎます"),
            (["Start", "with", "light", "activity", "to", "increase", "heart", "rate", "gradually"], 
             "心拍数を徐々に上げるために軽い活動で始めます"),
            (["Stretch", "major", "muscle", "groups"], 
             "主要な筋肉群をストレッチします"),
            (["Cooling", "down", "after", "exercise", "is", "equally", "important"], 
             "運動後のクールダウンも同様に重要です"),
            (["Gradually", "reduce", "intensity"], 
             "徐々に強度を下げます"),
            (["Stretch", "while", "muscles", "are", "still", "warm"], 
             "筋肉がまだ温かいうちにストレッチします"),
            (["This", "reduces", "soreness", "and", "improves", "flexibility"], 
             "これは痛みを減らし柔軟性を改善します"),
            (["Stay", "hydrated", "during", "exercise"], 
             "運動中は水分補給をします"),
            (["Drink", "water", "before", "during", "and", "after", "physical", "activity"], 
             "身体活動の前中後に水を飲みます"),
            (["Sports", "drinks", "are", "usually", "unnecessary", "for", "moderate", "exercise"], 
             "スポーツドリンクは通常適度な運動には不要です"),
            (["Plain", "water", "is", "best", "for", "most", "activities"], 
             "ほとんどの活動には普通の水が最適です"),
            
            # Sleep
            (["Sleep", "is", "often", "overlooked", "but", "extremely", "important"], 
             "睡眠はしばしば見過ごされますが非常に重要です"),
            (["During", "sleep", "our", "body", "repairs", "and", "regenerates"], 
             "睡眠中に体は修復し再生します"),
            (["Our", "brain", "processes", "memories", "and", "consolidates", "learning"], 
             "脳は記憶を処理し学習を統合します"),
            (["Lack", "of", "sleep", "affects", "concentration", "and", "mood"], 
             "睡眠不足は集中力と気分に影響します"),
            (["It", "weakens", "the", "immune", "system"], 
             "免疫システムを弱めます"),
            (["It", "increases", "risk", "of", "many", "diseases"], 
             "多くの病気のリスクを高めます"),
            (["Teenagers", "need", "about", "nine", "hours", "of", "sleep", "per", "night"], 
             "十代の若者は一晩に約九時間の睡眠が必要です"),
            (["Adults", "need", "seven", "to", "eight", "hours"], 
             "大人は七から八時間必要です"),
            (["Quality", "of", "sleep", "matters", "as", "much", "as", "quantity"], 
             "睡眠の質は量と同じくらい重要です"),
            (["A", "regular", "sleep", "schedule", "helps"], 
             "規則正しい睡眠スケジュールが役立ちます"),
            (["Going", "to", "bed", "and", "waking", "at", "the", "same", "time", "daily"], 
             "毎日同じ時間に寝て起きること"),
            (["This", "regulates", "your", "body", "internal", "clock"], 
             "これは体の内部時計を調整します"),
            (["The", "bedroom", "should", "be", "dark", "quiet", "and", "cool"], 
             "寝室は暗く静かで涼しくあるべきです"),
            (["Remove", "electronic", "devices", "from", "the", "bedroom"], 
             "寝室から電子機器を取り除きます"),
            (["Blue", "light", "from", "screens", "interferes", "with", "sleep"], 
             "画面からの青い光は睡眠を妨げます"),
            (["Avoid", "caffeine", "in", "the", "evening"], 
             "夕方のカフェインを避けます"),
            (["Caffeine", "can", "stay", "in", "your", "system", "for", "hours"], 
             "カフェインは何時間も体内に残る可能性があります"),
            (["A", "relaxing", "bedtime", "routine", "signals", "your", "body", "to", "sleep"], 
             "リラックスする就寝の習慣は体に睡眠の信号を送ります"),
            (["Reading", "taking", "a", "bath", "or", "listening", "to", "calm", "music", "helps"], 
             "読書入浴穏やかな音楽を聴くことが役立ちます"),
            (["Avoid", "heavy", "meals", "close", "to", "bedtime"], 
             "就寝時間に近い重い食事を避けます"),
            (["Digesting", "food", "can", "interfere", "with", "sleep"], 
             "食べ物の消化は睡眠を妨げる可能性があります"),
            (["However", "going", "to", "bed", "hungry", "is", "also", "problematic"], 
             "しかし空腹で寝ることも問題です"),
            (["A", "light", "snack", "like", "milk", "or", "banana", "can", "help"], 
             "牛乳やバナナのような軽いスナックが役立ちます"),
            (["Exercise", "helps", "sleep", "but", "timing", "matters"], 
             "運動は睡眠を助けますがタイミングが重要です"),
            (["Vigorous", "exercise", "late", "at", "night", "can", "be", "too", "stimulating"], 
             "夜遅い激しい運動は刺激的すぎる可能性があります"),
            (["Try", "to", "finish", "intense", "workouts", "at", "least", "three", "hours", "before", "bed"], 
             "就寝の少なくとも三時間前に激しいワークアウトを終えるようにします"),
            (["Gentle", "stretching", "or", "yoga", "before", "bed", "is", "beneficial"], 
             "就寝前の穏やかなストレッチやヨガは有益です"),
            (["Naps", "can", "be", "helpful", "or", "harmful", "depending", "on", "timing"], 
             "昼寝はタイミングによって有益または有害になる可能性があります"),
            (["Short", "naps", "of", "twenty", "minutes", "can", "boost", "alertness"], 
             "二十分の短い昼寝は注意力を高めることができます"),
            (["But", "long", "naps", "or", "naps", "late", "in", "the", "day", "disrupt", "night", "sleep"], 
             "しかし長い昼寝や一日の遅い時間の昼寝は夜の睡眠を乱します"),
            (["If", "you", "must", "nap", "do", "so", "before", "3", "PM"], 
             "昼寝をする必要がある場合は午後三時前にします"),
            (["Sleep", "disorders", "like", "insomnia", "affect", "many", "people"], 
             "不眠症のような睡眠障害は多くの人々に影響します"),
            (["If", "sleep", "problems", "persist", "consult", "a", "doctor"], 
             "睡眠の問題が続く場合は医師に相談します"),
            (["Professional", "help", "can", "identify", "underlying", "causes"], 
             "専門家の助けは根本的な原因を特定できます"),
            
            # Mental Health
            (["Mental", "health", "is", "just", "as", "important", "as", "physical", "health"], 
             "精神的健康は身体的健康と同じくらい重要です"),
            (["Our", "emotions", "and", "thoughts", "affect", "our", "overall", "wellbeing"], 
             "感情と思考は全体的な幸福に影響します"),
            (["Stress", "is", "a", "normal", "part", "of", "life"], 
             "ストレスは人生の普通の一部です"),
            (["But", "chronic", "stress", "can", "harm", "both", "mind", "and", "body"], 
             "しかし慢性的なストレスは心と体の両方を害する可能性があります"),
            (["We", "need", "healthy", "ways", "to", "manage", "stress"], 
             "ストレスを管理する健康的な方法が必要です"),
            (["Deep", "breathing", "exercises", "calm", "the", "nervous", "system"], 
             "深呼吸の練習は神経系を落ち着かせます"),
            (["Meditation", "helps", "clear", "the", "mind"], 
             "瞑想は心をクリアにするのを助けます"),
            (["Even", "five", "minutes", "of", "meditation", "can", "reduce", "anxiety"], 
             "わずか五分の瞑想でも不安を減らすことができます"),
            (["Spending", "time", "in", "nature", "improves", "mood"], 
             "自然の中で時間を過ごすことは気分を改善します"),
            (["Walking", "in", "a", "park", "or", "forest", "reduces", "stress", "hormones"], 
             "公園や森を歩くことはストレスホルモンを減らします"),
            (["Social", "connections", "are", "vital", "for", "mental", "health"], 
             "社会的つながりは精神的健康に不可欠です"),
            (["Spending", "time", "with", "family", "and", "friends", "provides", "support"], 
             "家族や友人と過ごすことはサポートを提供します"),
            (["Talking", "about", "problems", "helps", "us", "process", "emotions"], 
             "問題について話すことは感情を処理するのを助けます"),
            (["Helping", "others", "also", "improves", "our", "own", "mental", "health"], 
             "他者を助けることは私たち自身の精神的健康も改善します"),
            (["Volunteering", "gives", "us", "a", "sense", "of", "purpose"], 
             "ボランティアは目的意識を与えます"),
            (["It", "reminds", "us", "that", "we", "can", "make", "a", "difference"], 
             "私たちが違いを生むことができることを思い出させます"),
            (["Hobbies", "and", "creative", "activities", "are", "important"], 
             "趣味と創造的な活動は重要です"),
            (["They", "provide", "a", "break", "from", "daily", "routines"], 
             "日常のルーチンからの休憩を提供します"),
            (["They", "allow", "self", "expression", "and", "personal", "growth"], 
             "自己表現と個人の成長を可能にします"),
            (["Music", "art", "sports", "or", "gardening", "can", "be", "therapeutic"], 
             "音楽芸術スポーツ園芸は治療的である可能性があります"),
            (["Sometimes", "professional", "help", "is", "needed"], 
             "時には専門家の助けが必要です"),
            (["There", "is", "no", "shame", "in", "seeking", "counseling"], 
             "カウンセリングを求めることに恥はありません"),
            (["Therapists", "can", "teach", "coping", "strategies"], 
             "セラピストは対処戦略を教えることができます"),
            (["They", "provide", "a", "safe", "space", "to", "discuss", "feelings"], 
             "感情について話し合う安全な空間を提供します"),
            (["Mental", "health", "is", "not", "a", "sign", "of", "weakness"], 
             "精神的健康は弱さのしるしではありません"),
            (["It", "takes", "strength", "to", "acknowledge", "and", "address", "problems"], 
             "問題を認識し対処するには強さが必要です"),
            (["Positive", "thinking", "can", "improve", "mental", "health"], 
             "前向きな考えは精神的健康を改善できます"),
            (["Practice", "gratitude", "by", "noting", "things", "you", "are", "thankful", "for"], 
             "感謝していることに注目して感謝の練習をします"),
            (["This", "shifts", "focus", "from", "problems", "to", "positives"], 
             "これは問題から肯定的なことに焦点を移します"),
            (["Challenge", "negative", "thoughts", "with", "evidence"], 
             "証拠で否定的な考えに挑戦します"),
            (["Ask", "yourself", "if", "worries", "are", "realistic"], 
             "心配が現実的かどうか自分に尋ねます"),
            (["Often", "our", "fears", "are", "exaggerated"], 
             "しばしば私たちの恐れは誇張されています"),
            (["Laughter", "is", "powerful", "medicine", "for", "the", "mind"], 
             "笑いは心にとって強力な薬です"),
            (["Watch", "comedies", "spend", "time", "with", "funny", "friends"], 
             "コメディを見て面白い友達と時間を過ごします"),
            (["Laughter", "reduces", "stress", "and", "boosts", "mood"], 
             "笑いはストレスを減らし気分を高めます"),
            (["Setting", "realistic", "goals", "provides", "direction", "and", "motivation"], 
             "現実的な目標を設定することは方向性と動機を提供します"),
            (["Break", "large", "goals", "into", "smaller", "achievable", "steps"], 
             "大きな目標を達成可能な小さなステップに分解します"),
            (["Celebrate", "small", "victories", "along", "the", "way"], 
             "途中の小さな勝利を祝います"),
            (["This", "builds", "confidence", "and", "momentum"], 
             "これは自信と勢いを築きます"),
            
            # Daily Habits
            (["Small", "daily", "habits", "add", "up", "to", "big", "health", "benefits"], 
             "小さな日常の習慣は大きな健康上の利益になります"),
            (["Starting", "the", "day", "with", "a", "healthy", "breakfast", "is", "important"], 
             "健康的な朝食で一日を始めることは重要です"),
            (["Breakfast", "provides", "energy", "and", "improves", "concentration"], 
             "朝食はエネルギーを提供し集中力を改善します"),
            (["It", "jumpstarts", "metabolism", "after", "the", "night", "fast"], 
             "夜の絶食後に代謝を活性化します"),
            (["Regular", "meal", "times", "help", "regulate", "hunger", "and", "digestion"], 
             "規則的な食事時間は空腹と消化を調整するのを助けます"),
            (["Eating", "slowly", "and", "mindfully", "aids", "digestion"], 
             "ゆっくりと注意深く食べることは消化を助けます"),
            (["It", "also", "helps", "us", "recognize", "when", "we", "are", "full"], 
             "満腹になったことを認識するのも助けます"),
            (["Good", "posture", "prevents", "back", "and", "neck", "pain"], 
             "良い姿勢は背中と首の痛みを防ぎます"),
            (["When", "sitting", "keep", "your", "back", "straight", "and", "feet", "flat"], 
             "座るときは背中をまっすぐに足を平らに保ちます"),
            (["Take", "breaks", "from", "sitting", "every", "hour"], 
             "一時間ごとに座ることから休憩を取ります"),
            (["Stand", "up", "stretch", "and", "walk", "around"], 
             "立ち上がりストレッチして歩き回ります"),
            (["Hand", "washing", "is", "a", "simple", "but", "effective", "health", "practice"], 
             "手洗いは簡単ですが効果的な健康習慣です"),
            (["It", "prevents", "the", "spread", "of", "germs", "and", "diseases"], 
             "細菌と病気の拡散を防ぎます"),
            (["Wash", "hands", "before", "eating", "and", "after", "using", "the", "bathroom"], 
             "食事前とトイレ使用後に手を洗います"),
            (["Use", "soap", "and", "water", "for", "at", "least", "twenty", "seconds"], 
             "少なくとも二十秒間石鹸と水を使います"),
            (["Dental", "hygiene", "protects", "more", "than", "just", "teeth"], 
             "歯の衛生は歯以上のものを保護します"),
            (["Poor", "oral", "health", "can", "affect", "the", "heart", "and", "other", "organs"], 
             "口腔の健康状態が悪いと心臓や他の臓器に影響する可能性があります"),
            (["Brush", "teeth", "twice", "daily", "and", "floss", "once"], 
             "一日二回歯を磨き一回フロスします"),
            (["Regular", "dental", "checkups", "catch", "problems", "early"], 
             "定期的な歯科検診は問題を早期に発見します"),
            (["Proper", "hygiene", "extends", "beyond", "just", "teeth", "and", "hands"], 
             "適切な衛生は歯と手だけを超えて広がります"),
            (["Regular", "showers", "keep", "skin", "clean", "and", "healthy"], 
             "定期的なシャワーは肌を清潔で健康に保ちます"),
            (["Clean", "clothes", "prevent", "odor", "and", "skin", "irritation"], 
             "清潔な服は悪臭と皮膚の刺激を防ぎます"),
            (["Sun", "protection", "is", "important", "for", "skin", "health"], 
             "日焼け対策は皮膚の健康に重要です"),
            (["Use", "sunscreen", "when", "spending", "time", "outdoors"], 
             "屋外で時間を過ごすときは日焼け止めを使います"),
            (["Wear", "hats", "and", "protective", "clothing", "in", "strong", "sunlight"], 
             "強い日差しの中では帽子と保護服を着用します"),
            (["Too", "much", "sun", "exposure", "damages", "skin", "and", "increases", "cancer", "risk"], 
             "日光への過度の曝露は皮膚を損傷しがんのリスクを高めます"),
            (["Hydration", "affects", "every", "body", "system"], 
             "水分補給はすべての体のシステムに影響します"),
            (["Carry", "a", "water", "bottle", "to", "remind", "yourself", "to", "drink"], 
             "飲むことを思い出させるために水筒を持ち歩きます"),
            (["Thirst", "is", "not", "always", "a", "reliable", "indicator"], 
             "喉の渇きは常に信頼できる指標ではありません"),
            (["By", "the", "time", "you", "feel", "thirsty", "you", "are", "already", "dehydrated"], 
             "喉が渇いたと感じる頃にはすでに脱水状態です"),
            (["Urine", "color", "indicates", "hydration", "levels"], 
             "尿の色は水分補給レベルを示します"),
            (["Pale", "yellow", "means", "good", "hydration"], 
             "薄い黄色は良い水分補給を意味します"),
            (["Dark", "yellow", "means", "you", "need", "more", "water"], 
             "濃い黄色はもっと水が必要であることを意味します"),
            (["Limiting", "processed", "foods", "improves", "health"], 
             "加工食品を制限することは健康を改善します"),
            (["Cook", "meals", "at", "home", "when", "possible"], 
             "可能なときは家で食事を調理します"),
            (["This", "lets", "you", "control", "ingredients", "and", "portions"], 
             "これにより材料と量を管理できます"),
            (["Involve", "family", "members", "in", "meal", "preparation"], 
             "食事の準備に家族を巻き込みます"),
            (["This", "teaches", "cooking", "skills", "and", "healthy", "habits"], 
             "これは料理のスキルと健康的な習慣を教えます"),
            (["It", "also", "creates", "quality", "family", "time"], 
             "また質の高い家族の時間も作ります"),
            
            # Avoiding Harmful Habits
            (["Some", "habits", "seriously", "damage", "health"], 
             "一部の習慣は健康を深刻に損ないます"),
            (["Smoking", "is", "one", "of", "the", "worst", "things", "for", "health"], 
             "喫煙は健康にとって最悪のことの一つです"),
            (["It", "damages", "lungs", "heart", "and", "nearly", "every", "organ"], 
             "肺心臓ほぼすべての臓器を損傷します"),
            (["It", "causes", "cancer", "and", "many", "other", "diseases"], 
             "がんや他の多くの病気を引き起こします"),
            (["Never", "start", "smoking", "and", "if", "you", "smoke", "quit", "now"], 
             "決して喫煙を始めず喫煙している場合は今すぐやめましょう"),
            (["Alcohol", "should", "be", "avoided", "by", "young", "people"], 
             "若者はアルコールを避けるべきです"),
            (["It", "harms", "brain", "development"], 
             "脳の発達を害します"),
            (["It", "impairs", "judgment", "and", "leads", "to", "dangerous", "behaviors"], 
             "判断力を損ない危険な行動につながります"),
            (["Adults", "who", "drink", "should", "do", "so", "in", "moderation"], 
             "飲酒する大人は適度にすべきです"),
            (["Drug", "abuse", "destroys", "lives", "and", "families"], 
             "薬物乱用は命と家族を破壊します"),
            (["Even", "trying", "drugs", "once", "can", "lead", "to", "addiction"], 
             "一度薬物を試すだけでも依存症につながる可能性があります"),
            (["Stay", "away", "from", "all", "illegal", "drugs"], 
             "すべての違法薬物から離れます"),
            (["Excessive", "screen", "time", "is", "a", "modern", "health", "concern"], 
             "過度の画面時間は現代の健康上の懸念です"),
            (["Too", "much", "time", "on", "phones", "and", "computers", "strains", "eyes"], 
             "電話やコンピュータの時間が長すぎると目を痛めます"),
            (["It", "disrupts", "sleep", "patterns"], 
             "睡眠パターンを乱します"),
            (["It", "reduces", "physical", "activity"], 
             "身体活動を減らします"),
            (["Set", "limits", "on", "recreational", "screen", "time"], 
             "娯楽の画面時間に制限を設けます"),
            (["Balance", "online", "activities", "with", "real", "world", "experiences"], 
             "オンライン活動と現実世界の経験のバランスを取ります"),
            (["Energy", "drinks", "are", "another", "concern"], 
             "エネルギードリンクはもう一つの懸念です"),
            (["They", "contain", "high", "levels", "of", "caffeine", "and", "sugar"], 
             "高レベルのカフェインと砂糖を含んでいます"),
            (["They", "can", "cause", "heart", "problems", "and", "sleep", "disruption"], 
             "心臓の問題と睡眠の乱れを引き起こす可能性があります"),
            (["Young", "people", "should", "avoid", "energy", "drinks", "entirely"], 
             "若者はエネルギードリンクを完全に避けるべきです"),
            (["Peer", "pressure", "can", "lead", "to", "unhealthy", "choices"], 
             "仲間からの圧力は不健康な選択につながる可能性があります"),
            (["Learn", "to", "say", "no", "confidently"], 
             "自信を持って断ることを学びます"),
            (["True", "friends", "will", "respect", "your", "decisions"], 
             "本当の友達はあなたの決断を尊重します"),
            (["Surround", "yourself", "with", "people", "who", "support", "healthy", "habits"], 
             "健康的な習慣を支持する人々に囲まれます"),
            (["Positive", "influences", "make", "healthy", "living", "easier"], 
             "肯定的な影響は健康的な生活をより簡単にします"),
            (["Sedentary", "lifestyle", "is", "a", "major", "health", "risk"], 
             "座りがちな生活様式は主要な健康リスクです"),
            (["Sitting", "for", "long", "periods", "harms", "cardiovascular", "health"], 
             "長時間座ることは心血管の健康を害します"),
            (["It", "weakens", "muscles", "and", "bones"], 
             "筋肉と骨を弱めます"),
            (["Find", "ways", "to", "add", "movement", "throughout", "the", "day"], 
             "一日を通して動きを追加する方法を見つけます"),
            (["Stand", "during", "phone", "calls"], 
             "電話中は立ちます"),
            (["Do", "stretches", "during", "commercial", "breaks"], 
             "コマーシャル休憩中にストレッチをします"),
            (["Walk", "or", "bike", "for", "short", "errands", "instead", "of", "driving"], 
             "運転する代わりに短い用事は歩いたり自転車に乗ったりします"),
            
            # Practical Tips for Implementation
            (["Making", "healthy", "changes", "can", "feel", "overwhelming"], 
             "健康的な変化をすることは圧倒されるように感じることがあります"),
            (["Start", "small", "and", "build", "gradually"], 
             "小さく始めて徐々に築きます"),
            (["Replace", "one", "unhealthy", "snack", "with", "fruit"], 
             "一つの不健康なスナックを果物に置き換えます"),
            (["Add", "one", "extra", "vegetable", "to", "dinner"], 
             "夕食に一つ余分な野菜を追加します"),
            (["Walk", "for", "ten", "minutes", "after", "lunch"], 
             "昼食後に十分間歩きます"),
            (["These", "small", "steps", "create", "lasting", "change"], 
             "これらの小さなステップは永続的な変化を生み出します"),
            (["Track", "your", "progress", "to", "stay", "motivated"], 
             "モチベーションを維持するために進捗を追跡します"),
            (["Keep", "a", "journal", "of", "meals", "and", "activities"], 
             "食事と活動の日記をつけます"),
            (["Note", "how", "you", "feel", "physically", "and", "emotionally"], 
             "身体的精神的にどう感じるか記録します"),
            (["Seeing", "improvements", "encourages", "continued", "effort"], 
             "改善を見ることは継続的な努力を奨励します"),
            (["Find", "a", "health", "buddy", "for", "support"], 
             "サポートのために健康仲間を見つけます"),
            (["Exercise", "together", "share", "healthy", "recipes"], 
             "一緒に運動し健康的なレシピを共有します"),
            (["Encourage", "each", "other", "during", "difficult", "times"], 
             "困難な時期にお互いを励まします"),
            (["Accountability", "helps", "maintain", "healthy", "habits"], 
             "説明責任は健康的な習慣を維持するのを助けます"),
            (["Learn", "to", "read", "food", "labels"], 
             "食品ラベルを読むことを学びます"),
            (["Check", "serving", "sizes", "and", "nutritional", "content"], 
             "一食分のサイズと栄養内容を確認します"),
            (["Avoid", "products", "with", "long", "lists", "of", "unfamiliar", "ingredients"], 
             "なじみのない成分の長いリストがある製品を避けます"),
            (["Simple", "ingredients", "usually", "mean", "healthier", "food"], 
             "シンプルな成分は通常より健康的な食べ物を意味します"),
            (["Meal", "planning", "saves", "time", "and", "supports", "healthy", "eating"], 
             "食事計画は時間を節約し健康的な食事をサポートします"),
            (["Plan", "weekly", "menus", "and", "shop", "accordingly"], 
             "週間メニューを計画しそれに応じて買い物します"),
            (["Prepare", "ingredients", "in", "advance", "when", "possible"], 
             "可能なときは事前に材料を準備します"),
            (["Having", "healthy", "options", "ready", "prevents", "poor", "choices"], 
             "健康的な選択肢を用意しておくことは悪い選択を防ぎます"),
            (["Regular", "health", "checkups", "are", "important"], 
             "定期的な健康診断は重要です"),
            (["Doctors", "can", "detect", "problems", "early"], 
             "医師は問題を早期に発見できます"),
            (["They", "can", "provide", "personalized", "health", "advice"], 
             "個別化された健康アドバイスを提供できます"),
            (["Do", "not", "ignore", "unusual", "symptoms"], 
             "異常な症状を無視しないでください"),
            (["Early", "treatment", "is", "often", "more", "effective"], 
             "早期治療はしばしばより効果的です"),
            (["Vaccinations", "protect", "against", "serious", "diseases"], 
             "予防接種は深刻な病気から守ります"),
            (["Stay", "up", "to", "date", "with", "recommended", "vaccines"], 
             "推奨されるワクチンを最新の状態に保ちます"),
            (["They", "not", "only", "protect", "you", "but", "also", "others"], 
             "あなただけでなく他の人も保護します"),
            
            # Conclusion
            (["Living", "healthily", "requires", "commitment", "and", "effort"], 
             "健康的に生きることには献身と努力が必要です"),
            (["But", "the", "rewards", "are", "enormous"], 
             "しかし報酬は莫大です"),
            (["Good", "health", "gives", "us", "the", "energy", "to", "achieve", "our", "goals"], 
             "健康は目標を達成するエネルギーを与えます"),
            (["It", "allows", "us", "to", "enjoy", "time", "with", "loved", "ones"], 
             "愛する人々と過ごす時間を楽しむことを可能にします"),
            (["It", "improves", "our", "mood", "and", "outlook", "on", "life"], 
             "気分と人生観を改善します"),
            (["Small", "changes", "can", "make", "a", "big", "difference"], 
             "小さな変化が大きな違いを生むことができます"),
            (["Start", "with", "one", "or", "two", "improvements"], 
             "一つか二つの改善から始めます"),
            (["When", "these", "become", "habits", "add", "more"], 
             "これらが習慣になったらさらに追加します"),
            (["Remember", "that", "nobody", "is", "perfect"], 
             "誰も完璧ではないことを覚えておいてください"),
            (["Occasional", "treats", "and", "rest", "days", "are", "fine"], 
             "時々のご褒美と休息日は問題ありません"),
            (["The", "goal", "is", "progress", "not", "perfection"], 
             "目標は完璧さではなく進歩です"),
            (["Consistency", "is", "more", "important", "than", "intensity"], 
             "一貫性は強度より重要です"),
            (["A", "moderate", "routine", "followed", "regularly"], 
             "定期的に続ける適度なルーチン"),
            (["Is", "better", "than", "an", "extreme", "plan", "abandoned", "quickly"], 
             "すぐに放棄される極端な計画より良いです"),
            (["Listen", "to", "your", "body"], 
             "体の声に耳を傾けます"),
            (["Rest", "when", "tired", "eat", "when", "hungry"], 
             "疲れたら休み空腹時に食べます"),
            (["Pay", "attention", "to", "how", "different", "foods", "and", "activities", "affect", "you"], 
             "異なる食べ物や活動があなたにどう影響するか注意を払います"),
            (["Everyone", "is", "unique", "and", "needs", "a", "personalized", "approach"], 
             "誰もがユニークで個別のアプローチが必要です"),
            (["Your", "health", "is", "your", "most", "valuable", "asset"], 
             "あなたの健康は最も価値ある資産です"),
            (["Invest", "time", "and", "effort", "in", "maintaining", "it"], 
             "それを維持するために時間と努力を投資します"),
            (["The", "benefits", "will", "last", "a", "lifetime"], 
             "利益は一生続くでしょう"),
            (["Start", "today", "your", "future", "self", "will", "thank", "you"], 
             "今日から始めましょう将来の自分が感謝するでしょう"),
            (["Health", "is", "not", "just", "about", "adding", "years", "to", "life"], 
             "健康は人生に年を加えるだけではありません"),
            (["It", "is", "about", "adding", "life", "to", "years"], 
             "年に生命を加えることです"),
            (["Quality", "of", "life", "matters", "as", "much", "as", "length"], 
             "生活の質は長さと同じくらい重要です"),
            (["Healthy", "habits", "allow", "us", "to", "do", "things", "we", "love"], 
             "健康的な習慣は私たちが愛することをすることを可能にします"),
            (["They", "give", "us", "energy", "for", "adventures"], 
             "冒険のためのエネルギーを与えます"),
            (["They", "help", "us", "be", "present", "for", "important", "moments"], 
             "重要な瞬間に存在するのを助けます"),
            (["Good", "health", "is", "a", "gift", "we", "give", "ourselves"], 
             "健康は私たちが自分自身に与える贈り物です"),
            (["It", "is", "also", "a", "gift", "to", "those", "who", "love", "us"], 
             "それはまた私たちを愛する人々への贈り物です"),
            (["When", "we", "take", "care", "of", "ourselves"], 
             "自分自身の世話をするとき"),
            (["We", "can", "better", "care", "for", "others"], 
             "他の人をよりよく世話することができます"),
            (["We", "set", "a", "positive", "example"], 
             "肯定的な例を示します"),
            (["Especially", "for", "younger", "family", "members"], 
             "特に若い家族のために"),
            (["Children", "learn", "by", "watching", "adults"], 
             "子供たちは大人を見て学びます"),
            (["Model", "the", "healthy", "behaviors", "you", "want", "them", "to", "adopt"], 
             "彼らに採用してほしい健康的な行動をモデル化します"),
            (["Make", "health", "a", "family", "priority"], 
             "健康を家族の優先事項にします"),
            (["Cook", "together", "exercise", "together"], 
             "一緒に料理し一緒に運動します"),
            (["Support", "each", "other", "healthy", "choices"], 
             "お互いの健康的な選択をサポートします"),
            (["Remember", "setbacks", "are", "normal"], 
             "挫折は普通であることを覚えておいてください"),
            (["Everyone", "has", "days", "when", "they", "eat", "poorly", "or", "skip", "exercise"], 
             "誰もが食事が悪かったり運動をスキップしたりする日があります"),
            (["What", "matters", "is", "getting", "back", "on", "track"], 
             "重要なのは軌道に戻ることです"),
            (["Do", "not", "let", "one", "bad", "day", "become", "a", "bad", "week"], 
             "一日の悪い日を悪い週にしないでください"),
            (["Learn", "from", "mistakes", "and", "move", "forward"], 
             "間違いから学び前進します"),
            (["Celebrate", "your", "health", "achievements"], 
             "健康の達成を祝います"),
            (["Did", "you", "exercise", "three", "times", "this", "week"], 
             "今週三回運動しましたか"),
            (["Did", "you", "drink", "enough", "water", "today"], 
             "今日十分な水を飲みましたか"),
            (["Did", "you", "choose", "fruit", "over", "candy"], 
             "キャンディーより果物を選びましたか"),
            (["These", "victories", "deserve", "recognition"], 
             "これらの勝利は認識に値します"),
            (["A", "healthy", "lifestyle", "is", "a", "journey", "not", "a", "destination"], 
             "健康的なライフスタイルは目的地ではなく旅です"),
            (["There", "is", "always", "room", "for", "improvement"], 
             "常に改善の余地があります"),
            (["But", "there", "is", "also", "room", "for", "enjoyment"], 
             "しかし楽しみの余地もあります"),
            (["Health", "should", "enhance", "life", "not", "restrict", "it"], 
             "健康は人生を制限するのではなく高めるべきです"),
            (["Find", "balance", "between", "discipline", "and", "flexibility"], 
             "規律と柔軟性のバランスを見つけます"),
            (["Your", "choices", "today", "shape", "your", "tomorrow"], 
             "今日のあなたの選択が明日を形作ります"),
            (["Every", "healthy", "choice", "is", "an", "investment", "in", "your", "future"], 
             "すべての健康的な選択はあなたの未来への投資です"),
            (["That", "investment", "pays", "dividends", "in", "energy", "happiness", "and", "longevity"], 
             "その投資はエネルギー幸福長寿で配当を支払います"),
            (["The", "best", "time", "to", "start", "was", "yesterday"], 
             "始める最良の時は昨日でした"),
            (["The", "second", "best", "time", "is", "now"], 
             "二番目に良い時は今です"),
            (["Take", "that", "first", "step", "toward", "a", "healthier", "you"], 
             "より健康的なあなたに向かってその最初の一歩を踏み出します"),
            (["Your", "body", "and", "mind", "will", "thank", "you"], 
             "あなたの体と心は感謝するでしょう"),
        ]
        
        for words, meaning in content:
            phrases.append(self.create_phrase(f"phrase-{pid}", words, meaning))
            pid += 1
        
        word_count = sum(len(p['words']) for p in phrases)
        
        return {
            "id": "intermediate-3",
            "title": "Healthy Living",
            "level": "中級",
            "theme": "健康的な生活",
            "targetWordCount": 2500,
            "actualWordCount": word_count,
            "phrases": phrases
        }


def main():
    print("="*70)
    print("高品質長文パッセージ生成ツール")
    print("="*70)
    print()
    
    generator = QualityPassageGenerator()
    
    passages = []
    passage_names = ["intermediate-1", "intermediate-2", "intermediate-3"]
    
    for name in passage_names:
        print(f"生成中: {name}...")
        method = getattr(generator, f"generate_{name.replace('-', '_')}")
        passage = method()
        generator.save_passage(passage)
        passages.append(passage)
        print()
    
    total = sum(p['actualWordCount'] for p in passages)
    
    print("="*70)
    print(f"✓ 生成完了: 合計{total}語")
    print("="*70)


if __name__ == "__main__":
    main()
