import * as vscode from 'vscode';
import * as fs from 'fs';
import * as path from 'path';
import { promisify } from 'util';
import type { Notifier } from '../ui/Notifier';

const writeFile = promisify(fs.writeFile);
const chmod = promisify(fs.chmod);
const exists = promisify(fs.exists);
const rename = promisify(fs.rename);
const lstat = promisify(fs.lstat);
const readlink = promisify(fs.readlink);
const unlink = promisify(fs.unlink);

/**
 * HookInstaller
 *
 * Git hooksをインストール・管理するクラス。
 * - pre-commit hookの生成とインストール
 * - 既存hookのバックアップ
 * - hookの削除とリストア
 */
export class HookInstaller {
  private outputChannel: vscode.OutputChannel;
  private notifier?: Notifier;

  constructor(outputChannel: vscode.OutputChannel, notifier?: Notifier) {
    this.outputChannel = outputChannel;
    this.notifier = notifier;
  }

  /**
   * pre-commit hookをインストール
   *
   * @param hooksDir - .git/hooksディレクトリのパス
   * @returns インストール成功ならtrue
   */
  async installPreCommitHook(hooksDir: string): Promise<boolean> {
    try {
      const hookPath = path.join(hooksDir, 'pre-commit');
      const backupPath = path.join(hooksDir, 'pre-commit.backup');

      // 既に repo 標準のリンク構成（.git/hooks/pre-commit -> scripts/pre-commit-ai-guard.sh）なら
      // 拡張は上書きしない（リンク先の scripts/* を破壊するリスクがあるため）
      if (await exists(hookPath)) {
        const isRepoGuardSymlink = await this.isSymlinkToRepoPreCommitGuard(hooksDir, hookPath);
        if (isRepoGuardSymlink) {
          this.outputChannel.appendLine(
            '[HookInstaller] Detected symlink pre-commit -> scripts/pre-commit-ai-guard.sh; leaving it untouched'
          );
          return true;
        }
      }

      // 既存hookをバックアップ
      if (await exists(hookPath)) {
        this.outputChannel.appendLine('[HookInstaller] Backing up existing pre-commit hook');
        await this.backupHookByRename(hookPath, backupPath);
      }

      // 新しいhookを生成
      const hookContent = this.generatePreCommitHook();
      await this.safeWriteHookFile(hookPath, hookContent);

      // 実行権限を付与 (Unix系のみ)
      if (process.platform !== 'win32') {
        await chmod(hookPath, 0o755);
      }

      this.outputChannel.appendLine('[HookInstaller] Pre-commit hook installed successfully');
      return true;
    } catch (error) {
      this.outputChannel.appendLine(`[HookInstaller] Error installing hook: ${error}`);
      this.notifier?.commandError(`Failed to install pre-commit hook: ${error}`);
      return false;
    }
  }

  /**
   * pre-commit hookスクリプトを生成
   *
   * @returns hookスクリプトの内容
   */
  private generatePreCommitHook(): string {
    return `#!/bin/sh
# Servant Pre-Commit Hook
# Auto-generated by Servant VSCode Extension

echo "🔍 Running Servant validation..."

# Prefer repo-local guard script if available (works even when VS Code CLI is not installed)
REPO_ROOT=$(git rev-parse --show-toplevel 2>/dev/null || true)
GUARD_SCRIPT="$REPO_ROOT/scripts/pre-commit-ai-guard.sh"

if [ -n "$REPO_ROOT" ] && [ -f "$GUARD_SCRIPT" ]; then
  echo "🛡️  Found repo-local guard: $GUARD_SCRIPT"
  if [ -x "$GUARD_SCRIPT" ]; then
    "$GUARD_SCRIPT"
    GUARD_EXIT=$?
  else
    # File exists but isn't executable (e.g., on fresh clones)
    sh "$GUARD_SCRIPT"
    GUARD_EXIT=$?
  fi

  if [ $GUARD_EXIT -ne 0 ]; then
    exit $GUARD_EXIT
  fi

  echo "✅ Repo guard passed."
fi

# VSCodeコマンドを使用して検証を実行
# 注: VSCodeが起動している必要があります

if ! command -v code >/dev/null 2>&1; then
  # If repo guard exists and passed, do not block commit just because VS Code CLI is missing.
  if [ -n "$REPO_ROOT" ] && [ -f "$GUARD_SCRIPT" ]; then
    echo "ℹ️  VS Code CLI (code) not found; skipping VS Code validation (repo guard already passed)."
    exit 0
  fi

  echo "❌ VS Code CLI (code) not found."
  echo "💡 Install/enable 'code' command in PATH or run validation manually:"
  echo "   - VS Code Command Palette: 'Servant: Validate Before Commit'"
  exit 1
fi

# 新しいIDを優先し、互換のため旧IDも試す
code --command servant.validateBeforeCommit >/dev/null 2>&1 || code --command instructionsValidator.validateBeforeCommit

EXIT_CODE=$?

if [ $EXIT_CODE -ne 0 ]; then
  echo "❌ Servant validation failed!"
  echo "💡 Fix the violations using Quick Fix in VSCode, then try committing again."
  exit 1
fi

echo "✅ Servant validation passed!"
exit 0
`;
  }

  /**
   * commit-msg hookをインストール
   *
   * @param hooksDir - .git/hooksディレクトリのパス
   * @returns インストール成功ならtrue
   */
  async installCommitMsgHook(hooksDir: string): Promise<boolean> {
    try {
      const hookPath = path.join(hooksDir, 'commit-msg');
      const backupPath = path.join(hooksDir, 'commit-msg.backup');

      // 既存hookをバックアップ
      if (await exists(hookPath)) {
        this.outputChannel.appendLine('[HookInstaller] Backing up existing commit-msg hook');
        await this.backupHookByRename(hookPath, backupPath);
      }

      // 新しいhookを生成
      const hookContent = this.generateCommitMsgHook();
      await this.safeWriteHookFile(hookPath, hookContent);

      // 実行権限を付与
      if (process.platform !== 'win32') {
        await chmod(hookPath, 0o755);
      }

      this.outputChannel.appendLine('[HookInstaller] Commit-msg hook installed successfully');
      return true;
    } catch (error) {
      this.outputChannel.appendLine(`[HookInstaller] Error installing commit-msg hook: ${error}`);
      return false;
    }
  }

  /**
   * commit-msg hookスクリプトを生成
   */
  private generateCommitMsgHook(): string {
    return `#!/bin/sh
# Servant Commit-Msg Hook
# Auto-generated by Servant VSCode Extension

COMMIT_MSG_FILE=$1
COMMIT_MSG=$(cat "$COMMIT_MSG_FILE")

echo "📝 Checking commit message..."

# Conventional Commits形式をチェック（オプション）
# 形式: type(scope): message
# 例: feat(ui): add new button component

if ! echo "$COMMIT_MSG" | grep -qE "^(feat|fix|docs|style|refactor|test|chore|perf)(\\(.+\\))?: .+"; then
  echo "⚠️  Commit message doesn't follow Conventional Commits format"
  echo "💡 Recommended format: type(scope): message"
  echo "   Example: feat(ui): add new button component"
  echo ""
  echo "   Types: feat, fix, docs, style, refactor, test, chore, perf"
  # 警告のみ、コミットは許可
fi

echo "✅ Commit message validation passed"
exit 0
`;
  }

  /**
   * hooksをアンインストール（バックアップからリストア）
   *
   * @param hooksDir - .git/hooksディレクトリのパス
   * @param hookName - hookの名前（'pre-commit'または'commit-msg'）
   */
  async uninstallHook(hooksDir: string, hookName: string): Promise<boolean> {
    try {
      const hookPath = path.join(hooksDir, hookName);
      const backupPath = path.join(hooksDir, `${hookName}.backup`);

      // バックアップが存在すれば復元
      if (await exists(backupPath)) {
        this.outputChannel.appendLine(`[HookInstaller] Restoring ${hookName} from backup`);
        await this.restoreHookByRename(hookPath, backupPath);
      } else {
        // バックアップがなければhookを削除
        this.outputChannel.appendLine(`[HookInstaller] Removing ${hookName}`);
        if (await exists(hookPath)) {
          await unlink(hookPath);
        }
      }

      this.outputChannel.appendLine(`[HookInstaller] ${hookName} uninstalled successfully`);
      return true;
    } catch (error) {
      this.outputChannel.appendLine(`[HookInstaller] Error uninstalling hook: ${error}`);
      return false;
    }
  }

  /**
   * hookが既にインストールされているかチェック
   *
   * @param hooksDir - .git/hooksディレクトリのパス
   * @param hookName - hookの名前
   * @returns インストール済みならtrue
   */
  async isHookInstalled(hooksDir: string, hookName: string): Promise<boolean> {
    try {
      const hookPath = path.join(hooksDir, hookName);
      if (!await exists(hookPath)) {
        return false;
      }

       // repo 標準のシンボリックリンク構成を「インストール済み」と見なす
       if (hookName === 'pre-commit') {
         const isRepoGuardSymlink = await this.isSymlinkToRepoPreCommitGuard(hooksDir, hookPath);
         if (isRepoGuardSymlink) {
           return true;
         }
       }

      const content = await promisify(fs.readFile)(hookPath, 'utf8');
      // Servant/Instructions Validatorのシグネチャをチェック（後方互換）
      return content.includes('Servant VSCode Extension') || content.includes('Instructions Validator');
    } catch {
      return false;
    }
  }

  private async isSymlinkToRepoPreCommitGuard(hooksDir: string, hookPath: string): Promise<boolean> {
    try {
      const st = await lstat(hookPath);
      if (!st.isSymbolicLink()) return false;

      const linkTarget = await readlink(hookPath);
      const hooksDirReal = hooksDir;
      const repoRoot = path.resolve(hooksDirReal, '..', '..');
      const expected = path.join(repoRoot, 'scripts', 'pre-commit-ai-guard.sh');
      const resolved = path.resolve(path.dirname(hookPath), linkTarget);
      return path.normalize(resolved) === path.normalize(expected);
    } catch {
      return false;
    }
  }

  private async backupHookByRename(hookPath: string, backupPath: string): Promise<void> {
    // 既存のバックアップがあれば上書き（内容より「現物」を残す）
    if (await exists(backupPath)) {
      try {
        await unlink(backupPath);
      } catch {
        // ignore
      }
    }
    await rename(hookPath, backupPath);
  }

  private async restoreHookByRename(hookPath: string, backupPath: string): Promise<void> {
    if (await exists(hookPath)) {
      try {
        const st = await lstat(hookPath);
        if (st.isSymbolicLink()) {
          await unlink(hookPath);
        } else {
          await unlink(hookPath);
        }
      } catch {
        // ignore
      }
    }

    await rename(backupPath, hookPath);
    if (process.platform !== 'win32') {
      await chmod(hookPath, 0o755);
    }
  }

  private async safeWriteHookFile(hookPath: string, content: string): Promise<void> {
    // hookPath がシンボリックリンクの場合、リンク先を書き換えないようリンクを解除してから書き込む
    if (await exists(hookPath)) {
      try {
        const st = await lstat(hookPath);
        if (st.isSymbolicLink()) {
          await unlink(hookPath);
        }
      } catch {
        // ignore
      }
    }

    await writeFile(hookPath, content, 'utf8');
  }

  /**
   * 全てのhooksをインストール
   *
   * @param hooksDir - .git/hooksディレクトリのパス
   * @returns 全てのインストールが成功したらtrue
   */
  async installAllHooks(hooksDir: string): Promise<boolean> {
    const config = vscode.workspace.getConfiguration('servant');
    const legacyConfig = vscode.workspace.getConfiguration('instructionsValidator');

    const installPreCommit =
      config.get<boolean>('preCommit.enabled') ??
      legacyConfig.get<boolean>('preCommit.enabled', true);
    const installCommitMsg =
      config.get<boolean>('commitMsg.enabled') ??
      legacyConfig.get<boolean>('commitMsg.enabled', false);

    let success = true;

    if (installPreCommit) {
      success = await this.installPreCommitHook(hooksDir) && success;
    }

    if (installCommitMsg) {
      success = await this.installCommitMsgHook(hooksDir) && success;
    }

    return success;
  }

  /**
   * 全てのhooksをアンインストール
   *
   * @param hooksDir - .git/hooksディレクトリのパス
   * @returns 全てのアンインストールが成功したらtrue
   */
  async uninstallAllHooks(hooksDir: string): Promise<boolean> {
    let success = true;
    success = await this.uninstallHook(hooksDir, 'pre-commit') && success;
    success = await this.uninstallHook(hooksDir, 'commit-msg') && success;
    return success;
  }
}
