// 一般的な英語の熟語パターン（2-3語）
export const commonPhrases = [
  // 前置詞句
  'in order to',
  'in spite of',
  'because of',
  'instead of',
  'in front of',
  'according to',
  'as well as',
  'as soon as',
  'as long as',
  'in case of',
  'in addition to',
  'on behalf of',
  'with regard to',
  'in terms of',
  'by means of',

  // 動詞句
  'look forward to',
  'take care of',
  'get rid of',
  'make use of',
  'pay attention to',
  'keep in mind',
  'look after',
  'look for',
  'look into',
  'look up',
  'give up',
  'put off',
  'take off',
  'turn on',
  'turn off',
  'find out',
  'point out',
  'carry out',
  'break down',
  'bring up',
  'come up with',
  'get along with',
  'catch up with',
  'run out of',

  // 形容詞句
  'be able to',
  'be afraid of',
  'be interested in',
  'be good at',
  'be famous for',
  'be proud of',
  'be satisfied with',
  'be surprised at',
  'be worried about',

  // その他の一般的な熟語
  'a lot of',
  'a number of',
  'plenty of',
  'kind of',
  'sort of',
  'each other',
  'one another',
  'so that',
  'such as',
  'would like',
  'had better',
  'would rather',
  'used to',
  'thanks to',
  'due to',

  // 3語の熟語
  'as far as',
  'as well as',
  'as much as',
  'as many as',
  'not only but',
  'either or',
  'neither nor',
  'both and',
  'from time to time',
  'little by little',
  'step by step',
  'sooner or later',
  'more or less',
  'now and then',
];

// 2語の熟語を優先してチェック
export const twoWordPhrases = [
  'look for',
  'look at',
  'look after',
  'look forward',
  'look into',
  'look up',
  'look out',
  'give up',
  'give in',
  'give away',
  'give back',
  'take off',
  'take out',
  'take on',
  'take over',
  'take after',
  'take care',
  'put on',
  'put off',
  'put away',
  'put up',
  'put down',
  'get up',
  'get on',
  'get off',
  'get in',
  'get out',
  'get over',
  'get along',
  'turn on',
  'turn off',
  'turn down',
  'turn up',
  'turn into',
  'find out',
  'figure out',
  'point out',
  'work out',
  'carry out',
  'fill out',
  'break down',
  'break up',
  'break out',
  'break in',
  'bring up',
  'bring about',
  'bring back',
  'come up',
  'come back',
  'come across',
  'come from',
  'come out',
  'go on',
  'go over',
  'go through',
  'go ahead',
  'go back',
  'make up',
  'make out',
  'make sure',
  'set up',
  'set off',
  'set out',
  'pick up',
  'clean up',
  'wake up',
  'grow up',
  'show up',
  'run into',
  'run out',
  'run away',
  'deal with',
  'agree with',
  'begin with',
  'end up',
  'depend on',
  'rely on',
  'focus on',
  'concentrate on',
  'belong to',
  'lead to',
  'refer to',
  'according to',
  'thanks to',
  'due to',
  'next to',
  'close to',
  'at least',
  'at most',
  'at first',
  'at last',
  'at once',
  'at all',
  'in fact',
  'in general',
  'in particular',
  'in common',
  'in public',
  'on time',
  'on purpose',
  'on average',
  'on sale',
  'for example',
  'for instance',
  'for sure',
  'by chance',
  'by accident',
  'by mistake',
  'by far',
  'so far',
  'so that',
  'such as',
  'each other',
  'one another',
  'would like',
  'had better',
  'used to',
];
