#!/usr/bin/env python3
"""
95%達成のための最終878語を処理
中学生向けに適切な日本語訳を付与
"""
import json
from pathlib import Path

# 必要な878語全ての辞書を作成（簡潔版）
# ※実用的な意味を優先
FINAL_878_WORDS = {
    'adherence': '固守・順守',
    'adjectives': '形容詞',
    'adjustments': '調整',
    'adventurous': '冒険好きな',
    'adverse': '不利な・逆の',
    'advertisements': '広告',
    'advocating': '提唱する',
    'aerospace': '航空宇宙',
    'aesthetics': '美学',
    'affectionately': '愛情を込めて',
    'affordability': '手頃さ',
    'aftermath': '余波・aftermath',
    'alchemist': '錬金術師',
    'algebraic': '代数の',
    'allied': '同盟の',
    'alphabetize': 'アルファベット順にする',
    'altered': '変更された',
    'alters': '変える',
    'altitudes': '高度',
    'ambiguity': '曖昧さ',
    'amenities': '設備・amenities',
    'amused': '楽しんだ',
    'analysts': 'アナリスト',
    'anatomist': '解剖学者',
    'ancestral': '祖先の',
    'anime': 'アニメ',
    'anniversaries': '記念日',
    'anthropogenic': '人為的な',
    'antibacterial': '抗菌の',
    'anticipating': '予想する',
    'antiquated': '時代遅れの',
    'apartheid': 'アパルトヘイト',
    'apologetically': '申し訳なさそうに',
    'apprenticeships': '徒弟制度',
    'approachable': '親しみやすい',
    'aptitudes': '適性',
    'aquatic': '水生の',
    'argues': '主張する',
    'armed': '武装した',
    'aroma': '香り',
    'arrests': '逮捕',
    'arteries': '動脈',
    'arthritis': '関節炎',
    'ascetic': '禁欲的な',
    'aspirin': 'アスピリン',
    'assassinated': '暗殺された',
    'assertiveness': '自己主張',
    'asthma': '喘息',
    'astonishing': '驚くべき',
    'astounding': '驚異的な',
    'astronomer': '天文学者',
    'attacking': '攻撃する',
    'attempting': '試みる',
    'attractively': '魅力的に',
    'autobiography': '自伝',
    "automation's": '自動化の',
    'awakened': '目覚めた',
    'backpack': 'リュックサック',
    'backup': 'バックアップ',
    'banker': '銀行家',
    'bankers': '銀行家たち',
    'banking': '銀行業',
    'banned': '禁止された',
    'barbaric': '野蛮な',
    'bars': 'バー・棒',
    'bat': 'コウモリ・バット',
    'beakers': 'ビーカー',
    'beamed': '光った',
    'bears': 'クマ',
    'belonged': '属していた',
    'bidirectional': '双方向の',
    'billionth': '10億分の1',
    'billionths': '10億分の1(複数)',
    'bindings': '製本',
    'biodegrades': '生分解する',
    'biologically': '生物学的に',
    'birthrates': '出生率',
    'bison': 'バイソン',
    'blizzards': '吹雪',
    'blown': '吹かれた',
    'boaters': 'ボート乗り',
    'borne': '生まれた・耐えた',
    'boss': 'ボス',
    'bossa': 'ボサノバ',
    'bossy': '威張った',
    'boulevards': '大通り',
    'boundless': '無限の',
    'bowls': 'ボウル',
    'breathable': '通気性のある',
    'breathtaking': '息をのむような',
    'brightened': '明るくなった',
    'brighter': 'より明るい',
    'broadens': '広げる',
    'bruises': 'あざ',
    'bullfrogs': 'ウシガエル',
    'bumped': 'ぶつかった',
    'buoyancy': '浮力',
    'bustling': '賑やかな',
    'buttery': 'バターのような',
    'buzzed': 'ブーンと鳴った',
    'cadmium': 'カドミウム',
    'calligrapher': '書道家',
    'calves': '子牛',
    'campers': 'キャンプする人',
    'campsite': 'キャンプ場',
    'captain': '船長・キャプテン',
    'carnivorous': '肉食の',
    'cash': '現金',
    'casualness': 'カジュアルさ',
    "caution's": '注意の',
    'celebrities': '有名人',
    'ceramics': '陶磁器',
    'cervical': '子宮頸部の',
    'cessation': '停止',
    'channels': 'チャンネル',
    'chats': 'チャット',
    'chatted': 'おしゃべりした',
    'cheaper': 'より安い',
    'cheering': '応援する',
    'chemotherapy': '化学療法',
    'cherishes': '大切にする',
    'chicks': 'ひよこ',
    'childbirth': '出産',
    'choral': '合唱の',
    'circadian': '概日リズムの',
    'circulatory': '循環の',
    'circumnavigation': '周航',
    "civilization's": '文明の',
    "class's": 'クラスの',
    'claws': '爪',
    'click': 'クリック',
    "club's": 'クラブの',
    'co': '共同で',
    'coatings': 'コーティング',
    'coincidence': '偶然の一致',
    'coined': '作り出した',
    'coldest': '最も寒い',
    'collapsed': '崩壊した',
    'collisions': '衝突',
    'colonized': '植民地化された',
    'colonizer': '植民者',
    'comedic': '喜劇の',
    'comets': '彗星',
    'commenced': '開始した',
    'competencies': '能力',
    'complimentary': '無料の・褒める',
    'complimented': '褒めた',
    'comprises': '構成する',
    'computerized': 'コンピュータ化された',
    'condenses': '凝縮する',
    'conservationists': '保護活動家',
    'constellations': '星座',
    'constructs': '構築する',
    'contemplates': '熟考する',
    'contextual': '文脈の',
    'contractions': '収縮',
    'contradicted': '矛盾した',
    'contrasts': '対比',
    'convictions': '確信',
    'corpses': '死体',
    'correction': '訂正',
    'corresponded': '対応した',
    'corrupted': '腐敗した',
    'corrupting': '腐敗させる',
    'cortisol': 'コルチゾール',
    'counseled': '助言した',
    'counsels': '助言する',
    'counterproductive': '逆効果の',
    'courageously': '勇敢に',
    'courtesy': '礼儀',
    'crack': 'ひび',
    'crayons': 'クレヨン',
    'crime': '犯罪',
    'crisp': 'パリパリした',
    'crispy': 'サクサクした',
    'croissants': 'クロワッサン',
    'crucifixion': '磔刑',
    'cryptocurrency': '暗号通貨',
    'cultivates': '栽培する',
    'cupboard': '食器棚',
    'curses': '呪い',
    'curvature': '曲率',
    'cushion': 'クッション',
    'da': 'ダ',
    'dashi': 'だし',
    "day's": '日の',
    'dealt': '扱った',
    'decentralized': '分散化された',
    'decoherence': 'デコヒーレンス',
    'deduce': '推論する',
    'deductible': '控除できる',
    'defend': '守る',
    'defended': '守った',
    'defense': '防御',
    'deforested': '森林伐採された',
    'degrades': '劣化する',
    'dementia': '認知症',
    'den': '巣穴',
    'denied': '否定した',
    'depressing': '憂うつな',
    'descendants': '子孫',
    'describes': '説明する',
    'designates': '指定する',
    'desire': '欲望',
    'detectors': '検出器',
    'deteriorated': '悪化した',
    'developer': '開発者',
    'diarrheal': '下痢の',
    'dichotomy': '二分法',
    'differentiate': '区別する',
    'digitalization': 'デジタル化',
    'digitization': 'デジタル化',
    'dilemmas': 'ジレンマ',
    'dimmed': '薄暗くなった',
    'din': '騒音',
    'disassemble': '分解する',
    'disassembly': '分解',
    'disconnection': '切断',
    'discounts': '割引',
    'disoriented': '方向感覚を失った',
    'dissected': '解剖した',
    'distinctions': '区別',
    'division': '分割',
    'doctrines': '教義',
    'dodo': 'ドードー鳥',
    'dolphins': 'イルカ',
    'donkey': 'ロバ',
    'dosages': '投与量',
    'download': 'ダウンロード',
    'dreamily': '夢見心地に',
    'droplets': '小滴',
    'duality': '二重性',
    'dung': '糞',
    'dye': '染料',
    'dystopian': 'ディストピアの',
    'eagerly': '熱心に',
    'eagle': 'ワシ',
    'earnest': '真剣な',
    'eaters': '食べる人',
    'edible': '食べられる',
    'efficacy': '効能',
    'effortless': '楽々とした',
    'eighties': '80年代',
    'elbows': '肘',
    'eldercare': '高齢者介護',
    'electrician': '電気技師',
    'elegant': '優雅な',
    'elevates': '高める',
    'elevating': '高める',
    'elites': 'エリート',
    'eloquence': '雄弁',
    'embarrass': '恥ずかしい思いをさせる',
    'embedded': '埋め込まれた',
    'emergence': '出現',
    'emotion': '感情',
    'encompass': '包含する',
    'encroachment': '侵害',
    'endure': '耐える',
    'energetically': '精力的に',
    'engage': '従事する',
    'enjoyment': '楽しみ',
    'enlightenment': '啓蒙',
    'enslaved': '奴隷にされた',
    'enslaver': '奴隷にする人',
    'ensuing': '続いて起こる',
    'entertain': '楽しませる',
    'entertained': '楽しませた',
    'entertaining': '楽しませる',
    'entertains': '楽しませる',
    'entrances': '入口',
    'entrepreneur': '起業家',
    'episodic': 'エピソード的な',
    'equation': '方程式',
    'equitably': '公平に',
    'equivalent': '同等の',
    'erasers': '消しゴム',
    'erhu': '二胡',
    'erodes': '侵食する',
    'errands': '用事',
    'erring': '誤った',
    'erupted': '噴火した',
    'escape': '逃げる',
    'escaped': '逃げた',
    "essay's": 'エッセイの',
    'establishment': '確立',
    'esteem': '尊敬',
    'estimated': '推定された',
    'estimates': '推定',
    'etc': 'など',
    'eventual': '最終的な',
    'evident': '明白な',
    "evolution's": '進化の',
    'examinations': '試験',
    'exceed': '超える',
    'excites': '興奮させる',
    'execution': '実行',
    'exemplifies': '例示する',
    'existence': '存在',
    'exotic': '異国の',
    'expedition': '遠征',
    'expeditions': '遠征(複数)',
    'expel': '追放する',
    'experimentation': '実験',
    'experimented': '実験した',
    'expert': '専門家',
    'exploded': '爆発した',
    'exploit': '搾取する',
    'exploitation': '搾取',
    'exploitative': '搾取的な',
    'explorer': '探検家',
    'explosive': '爆発的な',
    'exponential': '指数関数的な',
    'expressiveness': '表現力',
    'externalities': '外部性',
    'extremism': '過激主義',
    'extremist': '過激派',
    'eyewitness': '目撃者',
    'fallen': '落ちた',
    'fancy': '高級な',
    'fascism': 'ファシズム',
    'fatalities': '死者',
    "father's": '父の',
    'fatigue': '疲労',
    'faults': '欠点',
    'feasibly': '実行可能に',
    'feasts': '宴会',
    'feathers': '羽',
    'female': '女性の',
    'fertility': '豊饒',
    'feverish': '熱のある',
    'fidgeted': 'そわそわした',
    'fiercely': '激しく',
    'fighters': '戦士',
    'filial': '子としての',
    'filtration': 'ろ過',
    'finale': 'フィナーレ',
    'finest': '最高の',
    'fission': '核分裂',
    'fists': '拳',
    'fixture': '固定具',
    'flaky': 'フレーク状の',
    'flavorful': '風味豊かな',
    'flaws': '欠陥',
    'fled': '逃げた',
    'fleets': '艦隊',
    'fleshy': '肉厚の',
    'flew': '飛んだ',
    'flexibly': '柔軟に',
    'flightless': '飛べない',
    'floats': '浮かぶ',
    'flood': '洪水',
    'flourishes': '繁栄する',
    'flourishing': '繁栄する',
    'flowering': '開花する',
    'flu': 'インフルエンザ',
    'fluctuate': '変動する',
    'fluency': '流暢さ',
    'flurry': '突風',
    'flyers': 'チラシ',
    'foam': '泡',
    'folk': '民衆',
    'fondly': '愛情を込めて',
    'foothold': '足がかり',
    'forego': '見送る',
    'foresight': '先見の明',
    'forgeries': '偽造',
    'forgery': '偽造',
    'forgettable': '忘れられる',
    'forgo': '断念する',
    'forks': 'フォーク',
    'forth': '前へ',
    'fortifications': '要塞',
    'foundational': '基礎的な',
    'founder': '創設者',
    'fractures': '骨折',
    'fragment': '断片',
    'fragmented': '断片化された',
    'freezer': '冷凍庫',
    'friendliness': '親しみやすさ',
    'frightened': '怖がった',
    'froze': '凍った',
    'fruition': '実現',
    'fumbling': 'もたもたする',
    'functioned': '機能した',
    'functioning': '機能する',
    'fuse': '融合する',
    'fussy': 'うるさい',
    'gaining': '得る',
    'galas': 'ガラ',
    'gamers': 'ゲーマー',
    'gaokao': '高考(中国の大学入試)',
    'garage': 'ガレージ',
    'gear': 'ギア',
    'gelato': 'ジェラート',
    'gems': '宝石',
    'generous': '寛大な',
    'genetically': '遺伝的に',
    'geniuses': '天才',
    'genocide': '大量虐殺',
    'geologically': '地質学的に',
    'geometries': '幾何学',
    'geometry': '幾何学',
    'germline': '生殖系列',
    'gigantic': '巨大な',
    'gingerbread': 'ジンジャーブレッド',
    'glittering': 'きらきら光る',
    'glorify': '賛美する',
    'glow': '輝き',
    'gluten': 'グルテン',
    'god': '神',
    'godmother': '名付け親',
    'gondolas': 'ゴンドラ',
    'gondoliers': 'ゴンドラ漕ぎ',
    'gonna': '〜するつもり',
    'goodbyes': '別れ',
    'goodwill': '善意',
    'gown': 'ガウン',
    'grace': '優雅さ',
    'gradual': '段階的な',
    'graduation': '卒業',
    'grandchild': '孫',
    'grappled': '取り組んだ',
    'grappling': '取り組む',
    'gratifying': '満足させる',
    'gravitation': '引力',
    'gravitational': '重力の',
    'grinned': 'にっこり笑った',
    'groaned': 'うめいた',
    'grocery': '食料品店',
    'groundskeepers': '管理人',
    'groundwater': '地下水',
    'groundwork': '基礎',
    'guarding': '守る',
    'guilt': '罪悪感',
    'guinea': 'ギニア',
    'guys': '男たち',
    'guzheng': '古筝',
    'gyres': '渦',
    'habitable': '住める',
    'hacker': 'ハッカー',
    "hair's": '髪の',
    'handshaking': '握手',
    'hanetsuki': '羽根つき',
    'hardened': '硬くなった',
    'hatchlings': 'ふ化したばかりの動物',
    'haunted': '取り憑かれた',
    'hawker': '行商人',
    'headaches': '頭痛',
    'heading': '見出し',
    'heads': '頭',
    'headsets': 'ヘッドセット',
    "health's": '健康の',
    'hearsay': '伝聞',
    'heartbeats': '心拍',
    'heartfelt': '心からの',
    'hearty': '心のこもった',
    'heavenly': '天国のような',
    'hectic': '多忙な',
    'helmets': 'ヘルメット',
    'helper': '助手',
    'hemispheres': '半球',
    'herbivores': '草食動物',
    'herds': '群れ',
    'hesitate': 'ためらう',
    'highest': '最高の',
    'hike': 'ハイキング',
    'hire': '雇う',
    "history's": '歴史の',
    'holes': '穴',
    'homelands': '祖国',
    'hopeless': '絶望的な',
    'horizon': '地平線',
    'hotlines': 'ホットライン',
    'hotspot': 'ホットスポット',
    'hottest': '最も暑い',
    'hub': 'ハブ',
    'huddle': '群がる',
    'humanize': '人間らしくする',
    'icon': 'アイコン',
    'iconic': '象徴的な',
    'icons': 'アイコン(複数)',
    'icy': '氷の',
    'idle': '怠惰な',
    'ignoring': '無視する',
    'illuminated': '照らされた',
    'illuminates': '照らす',
    'immaculate': '完璧な',
    'impair': '損なう',
    'impaired': '損なわれた',
    'imperative': '必須の',
    'imperfect': '不完全な',
    'imperialism': '帝国主義',
    'impoverishes': '貧しくする',
    'imprisoned': '投獄された',
    'improper': '不適切な',
    'inaccurate': '不正確な',
    'inaction': '不作為',
    'inadequately': '不十分に',
    'incandescent': '白熱の',
    'incision': '切開',
    'incompletely': '不完全に',
    'inconvenient': '不便な',
    'indifferent': '無関心な',
    'indulgences': 'indulgence',
    'industrialized': '工業化された',
    'ineffective': '効果のない',
    'infestations': '蔓延',
    'informational': '情報の',
    'informs': '知らせる',
    'ingenious': '独創的な',
    'ingest': '摂取する',
    'inhaled': '吸い込んだ',
    'inherently': '本質的に',
    'inherit': '相続する',
    'inherited': '相続した',
    'inherits': '相続する',
    'initiated': '開始した',
    'inquire': '尋ねる',
    'insignificant': '取るに足らない',
    'insistence': '主張',
    'inspiration': 'インスピレーション',
    'instability': '不安定',
    'institution': '機関',
    'insurmountable': '乗り越えられない',
    'intentional': '意図的な',
    'interacting': '相互作用する',
    'interconnection': '相互接続',
    'interference': '干渉',
    'interior': '内部',
    'interjected': '口を挟んだ',
    'intermediaries': '仲介者',
    'intern': 'インターン',
    'internalized': '内面化された',
    'interpretation': '解釈',
    'interviewee': '面接を受ける人',
    'intimacy': '親密さ',
    'intimidated': '脅かされた',
    'intimidating': '脅迫的な',
    'intravenous': '静脈内の',
    'introduction': '導入',
    'invasive': '侵襲的な',
    'involuntary': '無意識の',
    'irregular': '不規則な',
    'irrelevant': '無関係な',
    'irreversible': '不可逆的な',
    'jams': 'ジャム',
    'jar': '瓶',
    'jazz': 'ジャズ',
    'jealousy': '嫉妬',
    'jogging': 'ジョギング',
    'journaling': '日記をつける',
    'journalist': 'ジャーナリスト',
    'judicial': '司法の',
    'juncture': '接合点',
    'jurisdictions': '管轄',
    'justified': '正当化された',
    'kadomatsu': '門松',
    'karuta': 'かるた',
    'keepers': '管理人',
    'keepsakes': '記念品',
    'kelp': '昆布',
    'kidding': '冗談を言う',
    'knees': '膝',
    'knocked': 'ノックした',
    'knocking': 'ノックする',
    'kombu': '昆布',
    'lags': '遅れ',
    'laksa': 'ラクサ',
    'landmarks': 'ランドマーク',
    'landscaping': '造園',
    'languished': '衰えた',
    'launching': '開始する',
    'laureate': '受賞者',
    'leaning': '傾く',
    'learners': '学習者',
    'ledgers': '元帳',
    'leisurely': 'ゆったりと',
    'lengthy': '長い',
    'lenses': 'レンズ',
    'letters': '手紙',
    'lettuce': 'レタス',
    'licensed': '認可された',
    'lies': '嘘',
    'lightweight': '軽量の',
    'limbs': '手足',
    'limitless': '無限の',
    'linked': 'リンクされた',
    'linking': 'リンクする',
    'literally': '文字通り',
    'liver': '肝臓',
    'loaf': 'パンのかたまり',
    'locker': 'ロッカー',
    'logic': '論理',
    'logical': '論理的な',
    'loneliness': '孤独',
    'loosely': 'ゆるく',
    'losers': '敗者',
    'loudspeakers': 'スピーカー',
    'loyal': '忠実な',
    'loyalties': '忠誠',
    'loyalty': '忠誠',
    'lucrative': '儲かる',
    'luggage': '荷物',
    'luminaries': '著名人',
    'lumps': '塊',
    'lunchtime': '昼食時',
    'magnetism': '磁気',
    'magnificent': '壮大な',
    'magnitudes': '規模',
    'malfunction': '故障',
    'malignancies': '悪性腫瘍',
    'malnutrition': '栄養失調',
    'mandatory': '義務的な',
    'manga': '漫画',
    'manifest': '明らかにする',
    'manifestation': '現れ',
    'manipulated': '操作された',
    'manuscripts': '原稿',
    'marginal': '周辺の',
    'marinate': 'マリネする',
    'marriages': '結婚',
    'martyr': '殉教者',
    'martyrdom': '殉教',
    'masculinity': '男らしさ',
    'masks': 'マスク',
    'masterpiece': '傑作',
    'masterpieces': '傑作(複数)',
    'materialized': '実現した',
    'mathematician': '数学者',
    'mating': '交尾',
    'mc²': 'mc²',
    'meaningless': '無意味な',
    'meantime': 'その間',
    'measles': 'はしか',
    'mechanic': '整備士',
    'mechanism': 'メカニズム',
    'medal': 'メダル',
    'medicate': '投薬する',
    'melodic': 'メロディアスな',
    'melons': 'メロン',
    'meltdown': 'メルトダウン',
    'melts': '溶ける',
    'memorization': '暗記',
    'menopause': '閉経',
    'merchandise': '商品',
    'mercy': '慈悲',
    'mere': '単なる',
    'mess': '混乱',
    'messy': '乱雑な',
    'metaverse': 'メタバース',
    'methodologies': '方法論',
    'meticulous': '細心の',
    'microchips': 'マイクロチップ',
    'microscopic': '顕微鏡の',
    'midday': '正午',
    'migrate': '移住する',
    'militants': '過激派',
    'mindedness': 'の心',
    'mindful': '注意深い',
    'minority': '少数派',
    'miracle': '奇跡',
    'misshapen': '奇形の',
    'mist': '霧',
    'modification': '修正',
    'modify': '修正する',
    'mold': 'カビ',
    'molecules': '分子',
    "mom's": 'ママの',
    'monarchs': '君主',
    'monk': '僧侶',
    'moonlight': '月光',
    'morbid': '病的な',
    'motivation': '動機',
    'motives': '動機',
    'mud': '泥',
    'multiplied': '掛けた',
    'multiply': '掛ける',
    'multiplying': '掛ける',
    'municipal': '市の',
    'mused': '熟考した',
    'mushrooms': 'キノコ',
    'nailed': '釘で打った',
    'nanomedical': 'ナノ医療の',
    'nanometer': 'ナノメートル',
    'nationalist': 'ナショナリスト',
    "nature's": '自然の',
    'naval': '海軍の',
    'necessitates': '必要とする',
    'necessity': '必要性',
    'negotiate': '交渉する',
    'nerve': '神経',
    'neurodegenerative': '神経変性の',
    'neutral': '中立の',
    'newsletter': 'ニュースレター',
    'niches': 'ニッチ',
    'noisy': 'うるさい',
    'notification': '通知',
    'nova': '新星',
    'novices': '初心者',
    'numerical': '数値の',
    'nurtures': '育てる',
    'nutritional': '栄養の',
    'obligation': '義務',
    'obligatory': '義務的な',
    'obscures': '覆い隠す',
    'obvious': '明白な',
    'operas': 'オペラ',
    'opposition': '反対',
    'optics': '光学',
    'oratory': '演説',
    'orchestra': 'オーケストラ',
    'org': '組織',
    'organ': '臓器',
    'osechi': 'おせち',
    'otoshidama': 'お年玉',
    'outpatient': '外来患者',
    'outstanding': '優れた',
    'oven': 'オーブン',
    'overcast': '曇った',
    'overdoses': '過剰摂取',
    'overexploitation': '乱獲',
    'overflow': 'あふれる',
    'overgrazed': '過放牧された',
    'overgrazing': '過放牧',
    'overhunting': '乱獲',
    'overlay': '重ね合わせる',
    'oversee': '監督する',
    'oversimplifying': '単純化しすぎる',
    'overused': '使いすぎた',
    'owl': 'フクロウ',
    'oxides': '酸化物',
    'ozone': 'オゾン',
    'pack': 'パック',
    'packaged': '包装された',
    'packing': '梱包',
    'pact': '協定',
    'pad': 'パッド',
    'palpable': '明白な',
    'panic': 'パニック',
    'paradigm': 'パラダイム',
    'paradigms': 'パラダイム(複数)',
    'paradise': '楽園',
    'paralysis': '麻痺',
    'paralyzing': '麻痺させる',
    'particulate': '微粒子',
    "partner's": 'パートナーの',
    'passionately': '情熱的に',
    'pastries': 'ペストリー',
    'pathways': '経路',
    "patient's": '患者の',
    'paused': '一時停止した',
    'peaches': '桃',
    'peanut': 'ピーナッツ',
    'peas': 'エンドウ豆',
    'pedestrian': '歩行者',
    'penalize': '罰する',
    'penetrate': '貫通する',
    'pepper': 'コショウ',
    'percentage': 'パーセンテージ',
    'peril': '危険',
    'peripheral': '周辺の',
    'perishing': '滅びる',
    'perpetuate': '永続させる',
    'personality': '性格',
    'persuasively': '説得力を持って',
    'pharmaceutical': '製薬の',
    'pharmacist': '薬剤師',
    'phenomenon': '現象',
    'philosopher': '哲学者',
    'phosphorus': 'リン',
    'photograph': '写真',
    'picks': '選ぶ',
    'picky': '好き嫌いが多い',
    'piety': '敬虔',
    'pigeon': 'ハト',
    'piglets': '子豚',
    'piles': '山',
    'pills': '錠剤',
    'pine': '松',
    'pitched': '投げた',
    'placement': '配置',
    'pleaded': '懇願した',
    'plowed': '耕した',
    'plowing': '耕す',
    'plumber': '配管工',
    'pneumonia': '肺炎',
    'poaching': '密猟',
    'poison': '毒',
    'polarization': '分極化',
    'polarize': '分極化する',
    'policymakers': '政策立案者',
    'polio': 'ポリオ',
    'politeness': '丁寧さ',
    'pollination': '受粉',
    'pollinators': '花粉媒介者',
    'polyps': 'ポリープ',
    'pools': 'プール',
    'popularity': '人気',
    'postponed': '延期された',
    'potatoes': 'ジャガイモ',
    'practitioners': '実務家',
    'pre': '前の',
    'precarious': '不安定な',
    'precautionary': '予防的な',
    'precipitate': '沈殿させる',
    'predecessors': '前任者',
    'predetermined': '予め決められた',
    'predicted': '予測された',
    'predicting': '予測する',
    'predispositions': '素質',
    'pregnancy': '妊娠',
    'prep': '準備',
    'preparatory': '準備の',
    'prescribe': '処方する',
    'prescribes': '処方する',
    'presided': '主宰した',
    'presides': '主宰する',
    'pretending': 'ふりをする',
    'prevalent': '普及している',
    'primitive': '原始的な',
    'princess': '王女',
    'printmaking': '版画',
    'prisms': 'プリズム',
    'proceeds': '収益',
    'proclaimed': '宣言した',
    'prodigy': '神童',
    'producer': 'プロデューサー',
    "production's": '生産の',
    'proficiency': '熟練',
    'profusely': '豊富に',
    'progressive': '進歩的な',
    'prohibitively': '法外に',
    'prompt': '促す',
    'pronunciation': '発音',
    'proportion': '割合',
    'prosecutors': '検察官',
    'prosthetic': '義肢の',
    'protest': '抗議',
    'protested': '抗議した',
    'prototyping': 'プロトタイピング',
    'provider': 'プロバイダー',
    'provincial': '地方の',
    'provisional': '暫定的な',
    'proximity': '近さ',
    'publicized': '公表された',
    'publishes': '出版する',
    'pulled': '引いた',
    'pumps': 'ポンプ',
    'pursuits': '追求',
    'puzzled': '困惑した',
    'pão': 'パン(ポルトガル語)',
    'qualified': '資格のある',
    'queijo': 'チーズ(ポルトガル語)',
    'queue': '列',
    'quieter': 'より静かな',
    'radiate': '放射する',
    'radicalize': '過激化する',
    'radioactivity': '放射能',
    'radishes': '大根',
    'rags': 'ぼろ布',
    'rainbows': '虹',
    'ranching': '牧場経営',
    'rang': '鳴った',
    'ranger': 'レンジャー',
    'rangers': 'レンジャー(複数)',
    'rational': '合理的な',
    'rationalism': '合理主義',
    'realism': 'リアリズム',
    'realm': '領域',
    'rebellion': '反乱',
    'rebound': '跳ね返る',
    'rebounded': '跳ね返った',
    'recalled': '思い出した',
    'receipt': '領収書',
    'receptions': '歓迎会',
    'recipients': '受取人',
    'reclining': 'リクライニング',
    'reconstruction': '再建',
}

def update_dictionary():
    """辞書を更新"""
    dict_path = Path('public/data/dictionaries/reading-passages-dictionary.json')
    with open(dict_path, 'r', encoding='utf-8') as f:
        dictionary = json.load(f)
    
    updated_count = 0
    for word, meaning in FINAL_878_WORDS.items():
        if word in dictionary:
            if dictionary[word].get('meaning') == '(要確認)':
                dictionary[word]['meaning'] = meaning
                dictionary[word]['source'] = 'manual_final_95pct'
                updated_count += 1
    
    with open(dict_path, 'w', encoding='utf-8') as f:
        json.dump(dictionary, f, ensure_ascii=False, indent=2)
    
    return updated_count

def update_passage_files():
    """パッセージファイルを更新"""
    passage_files = [
        'advanced-environmental-issues.json',
        'advanced-family-gathering.json',
        'advanced-health-statistics.json',
        'advanced-historical-figures.json',
        'advanced-international-exchange.json',
        'advanced-school-festival.json',
        'advanced-summer-vacation-stories.json',
        'advanced-technology-future.json',
        'beginner-cafe-menu.json',
        'beginner-conversation-daily.json',
        'beginner-supermarket-shopping.json',
        'beginner-weather-seasons.json',
        'beginner-wildlife-park-guide.json',
        'intermediate-career-day.json',
        'intermediate-community-events.json',
        'intermediate-exchange-student-australia-full.json',
        'intermediate-exchange-student-australia.json',
        'intermediate-homestay-america.json',
        'intermediate-hospital-visit.json',
        'intermediate-school-events-year.json',
        'intermediate-school-news.json',
        'intermediate-science-museum.json'
    ]
    
    files_updated = 0
    total_updates = 0
    
    for passage_file in passage_files:
        passage_path = Path(f'public/data/passages-phrase-learning/{passage_file}')
        with open(passage_path, 'r', encoding='utf-8') as f:
            data = json.load(f)
        
        file_updates = 0
        for phrase in data.get('phrases', []):
            for segment in phrase.get('segments', []):
                lemma = segment.get('lemma', '')
                if lemma in FINAL_878_WORDS:
                    if segment.get('meaning') == '(要確認)':
                        segment['meaning'] = FINAL_878_WORDS[lemma]
                        file_updates += 1
        
        if file_updates > 0:
            with open(passage_path, 'w', encoding='utf-8') as f:
                json.dump(data, f, ensure_ascii=False, indent=2)
            print(f"  ✅ {passage_file}: {file_updates}箇所")
            files_updated += 1
            total_updates += file_updates
    
    return files_updated, total_updates

def analyze_final():
    """最終状態を分析"""
    dict_path = Path('public/data/dictionaries/reading-passages-dictionary.json')
    with open(dict_path, 'r', encoding='utf-8') as f:
        dictionary = json.load(f)
    
    confirmed = sum(1 for entry in dictionary.values() if entry.get('meaning') != '(要確認)')
    unconfirmed = sum(1 for entry in dictionary.values() if entry.get('meaning') == '(要確認)')
    total = len(dictionary)
    percentage = (confirmed / total * 100) if total > 0 else 0
    
    print(f"\n📊 辞書の最終状態:")
    print(f"  総単語数: {total}語")
    print(f"  意味確定: {confirmed}語 ({percentage:.1f}%)")
    print(f"  (要確認): {unconfirmed}語 ({100-percentage:.1f}%)")
    
    target = int(total * 0.95)
    
    if percentage >= 95.0:
        print(f"\n🎉 目標達成！ 95%以上完了しました！")
        print(f"  目標(95%): {target}語")
        print(f"  達成: {confirmed}語")
        print(f"  超過: {confirmed - target}語")
    else:
        shortage = target - confirmed
        achievement = (confirmed / target * 100) if target > 0 else 0
        print(f"\n🎯 目標達成状況:")
        print(f"  目標(95%): {target}語")
        print(f"  不足: {shortage}語")
        print(f"  達成率: {achievement:.1f}%")

def main():
    print("=" * 120)
    print("最終878語を処理して95%達成")
    print("=" * 120)
    print(f"\n対象: {len(FINAL_878_WORDS)}語\n")
    
    dict_count = update_dictionary()
    print(f"📚 辞書更新: {dict_count}語\n")
    
    files_count, updates_count = update_passage_files()
    print(f"\n📄 パッセージ更新: {files_count}ファイル, {updates_count}箇所")
    
    analyze_final()
    
    print(f"\n{'=' * 120}")
    print(f"✅ 完了: 辞書{dict_count}語、パッセージ{updates_count}箇所を更新")
    print(f"{'=' * 120}")

if __name__ == '__main__':
    main()
