#!/usr/bin/env python3
"""
第1段階: 高頻度単語の優先対応

出現頻度が高い(要確認)単語を拡張英単語辞書で自動マッピング
複数形・過去形・ing形などの基本的な活用形も処理
"""

import json
from pathlib import Path
from collections import defaultdict

# 拡張英単語辞書（基本単語 + 頻出単語）
EXTENDED_DICTIONARY = {
    # パッセージファイルに実際に出現する頻出単語
    'neighborhoods': '近所・地域',
    'amazed': '驚いた',
    'forever': '永遠に',
    'imagined': '想像した',
    'terrible': 'ひどい・恐ろしい',
    'painting': '絵画',
    'entrance': '入口',
    'difficulties': '困難',
    'movement': '動き・運動',
    'forecasts': '予報',
    'asks': '尋ねる',
    'greatest': '最も偉大な',
    'thoughtfully': '思慮深く',
    'teenage': '10代の',
    'professions': '職業',
    'survival': '生存',
    'coverage': '報道・範囲',
    'influenced': '影響を受けた',
    'recovery': '回復',
    'polite': '礼儀正しい',
    'ate': '食べた',
    'moved': '移動した・感動した',
    'announced': '発表した',
    'grew': '成長した',
    'production': '生産',
    'attended': '出席した',
    'importance': '重要性',
    'met': '会った',
    'oxygen': '酸素',
    'organisms': '生物',
    
    # 頻出名詞
    'achievements': '成果・業績',
    'ancestors': '祖先',
    'appearance': '外見・出現',
    'architect': '建築家',
    'artists': '芸術家',
    'athletes': '運動選手',
    'attractions': '観光名所・魅力',
    'audiences': '観客・聴衆',
    'behaviors': '行動・振る舞い',
    'beliefs': '信念・信仰',
    'benefits': '利益・恩恵',
    'boundaries': '境界・限界',
    'campaigns': 'キャンペーン・運動',
    'candidates': '候補者',
    'celebrations': '祝賀・祭り',
    'challenges': '挑戦・課題',
    'characteristics': '特徴・特性',
    'citizens': '市民',
    'clients': '依頼人・顧客',
    'climates': '気候',
    'coaches': 'コーチ',
    'colleagues': '同僚',
    'collections': '収集品・コレクション',
    'communities': '地域社会・共同体',
    'competitions': '競争・コンテスト',
    'complaints': '苦情・不満',
    'concepts': '概念',
    'concerns': '懸念・関心事',
    'conditions': '条件・状態',
    'conferences': '会議',
    'conflicts': '対立・紛争',
    'connections': '接続・つながり',
    'consequences': '結果・影響',
    'consumers': '消費者',
    'contacts': '連絡・接触',
    'containers': '容器',
    'contents': '内容',
    'contests': 'コンテスト・競争',
    'contexts': '文脈・背景',
    'contracts': '契約',
    'contributions': '貢献・寄付',
    'conversations': '会話',
    'corners': '角・隅',
    'costumes': '衣装',
    'creatures': '生き物',
    'crimes': '犯罪',
    'crops': '作物',
    'crowds': '群衆',
    'cultures': '文化',
    'debates': '討論',
    'decisions': '決定',
    'decorations': '装飾',
    'definitions': '定義',
    'degrees': '度・学位',
    'demonstrations': '実演・デモ',
    'designs': 'デザイン・設計',
    'destinations': '目的地',
    'details': '詳細',
    'devices': '装置・機器',
    'diets': '食事・ダイエット',
    'dimensions': '寸法・次元',
    'disasters': '災害',
    'diseases': '病気',
    'dishes': '料理・皿',
    'distances': '距離',
    'districts': '地区',
    'doctors': '医者',
    'documents': '文書',
    'donations': '寄付',
    'dreams': '夢',
    'duties': '義務・職務',
    'editors': '編集者',
    'efforts': '努力',
    'elections': '選挙',
    'elements': '要素',
    'emotions': '感情',
    'employees': '従業員',
    'employers': '雇用主',
    'encounters': '遭遇・出会い',
    'enemies': '敵',
    'engineers': '技術者',
    'enterprises': '企業・事業',
    'entertainment': '娯楽',
    'environments': '環境',
    'episodes': 'エピソード・出来事',
    'equipment': '設備・装備',
    'errors': '誤り・エラー',
    'events': '出来事・イベント',
    'evidence': '証拠',
    'examples': '例',
    'exchanges': '交換',
    'executives': '経営者・幹部',
    'experiments': '実験',
    'experts': '専門家',
    'explanations': '説明',
    'expressions': '表現',
    'facilities': '施設',
    'factors': '要因',
    'failures': '失敗',
    'farmers': '農家',
    'fashions': 'ファッション・流行',
    'features': '特徴・特色',
    'feelings': '感情',
    'festivals': '祭り',
    'fields': '分野・畑',
    'films': '映画',
    'findings': '発見・調査結果',
    'forests': '森林',
    'formats': '形式',
    'foundations': '基礎・財団',
    'functions': '機能',
    'funds': '資金',
    'galleries': '美術館・ギャラリー',
    'gardens': '庭',
    'generations': '世代',
    'genres': 'ジャンル',
    'goals': '目標',
    'governments': '政府',
    'grades': '成績・等級',
    'graduates': '卒業生',
    'grants': '助成金・認可',
    'guests': '客',
    'guides': 'ガイド・案内',
    'habits': '習慣',
    'habitats': '生息地',
    'headquarters': '本部',
    'heights': '高さ',
    'heroes': '英雄',
    'historians': '歴史家',
    'hobbies': '趣味',
    'holidays': '休日',
    'hospitals': '病院',
    'hosts': '主催者・ホスト',
    'households': '家庭・世帯',
    'humans': '人間',
    'hunters': '狩人',
    'ideas': 'アイデア・考え',
    'identities': 'アイデンティティ・身元',
    'illustrations': '挿絵・例証',
    'images': '画像・イメージ',
    'impacts': '影響',
    'improvements': '改善',
    'incidents': '出来事・事件',
    'industries': '産業',
    'influences': '影響',
    'innovations': '革新',
    'insects': '昆虫',
    'insights': '洞察',
    'inspections': '検査',
    'inspectors': '検査官',
    'installations': '設置・施設',
    'instances': '例・事例',
    'institutes': '研究所',
    'instructions': '指示・説明書',
    'instruments': '楽器・器具',
    'interactions': '相互作用・交流',
    'interests': '興味・利益',
    'interviews': '面接・インタビュー',
    'inventions': '発明',
    'inventors': '発明家',
    'investments': '投資',
    'investors': '投資家',
    'islands': '島',
    'issues': '問題・課題',
    'items': '項目・品物',
    'jobs': '仕事',
    'journalists': 'ジャーナリスト',
    'judges': '裁判官・審査員',
    'kingdoms': '王国',
    'labels': 'ラベル・レッテル',
    'laboratories': '研究室',
    'landscapes': '景色・風景',
    'languages': '言語',
    'layers': '層',
    'leaders': 'リーダー',
    'lectures': '講義',
    'legends': '伝説',
    'legislators': '議員',
    'lessons': '授業・教訓',
    'levels': '水準・レベル',
    'libraries': '図書館',
    'licenses': '免許・許可',
    'limits': '限界・制限',
    'listeners': '聞き手',
    'locations': '場所',
    'losses': '損失',
    'machines': '機械',
    'magazines': '雑誌',
    'managers': '管理者',
    'manners': 'マナー・方法',
    'manufacturers': '製造業者',
    'maps': '地図',
    'markets': '市場',
    'materials': '材料',
    'matters': '問題・事柄',
    'meanings': '意味',
    'measures': '対策・測定',
    'media': 'メディア',
    'medicines': '薬',
    'meetings': '会議',
    'members': 'メンバー',
    'memories': '記憶',
    'merchants': '商人',
    'messages': 'メッセージ',
    'methods': '方法',
    'migrants': '移住者',
    'minds': '心・精神',
    'minerals': '鉱物',
    'ministers': '大臣',
    'minorities': '少数派',
    'mistakes': '間違い',
    'models': 'モデル・模型',
    'moments': '瞬間',
    'monitors': 'モニター・監視装置',
    'monuments': '記念碑',
    'movements': '動き・運動',
    'museums': '博物館',
    'musicians': '音楽家',
    'nations': '国家',
    'natives': '原住民',
    'neighbors': '隣人',
    'networks': 'ネットワーク',
    'newspapers': '新聞',
    'nobles': '貴族',
    'notes': '音符・メモ',
    'notices': '通知',
    'novels': '小説',
    'objects': '物・対象',
    'observations': '観察',
    'observers': '観察者',
    'obstacles': '障害',
    'occasions': '機会・場合',
    'occupations': '職業',
    'oceans': '海洋',
    'officers': '役員・将校',
    'officials': '公務員・役人',
    'operations': '操作・手術',
    'operators': '操作者',
    'opinions': '意見',
    'opponents': '対戦相手',
    'opportunities': '機会',
    'options': '選択肢',
    'orders': '注文・命令',
    'organizations': '組織',
    'organizers': '主催者',
    'origins': '起源',
    'outcomes': '結果',
    'outlets': '販売店・出口',
    'outputs': '出力・生産高',
    'owners': '所有者',
    'packages': '包み・パッケージ',
    'paintings': '絵画',
    'panels': 'パネル・委員会',
    'paragraphs': '段落',
    'parents': '両親',
    'participants': '参加者',
    'particles': '粒子',
    'partners': 'パートナー',
    'passages': '通路・一節',
    'passengers': '乗客',
    'passions': '情熱',
    'patterns': 'パターン・模様',
    'payments': '支払い',
    'peaks': '頂上・ピーク',
    'peasants': '農民',
    'pedestrians': '歩行者',
    'peers': '同輩',
    'penalties': '罰則',
    'periods': '期間',
    'permissions': '許可',
    'perspectives': '視点',
    'phenomena': '現象',
    'philosophers': '哲学者',
    'photographs': '写真',
    'photographers': '写真家',
    'phrases': 'フレーズ・句',
    'physicians': '内科医',
    'pieces': '断片・作品',
    'pioneers': '開拓者',
    'pixels': 'ピクセル',
    'planets': '惑星',
    'plans': '計画',
    'plants': '植物・工場',
    'platforms': 'プラットフォーム',
    'plots': '筋・陰謀',
    'poems': '詩',
    'poets': '詩人',
    'points': '点・要点',
    'policies': '政策',
    'politicians': '政治家',
    'populations': '人口',
    'ports': '港',
    'positions': '位置・立場',
    'possibilities': '可能性',
    'practices': '実践・練習',
    'prayers': '祈り',
    'predictions': '予測',
    'preferences': '好み',
    'preparations': '準備',
    'presentations': '発表・プレゼン',
    'presidents': '大統領・社長',
    'pressures': '圧力',
    'prices': '価格',
    'priests': '聖職者',
    'principles': '原則',
    'priorities': '優先事項',
    'prisoners': '囚人',
    'procedures': '手順',
    'processes': '過程・プロセス',
    'producers': '生産者',
    'products': '製品',
    'professionals': '専門家',
    'professors': '教授',
    'profiles': 'プロフィール・輪郭',
    'profits': '利益',
    'programs': 'プログラム',
    'projects': 'プロジェクト',
    'promises': '約束',
    'properties': '財産・特性',
    'proposals': '提案',
    'prospects': '見込み・展望',
    'protests': '抗議',
    'provinces': '州・地方',
    'publications': '出版物',
    'publishers': '出版社',
    'purposes': '目的',
    'qualities': '質・品質',
    'quantities': '量',
    'questions': '質問',
    'races': '人種・レース',
    'ranges': '範囲',
    'ranks': '階級・順位',
    'rates': '率・料金',
    'readers': '読者',
    'reasons': '理由',
    'rebels': '反逆者',
    'receivers': '受信者',
    'recipes': 'レシピ',
    'records': '記録',
    'references': '参考文献',
    'reforms': '改革',
    'refugees': '難民',
    'regions': '地域',
    'regulations': '規制',
    'relationships': '関係',
    'relatives': '親戚',
    'religions': '宗教',
    'remains': '遺跡・残り',
    'remarks': '発言・意見',
    'remedies': '治療法',
    'reports': '報告',
    'representatives': '代表',
    'requests': '要求',
    'researchers': '研究者',
    'reserves': '予備・保護区',
    'residents': '住民',
    'resources': '資源',
    'responses': '応答',
    'restaurants': 'レストラン',
    'restrictions': '制限',
    'results': '結果',
    'retailers': '小売業者',
    'revenues': '収入',
    'reviews': 'レビュー・批評',
    'revolutions': '革命',
    'rewards': '報酬',
    'rights': '権利',
    'risks': 'リスク',
    'rituals': '儀式',
    'rivals': 'ライバル',
    'rivers': '川',
    'roads': '道路',
    'robots': 'ロボット',
    'roles': '役割',
    'routes': 'ルート・経路',
    'routines': '日課',
    'ruins': '廃墟',
    'rulers': '支配者・定規',
    'rules': '規則',
    'rumors': 'うわさ',
    'sacrifices': '犠牲',
    'salaries': '給料',
    'samples': 'サンプル',
    'satellites': '衛星',
    'scales': '規模・秤',
    'scandals': 'スキャンダル',
    'scenarios': 'シナリオ',
    'scenes': '場面・光景',
    'schedules': 'スケジュール',
    'schemes': '計画・制度',
    'scholars': '学者',
    'sciences': '科学',
    'scientists': '科学者',
    'scores': '得点・楽譜',
    'screens': '画面・スクリーン',
    'scripts': '台本・文字',
    'sculptures': '彫刻',
    'seasons': '季節',
    'seats': '座席',
    'sections': '部分・区域',
    'sectors': '部門',
    'seeds': '種',
    'segments': '部分・区分',
    'senators': '上院議員',
    'senses': '感覚',
    'sentences': '文',
    'series': 'シリーズ',
    'servants': '使用人',
    'services': 'サービス',
    'sessions': 'セッション・会期',
    'settings': '設定・環境',
    'settlements': '定住地・和解',
    'settlers': '入植者',
    'shadows': '影',
    'shapes': '形',
    'shares': '株・分け前',
    'shelters': '避難所',
    'shifts': '交代・変化',
    'ships': '船',
    'shops': '店',
    'shores': '岸',
    'shots': 'ショット・注射',
    'signals': '信号',
    'signatures': '署名',
    'signs': '標識・兆候',
    'sites': '場所・遺跡',
    'situations': '状況',
    'sizes': 'サイズ',
    'skills': '技能',
    'slaves': '奴隷',
    'slopes': '斜面',
    'societies': '社会',
    'soldiers': '兵士',
    'solutions': '解決策',
    'sources': '源',
    'spaces': '空間',
    'speakers': '話者・スピーカー',
    'species': '種',
    'speeches': '演説',
    'speeds': '速度',
    'spirits': '精神・魂',
    'sponsors': 'スポンサー',
    'sports': 'スポーツ',
    'spots': '地点・斑点',
    'stages': '段階・舞台',
    'standards': '基準',
    'stars': '星',
    'statements': '声明',
    'stations': '駅',
    'statistics': '統計',
    'statues': '像',
    'status': '地位・状態',
    'steps': '段階・歩み',
    'stories': '物語',
    'storms': '嵐',
    'strategies': '戦略',
    'streams': '流れ・小川',
    'streets': '通り',
    'structures': '構造',
    'students': '学生',
    'studios': 'スタジオ',
    'studies': '研究',
    'styles': 'スタイル',
    'subjects': '主題・科目',
    'substances': '物質',
    'substitutes': '代用品',
    'suburbs': '郊外',
    'successes': '成功',
    'suggestions': '提案',
    'suits': 'スーツ・訴訟',
    'summaries': '要約',
    'summers': '夏',
    'summits': '頂上・首脳会談',
    'supplies': '供給',
    'supporters': '支持者',
    'surfaces': '表面',
    'surgeons': '外科医',
    'surveys': '調査',
    'survivors': '生存者',
    'suspects': '容疑者',
    'symbols': '象徴・記号',
    'symptoms': '症状',
    'systems': 'システム',
    'tables': 'テーブル・表',
    'talents': '才能',
    'targets': '目標・標的',
    'tasks': '仕事・課題',
    'taxes': '税金',
    'teachers': '教師',
    'teams': 'チーム',
    'techniques': '技術',
    'technologies': '技術',
    'teenagers': '10代の若者',
    'temples': '寺院',
    'tendencies': '傾向',
    'terms': '用語・期間',
    'territories': '領土',
    'tests': 'テスト',
    'texts': 'テキスト',
    'theaters': '劇場',
    'themes': 'テーマ',
    'theories': '理論',
    'therapies': '治療法',
    'threads': '糸・スレッド',
    'threats': '脅威',
    'tips': '先端・助言',
    'tissues': '組織',
    'titles': '題名・称号',
    'tools': '道具',
    'topics': '話題',
    'tourists': '観光客',
    'tournaments': 'トーナメント',
    'towers': '塔',
    'towns': '町',
    'tracks': '軌道・トラック',
    'trades': '貿易・取引',
    'traders': '商人',
    'traditions': '伝統',
    'trails': '小道',
    'trainers': 'トレーナー',
    'transactions': '取引',
    'transfers': '移転・転送',
    'transformations': '変化',
    'transitions': '移行',
    'translations': '翻訳',
    'translators': '翻訳者',
    'treatments': '治療',
    'treaties': '条約',
    'trends': '傾向・トレンド',
    'trials': '裁判・試験',
    'tribes': '部族',
    'tricks': 'トリック・芸',
    'trips': '旅行',
    'troops': '軍隊',
    'troubles': '困難・問題',
    'trucks': 'トラック',
    'truths': '真実',
    'tunnels': 'トンネル',
    'turns': '回転・順番',
    'tutors': '家庭教師',
    'types': '種類・タイプ',
    'unions': '組合・連合',
    'units': '単位',
    'universities': '大学',
    'updates': '更新',
    'users': '利用者',
    'utilities': '公共事業',
    'vacations': '休暇',
    'valleys': '谷',
    'values': '価値',
    'varieties': '種類',
    'vehicles': '乗り物',
    'vendors': '販売業者',
    'ventures': '事業',
    'versions': 'バージョン',
    'vessels': '容器・船',
    'veterans': '退役軍人',
    'victims': '犠牲者',
    'victories': '勝利',
    'videos': 'ビデオ',
    'views': '見方・景色',
    'villages': '村',
    'violations': '違反',
    'visitors': '訪問者',
    'vitamins': 'ビタミン',
    'voices': '声',
    'volumes': '量・巻',
    'volunteers': 'ボランティア',
    'voters': '投票者',
    'votes': '投票',
    'wages': '賃金',
    'walls': '壁',
    'wars': '戦争',
    'warnings': '警告',
    'warriors': '戦士',
    'wastes': '廃棄物',
    'waters': '水',
    'waves': '波',
    'weapons': '武器',
    'weathers': '天気',
    'websites': 'ウェブサイト',
    'weights': '重さ',
    'wheels': '車輪',
    'winds': '風',
    'windows': '窓',
    'wines': 'ワイン',
    'wings': '翼',
    'winners': '勝者',
    'winters': '冬',
    'witnesses': '証人・目撃者',
    'workers': '労働者',
    'workshops': '工房・ワークショップ',
    'worlds': '世界',
    'writers': '作家',
    'zones': '地帯',
    
    # 頻出形容詞・副詞
    'absolutely': '絶対に',
    'accidentally': '偶然に',
    'actively': '活発に',
    'actually': '実際に',
    'additionally': '加えて',
    'apparently': '明らかに',
    'approximately': 'およそ',
    'basically': '基本的に',
    'carefully': '注意深く',
    'certainly': '確かに',
    'clearly': '明らかに',
    'closely': '密接に',
    'commonly': '一般的に',
    'completely': '完全に',
    'constantly': '絶えず',
    'currently': '現在',
    'definitely': '確かに',
    'directly': '直接に',
    'easily': '簡単に',
    'effectively': '効果的に',
    'entirely': '完全に',
    'equally': '等しく',
    'especially': '特に',
    'essentially': '本質的に',
    'eventually': '最終的に',
    'exactly': '正確に',
    'extremely': '極めて',
    'fairly': 'かなり',
    'finally': '最後に',
    'formally': '正式に',
    'frequently': '頻繁に',
    'fully': '完全に',
    'generally': '一般的に',
    'gradually': '徐々に',
    'greatly': '大いに',
    'highly': '非常に',
    'immediately': 'すぐに',
    'incredibly': '信じられないほど',
    'indeed': '実に',
    'initially': '最初は',
    'naturally': '自然に',
    'nearly': 'ほとんど',
    'necessarily': '必ずしも',
    'obviously': '明らかに',
    'occasionally': 'たまに',
    'officially': '公式に',
    'originally': '元々',
    'particularly': '特に',
    'perfectly': '完璧に',
    'personally': '個人的に',
    'possibly': 'おそらく',
    'potentially': '潜在的に',
    'previously': '以前に',
    'primarily': '主に',
    'probably': 'おそらく',
    'properly': '適切に',
    'purely': '純粋に',
    'quickly': '素早く',
    'quite': 'かなり',
    'rarely': 'めったに〜ない',
    'really': '本当に',
    'recently': '最近',
    'regularly': '定期的に',
    'relatively': '比較的',
    'respectively': 'それぞれ',
    'seemingly': '一見',
    'seriously': '真剣に',
    'significantly': '著しく',
    'similarly': '同様に',
    'simply': '単に',
    'slightly': 'わずかに',
    'slowly': 'ゆっくり',
    'specifically': '具体的に',
    'strongly': '強く',
    'successfully': '成功して',
    'suddenly': '突然',
    'surely': '確かに',
    'surprisingly': '驚くことに',
    'therefore': 'それゆえに',
    'thoroughly': '徹底的に',
    'totally': '完全に',
    'traditionally': '伝統的に',
    'truly': '本当に',
    'typically': '典型的に',
    'ultimately': '最終的に',
    'unfortunately': '残念ながら',
    'usually': '通常',
    'virtually': '事実上',
    'widely': '広く',
    
    # その他頻出語
    "other's": '他人の',
    'ji': '二・ji（日本語のローマ字）',
    'p': 'p・ページ',
}


def main():
    # パスの設定
    dict_path = Path('public/data/dictionaries/reading-passages-dictionary.json')
    passages_dir = Path('public/data/passages-phrase-learning')
    
    # 辞書を読み込み
    print("📖 辞書を読み込み中...")
    with open(dict_path, 'r', encoding='utf-8') as f:
        dictionary = json.load(f)
    
    # パッセージファイル内の(要確認)単語を集計
    print("📊 (要確認)単語を集計中...")
    unconfirmed_words = defaultdict(int)
    
    for passage_file in passages_dir.glob('*.json'):
        with open(passage_file, 'r', encoding='utf-8') as f:
            data = json.load(f)
        
        for phrase in data.get('phrases', []):
            for segment in phrase.get('segments', []):
                word = segment.get('word', '').lower()
                meaning = segment.get('meaning', '')
                
                if meaning == '(要確認)' and word:
                    unconfirmed_words[word] += 1
    
    print(f"  見つかった(要確認)単語: {len(unconfirmed_words)}種類")
    
    # 拡張辞書でマッピング可能な単語を抽出
    fixed_words = {}
    for word, count in unconfirmed_words.items():
        if word in EXTENDED_DICTIONARY:
            fixed_words[word] = {
                'meaning': EXTENDED_DICTIONARY[word],
                'count': count
            }
    
    print(f"\n✅ 修正可能な単語: {len(fixed_words)}語")
    print(f"  総出現回数: {sum(w['count'] for w in fixed_words.values())}回")
    
    if not fixed_words:
        print("\n修正する単語がありません。")
        return
    
    # 辞書を更新
    print("\n📝 辞書を更新中...")
    updated_count = 0
    for word, info in fixed_words.items():
        if word in dictionary:
            if dictionary[word].get('meaning') == '(要確認)':
                dictionary[word]['meaning'] = info['meaning']
                dictionary[word]['source'] = 'high-frequency'
                updated_count += 1
    
    # 辞書を保存
    with open(dict_path, 'w', encoding='utf-8') as f:
        json.dump(dictionary, f, ensure_ascii=False, indent=2)
    
    print(f"  辞書更新: {updated_count}語")
    
    # パッセージファイルを更新
    print("\n📝 パッセージファイルを更新中...")
    total_updated = 0
    
    for passage_file in sorted(passages_dir.glob('*.json')):
        with open(passage_file, 'r', encoding='utf-8') as f:
            data = json.load(f)
        
        file_updated = 0
        for phrase in data.get('phrases', []):
            for segment in phrase.get('segments', []):
                word = segment.get('word', '').lower()
                
                if word in fixed_words and segment.get('meaning') == '(要確認)':
                    segment['meaning'] = fixed_words[word]['meaning']
                    file_updated += 1
        
        if file_updated > 0:
            with open(passage_file, 'w', encoding='utf-8') as f:
                json.dump(data, f, ensure_ascii=False, indent=2)
            print(f"  {passage_file.name}: {file_updated}箇所更新")
            total_updated += file_updated
    
    print(f"\n✅ 完了!")
    print(f"  修正した単語: {len(fixed_words)}語")
    print(f"  更新した箇所: {total_updated}箇所")
    
    # 上位20語を表示
    print("\n📊 修正した単語（出現頻度上位20）:")
    sorted_fixed = sorted(fixed_words.items(), key=lambda x: x[1]['count'], reverse=True)
    for i, (word, info) in enumerate(sorted_fixed[:20], 1):
        print(f"  {i}. {word}: {info['meaning']} ({info['count']}回)")


if __name__ == '__main__':
    main()
