#!/usr/bin/env python3
"""
1回出現単語 Part 1/4 (a-d, 350語)
"""
import json
from pathlib import Path

# Part 1の単語辞書 (350語)
PART1_DICT = {
    'abnormalities': '異常',
    'abolish': '廃止する',
    'abolished': '廃止された',
    'abolitionist': '奴隷制廃止論者',
    'abstractions': '抽象概念',
    'academically': '学業的に',
    'acceleration': '加速',
    'accepts': '受け入れる',
    'accommodates': '収容する',
    'accountable': '説明責任のある',
    'accumulates': '蓄積する',
    'accused': '告発された',
    'acquaintances': '知人',
    'acquisition': '取得',
    'acres': 'エーカー',
    'acrylic': 'アクリル',
    'activism': '社会運動',
    'acumen': '洞察力',
    'additions': '追加',
    'additive': '添加物',
    'addressing': '対処する',
    'adjusting': '調整する',
    'administer': '管理する',
    'admiration': '称賛',
    'adolescence': '青年期',
    'adulthood': '成人期',
    'advancing': '進歩する',
    'adversity': '逆境',
    'advocacy': '主張・擁護',
    'aesthetic': '美的な',
    'affection': '愛情',
    'affirm': '断言する',
    'afflicted': '苦しむ',
    'agriculture': '農業',
    'aiming': '目指す',
    'alarming': '憂慮すべき',
    'albums': 'アルバム',
    'aligning': '一致させる',
    'alleviating': '軽減する',
    'alliances': '同盟',
    'allocated': '割り当てられた',
    'alternate': '交互の',
    'alternatives': '代替案',
    'amazed': '驚いた',
    'ambitions': '野心',
    'amendments': '修正',
    'amidst': '〜の中で',
    'amplified': '増幅された',
    'analyzed': '分析された',
    'analyzing': '分析する',
    'anecdotes': '逸話',
    'angles': '角度',
    'animations': 'アニメーション',
    'annually': '毎年',
    'anticipated': '予想された',
    'anticipation': '期待',
    'antique': '骨董品',
    'anxiety': '不安',
    'apex': '頂点',
    'apologizing': '謝罪する',
    'apparatus': '装置',
    'appealing': '魅力的な',
    'appetite': '食欲',
    'applauded': '称賛された',
    'appliances': '家電製品',
    'applicants': '応募者',
    'appointed': '任命された',
    'appointments': '予約',
    'appreciates': '感謝する',
    'apprentice': '見習い',
    'approaches': 'アプローチ',
    'approval': '承認',
    'approximately': 'おおよそ',
    'arbor': '東屋',
    'archaeological': '考古学的な',
    'architects': '建築家',
    'archive': 'アーカイブ',
    'arguing': '議論する',
    'arise': '生じる',
    'aristocratic': '貴族的な',
    'arithmetic': '算数',
    'aromatic': '香りのよい',
    'arose': '生じた',
    'arranging': '配置する',
    'arrays': '配列',
    'arrivals': '到着',
    'arrow': '矢印',
    'arsenal': '兵器庫',
    'arterial': '動脈の',
    'articulate': '明確に述べる',
    'artifacts': '工芸品',
    'artificially': '人工的に',
    'ascending': '上昇する',
    'ashamed': '恥じる',
    'aspire': '熱望する',
    'assembling': '組み立てる',
    'asserting': '主張する',
    'assessed': '評価された',
    'asset': '資産',
    'assigning': '割り当てる',
    'assimilation': '同化',
    'assistance': '援助',
    'assuming': '仮定する',
    'assurance': '保証',
    'astonished': '驚いた',
    'astronomical': '天文学的な',
    'athletics': '陸上競技',
    'atmospheric': '大気の',
    'atoms': '原子',
    'attached': '添付された',
    'attain': '達成する',
    'attendees': '出席者',
    'attic': '屋根裏',
    'attributed': '起因する',
    'audiences': '観客',
    'auditorium': '講堂',
    'authentic': '本物の',
    'authoritative': '権威のある',
    'authorities': '当局',
    'authorization': '許可',
    'authorized': '認可された',
    'auto': '自動車',
    'automated': '自動化された',
    'automobile': '自動車',
    'autonomy': '自治',
    'autumn': '秋',
    'auxiliary': '補助的な',
    'availability': '入手可能性',
    'averaging': '平均する',
    'awaited': '待たれた',
    'awakening': '目覚め',
    'awarding': '授与する',
    'aware': '気づいている',
    'awkward': '気まずい',
    'axis': '軸',
    'backdrop': '背景',
    'backgrounds': '経歴',
    'backwards': '後ろ向きに',
    'bacterium': '細菌',
    'balancing': 'バランスをとる',
    'ballads': 'バラード',
    'bamboo': '竹',
    'bandage': '包帯',
    'banners': '横断幕',
    'baptism': '洗礼',
    'bargain': '掘り出し物',
    'barley': '大麦',
    'barren': '不毛の',
    'barriers': '障壁',
    'basics': '基本',
    'basil': 'バジル',
    'basin': '盆地',
    'batches': 'バッチ',
    'batteries': '電池',
    'battlefields': '戦場',
    'beacon': '標識',
    'bearable': '耐えられる',
    'beetles': '甲虫',
    'beginner': '初心者',
    'behavioral': '行動の',
    'beings': '生き物',
    'belongs': '属する',
    'beloved': '最愛の',
    'beneficiaries': '受益者',
    'benign': '良性の',
    'berries': 'ベリー',
    'besides': 'その上',
    'betray': '裏切る',
    'beverages': '飲料',
    'beware': '用心する',
    'bidding': '入札',
    'bilateral': '二国間の',
    'billion': '10億',
    'biography': '伝記',
    'biological': '生物学的な',
    'biome': '生物群系',
    'birthdays': '誕生日',
    'bishop': '司教',
    'blend': '混ぜる',
    'blending': '混合する',
    'blessed': '祝福された',
    'blindness': '盲目',
    'blogging': 'ブログを書く',
    'blooms': '開花する',
    'blueprint': '青写真',
    'blurred': 'ぼやけた',
    'boarding': '搭乗',
    'boats': 'ボート',
    'boiled': '茹でた',
    'boiling': '沸騰',
    'bonding': '結束',
    'bonds': '絆',
    'bonus': 'ボーナス',
    'boom': 'ブーム',
    'boosted': '押し上げられた',
    'booth': 'ブース',
    'botanical': '植物の',
    'bounce': '跳ねる',
    'boundaries': '境界',
    'bounded': '囲まれた',
    'bourgeoisie': 'ブルジョワジー',
    'boxes': '箱',
    'brackets': '括弧',
    'braille': '点字',
    'brake': 'ブレーキ',
    'branches': '枝',
    'branching': '分岐する',
    'branding': 'ブランディング',
    'breadth': '幅',
    'breakaway': '分離',
    'breakthrough': '画期的進歩',
    'breeds': '品種',
    'brewery': '醸造所',
    'brewing': '醸造する',
    'bricks': 'レンガ',
    'bridging': '橋渡しする',
    'briefly': '簡潔に',
    'brighten': '明るくする',
    'brightness': '明るさ',
    'brilliance': '輝き',
    'brilliant': '優秀な',
    'broadcast': '放送',
    'broaden': '広げる',
    'broader': 'より広い',
    'broadly': '広く',
    'brochures': 'パンフレット',
    'bronze': '青銅',
    'brownie': 'ブラウニー',
    'browsing': '閲覧する',
    'brutal': '残忍な',
    'bucket': 'バケツ',
    'budding': '新進の',
    'buffet': 'ビュッフェ',
    'buffers': '緩衝材',
    'bulk': '大部分',
    'bulletin': '掲示板',
    'bully': 'いじめっ子',
    'bump': 'ぶつかる',
    'bumpy': 'でこぼこの',
    'bundles': '束',
    'burden': '負担',
    'bureau': '局',
    'bureaucracy': '官僚制',
    'burial': '埋葬',
    'burning': '燃焼',
    'bursts': '破裂',
    'bury': '埋める',
    'buses': 'バス',
    'businessmen': 'ビジネスマン',
    'cabbage': 'キャベツ',
    'cabin': '小屋',
    'cactus': 'サボテン',
    'cafes': 'カフェ',
    'cafeteria': 'カフェテリア',
    'calculus': '微積分',
    'calligraphy': '書道',
    'calmly': '穏やかに',
    'calorie': 'カロリー',
    'camaraderie': '仲間意識',
    'cameras': 'カメラ',
    'campaigns': 'キャンペーン',
    'canal': '運河',
    'cancellation': 'キャンセル',
    'candid': '率直な',
    'candidly': '率直に',
    'candle': 'ろうそく',
    'canned': '缶詰の',
    'canopy': '天蓋',
    'canvas': 'キャンバス',
    'canyon': '峡谷',
    'capability': '能力',
    'capitalism': '資本主義',
    'capitalist': '資本主義の',
    'capsules': 'カプセル',
    'captivate': '魅了する',
    'captivated': '魅了された',
    'captive': '捕虜',
    'captivity': '捕らわれの身',
    'caramel': 'キャラメル',
    'carat': 'カラット',
    'caravan': 'キャラバン',
    'carbohydrate': '炭水化物',
    'cardiovascular': '心血管の',
    'cargo': '貨物',
    'caring': '思いやりのある',
    'carnival': 'カーニバル',
    'carpenter': '大工',
    'carpentry': '大工仕事',
    'carrot': 'にんじん',
    'cartoon': '漫画',
    'carve': '彫る',
    'carved': '彫刻された',
    'carving': '彫刻',
    'cascade': '滝',
    'caste': 'カースト',
    'castle': '城',
    'catalog': 'カタログ',
    'catalyst': '触媒',
    'catastrophic': '壊滅的な',
    'categories': 'カテゴリー',
    'categorize': '分類する',
    'catering': 'ケータリング',
    'cathedral': '大聖堂',
    'cattle': '牛',
    'causation': '因果関係',
    'cavalry': '騎兵隊',
    'caves': '洞窟',
    'ceiling': '天井',
    'celebrations': '祝賀',
    'celestial': '天体の',
    'cellular': '細胞の',
    'cement': 'セメント',
    'cemetery': '墓地',
    'censorship': '検閲',
    'census': '国勢調査',
    'centrally': '中央に',
    'ceramic': '陶磁器',
    'ceremonies': '式典',
    'certainty': '確実性',
    'certification': '認証',
    'chains': '鎖',
    'chairs': '椅子',
    'chalk': 'チョーク',
    'chambers': '部屋',
    'championed': '擁護した',
    'championship': '選手権',
    'characterize': '特徴づける',
    'charcoal': '炭',
    'charges': '料金',
    'charisma': 'カリスマ性',
    'charitable': '慈善の',
    'charm': '魅力',
    'charming': '魅力的な',
    'charter': '憲章',
    'charts': 'チャート',
    'chasing': '追いかける',
    'cheer': '応援する',
    'cheerful': '陽気な',
    'chef': 'シェフ',
    'chemically': '化学的に',
    'cherry': 'さくらんぼ',
    'chess': 'チェス',
    'chewing': '噛む',
    'chickens': '鶏',
    'childhood': '子供時代',
    'chile': 'チリ',
    'chili': '唐辛子',
    'chilly': '肌寒い',
    'chime': '鐘の音',
    'chimneys': '煙突',
    'chip': 'チップ',
    'chivalry': '騎士道',
    'chlorophyll': '葉緑素',
    'chocolate': 'チョコレート',
    'choir': '合唱団',
    'cholera': 'コレラ',
    'choreography': '振り付け',
    'chronic': '慢性的な',
    'chronological': '年代順の',
    'chunks': '塊',
    'cinnamon': 'シナモン',
    'circa': 'およそ',
    'circulate': '循環する',
    'circulating': '循環する',
    'circus': 'サーカス',
    'cite': '引用する',
    'citing': '引用する',
    'citizenship': '市民権',
    'civic': '市民の',
    'civilians': '民間人',
    'clapped': '拍手した',
    'clarify': '明確にする',
    'clarity': '明確さ',
    'clash': '衝突',
    'classical': '古典的な',
    'classification': '分類',
    'classmates': 'クラスメート',
    'classroom': '教室',
    'clauses': '節',
    'cleaner': 'より清潔な',
    'clearance': '認可',
    'clergy': '聖職者',
    'clever': '賢い',
    'clicking': 'クリックする',
    'climates': '気候',
    'clinics': '診療所',
    'clip': 'クリップ',
    'clocks': '時計',
    'clockwise': '時計回り',
    'closet': 'クローゼット',
    'cloth': '布',
    'cloud': '雲',
    'cloudy': '曇った',
    'cluster': '集団',
    'clutching': 'つかむ',
    'coal': '石炭',
    'coastal': '沿岸の',
    'coconut': 'ココナッツ',
    'codes': 'コード',
    'coding': 'コーディング',
    'coexist': '共存する',
    'coherent': '首尾一貫した',
    'cohesion': '結束',
    'coil': 'コイル',
    'coincide': '一致する',
    'coincidentally': '偶然に',
    'collaborated': '協力した',
    'collaboration': '協力',
    'collaborative': '協力的な',
    'collapse': '崩壊',
    'colleague': '同僚',
    'collective': '集団的な',
    'collectively': '集団的に',
    'collectors': '収集家',
    'colonial': '植民地の',
    'colonies': '植民地',
    'colonization': '植民地化',
    'colors': '色',
    'column': '列',
    'columns': '列',
    'comedies': '喜劇',
    'comforting': '慰める',
    'commanding': '指揮する',
    'commemorate': '記念する',
    'commence': '開始する',
    'commended': '称賛された',
    'commentary': '解説',
    'commerce': '商業',
    'commissioners': 'コミッショナー',
    'commits': '犯す',
    'commodity': '商品',
    'commonplace': 'ありふれた',
    'communal': '共同の',
    'communications': 'コミュニケーション',
    'communism': '共産主義',
    'communist': '共産主義の',
    'companionship': '交友',
    'comparable': '匹敵する',
    'comparative': '比較の',
    'compartments': '区画',
    'compatibility': '互換性',
    'compelling': '説得力のある',
    'compensate': '補償する',
    'competence': '能力',
    'competitive': '競争力のある',
    'competitors': '競合他社',
    'compile': '編集する',
    'compiled': '編集された',
    'complacency': '自己満足',
    'complementary': '補完的な',
    'completion': '完成',
    'complexity': '複雑さ',
    'compliance': '遵守',
    'complicate': '複雑にする',
    'complication': '合併症',
    'compliment': '褒め言葉',
    'comply': '従う',
    'component': '構成要素',
    'compose': '作曲する',
    'composers': '作曲家',
    'composing': '作曲する',
    'composition': '作曲',
    'compound': '化合物',
    'comprehend': '理解する',
    'comprehensive': '包括的な',
    'compression': '圧縮',
    'comprised': '構成された',
    'compromise': '妥協',
    'compulsory': '義務的な',
    'compute': '計算する',
    'comrades': '同志',
    'conceal': '隠す',
    'concealed': '隠された',
    'conceived': '考案された',
    'concentrated': '集中した',
    'concentrating': '集中する',
    'conception': '概念',
    'concerto': '協奏曲',
    'concerts': 'コンサート',
    'concise': '簡潔な',
    'conclude': '結論を出す',
    'concludes': '結論を出す',
    'concurrent': '同時の',
    'condemn': '非難する',
    'condensed': '凝縮された',
    'cone': '円錐',
    'conferences': '会議',
    'confess': '告白する',
    'confide': '打ち明ける',
    'configuring': '設定する',
    'confined': '閉じ込められた',
    'confirmation': '確認',
    'conflict': '紛争',
    'conformity': '適合',
    'confrontation': '対決',
    'confronting': '直面する',
    'confusing': '混乱させる',
    'congestion': '混雑',
    'congregation': '会衆',
    'congress': '議会',
    'congressional': '議会の',
    'conquer': '征服する',
    'conquest': '征服',
    'conscience': '良心',
    'consciously': '意識的に',
    'consciousness': '意識',
    'consensus': '合意',
    'consent': '同意',
    'consequence': '結果',
    'consequently': '結果として',
    'conservatives': '保守派',
    'considerably': 'かなり',
    'considerate': '思いやりのある',
    'consistency': '一貫性',
    'console': '慰める',
    'consolidated': '統合された',
    'consonants': '子音',
    'conspiracy': '陰謀',
    'constantly': '絶えず',
    'constellation': '星座',
    'constituent': '構成要素',
    'constituted': '構成された',
    'constitution': '憲法',
    'constitutional': '憲法の',
    'constraint': '制約',
    'constraints': '制約',
    'constructed': '建設された',
    'constructing': '建設する',
    'constructive': '建設的な',
    'consult': '相談する',
    'consultants': 'コンサルタント',
    'consulting': '相談する',
    'consume': '消費する',
    'consumed': '消費された',
    'consumerism': '消費主義',
    'consuming': '消費する',
    'consumption': '消費',
    'container': '容器',
    'containers': '容器',
    'contaminated': '汚染された',
    'contemplate': '熟考する',
    'contemporary': '現代の',
    'contempt': '軽蔑',
    'contend': '争う',
    'contenders': '競争者',
    'contentment': '満足',
    'contests': 'コンテスト',
    'continents': '大陸',
    'continual': '絶え間ない',
    'continuity': '連続性',
    'continuous': '連続的な',
    'continuously': '継続的に',
    'contour': '輪郭',
    'contracted': '契約した',
    'contradictory': '矛盾した',
    'contrary': '反対の',
    'contrasting': '対照的な',
    'contributors': '貢献者',
    'controversial': '論争の的となる',
    'controversy': '論争',
    'convened': '招集された',
    'convenience': '便利さ',
    'conventions': '慣習',
    'conversational': '会話の',
    'conversations': '会話',
    'conversion': '変換',
    'converted': '変換された',
    'converting': '変換する',
    'conveying': '伝える',
    'convicted': '有罪判決を受けた',
    'conviction': '確信',
    'convinced': '確信した',
    'convincing': '説得力のある',
    'cookbook': '料理本',
    'cookies': 'クッキー',
    'cooler': 'より涼しい',
    'cooperate': '協力する',
    'cooperation': '協力',
    'cooperative': '協力的な',
    'coordinate': '調整する',
    'coordinated': '調整された',
    'coordination': '調整',
    'cope': '対処する',
    'copper': '銅',
    'coral': 'サンゴ',
    'cord': 'コード',
    'core': '核',
    'cork': 'コルク',
    'corn': 'トウモロコシ',
    'coronation': '戴冠式',
    'corporate': '企業の',
    'corporations': '企業',
    'correctly': '正しく',
    'correlate': '相関する',
    'correlation': '相関',
    'correspond': '対応する',
    'correspondence': '通信',
    'corresponding': '対応する',
    'corridors': '廊下',
    'corruption': '腐敗',
    'cosmopolitan': '国際的な',
    'cosmos': '宇宙',
    'costly': '高価な',
    'costume': '衣装',
    'costumes': '衣装',
    'cottage': 'コテージ',
    'cotton': '綿',
    'couches': 'ソファ',
    'cough': '咳',
    'council': '評議会',
    'counsel': '助言',
    'counseling': 'カウンセリング',
    'counselors': 'カウンセラー',
    'counted': '数えられた',
    'counterpart': '対応物',
    'countless': '無数の',
    'counties': '郡',
    'courage': '勇気',
    'courses': 'コース',
    'courtroom': '法廷',
    'courts': '裁判所',
    'courtyard': '中庭',
    'cousin': 'いとこ',
    'covenant': '契約',
    'covert': '秘密の',
    'cozy': '居心地の良い',
    'craft': '工芸',
    'crafted': '作られた',
    'crafting': '作る',
    'craftsmanship': '職人技',
    'crater': 'クレーター',
    'crave': '切望する',
    'craving': '渇望',
    'crawl': '這う',
    'creativity': '創造性',
    'creators': '創造者',
    'credentials': '資格',
    'credibility': '信頼性',
    'creek': '小川',
    'creeping': '忍び寄る',
    'crescent': '三日月',
    'crest': '頂上',
    'crews': '乗組員',
    'cricket': 'クリケット',
    'crimes': '犯罪',
    'criminal': '犯罪者',
    'criminals': '犯罪者',
    'crippled': '不自由になった',
    'criteria': '基準',
    'critic': '批評家',
    'critically': '批判的に',
    'criticism': '批判',
    'criticized': '批判された',
    'critique': '批評',
    'crop': '作物',
    'crops': '作物',
    'crossroads': '十字路',
    'crown': '王冠',
    'crowned': '戴冠した',
    'crucial': '重要な',
    'crude': '粗野な',
    'cruel': '残酷な',
    'cruelty': '残酷さ',
    'cruise': 'クルーズ',
    'crumbling': '崩れる',
    'crusade': '十字軍',
    'crushed': '粉砕された',
    'crust': '地殻',
    'crystal': '結晶',
    'crystals': '結晶',
    'cube': '立方体',
    'cubic': '立方の',
    'cue': '合図',
    'cuisine': '料理',
    'culminating': '頂点に達する',
    'cultivate': '栽培する',
    'cultivated': '栽培された',
    'cultivation': '栽培',
    'cults': 'カルト',
    'cultural': '文化的な',
    'culturally': '文化的に',
    'cumulative': '累積的な',
    'curated': 'キュレーションされた',
    'curfew': '門限',
    'curiosity': '好奇心',
    'curling': 'カーリング',
    'currencies': '通貨',
    'cursor': 'カーソル',
    'curved': '曲がった',
    'curves': '曲線',
    'cushions': 'クッション',
    'custody': '拘留',
    'customize': 'カスタマイズする',
    'cutting': '切る',
    'cyber': 'サイバー',
    'cycles': 'サイクル',
    'cylinder': '円筒',
    'dairy': '乳製品',
    'dam': 'ダム',
    'damages': '損害',
    'damp': '湿った',
    'dancers': 'ダンサー',
    'dances': 'ダンス',
    'darkened': '暗くなった',
    'dart': 'ダーツ',
    'dashboard': 'ダッシュボード',
    'databases': 'データベース',
    'dawn': '夜明け',
    'daylight': '日光',
    'deadline': '締め切り',
    'deadlock': '行き詰まり',
    'deadly': '致命的な',
    'deaf': '聴覚障害のある',
    'dealers': '販売業者',
    'dealings': '取引',
    'deals': '取引',
    'debatable': '議論の余地がある',
    'debates': '討論',
    'debris': '破片',
    'debts': '借金',
    'decadent': '退廃的な',
    'decay': '腐敗',
    'deceased': '故人',
    'deceit': '欺瞞',
    'deceive': '欺く',
    'deception': '詐欺',
    'deciding': '決定する',
    'decimal': '小数',
    'decisively': '決定的に',
    'declaration': '宣言',
    'declarations': '宣言',
    'declaring': '宣言する',
    'declining': '衰退する',
    'decode': '解読する',
    'decompose': '分解する',
    'decomposition': '分解',
    'decorated': '装飾された',
    'decoration': '装飾',
    'decorations': '装飾',
    'decorative': '装飾的な',
    'decree': '法令',
    'dedicate': '捧げる',
    'dedicated': '献身的な',
    'dedication': '献身',
    'deed': '行為',
    'deeds': '行為',
    'deemed': 'みなされた',
    'deer': '鹿',
    'default': 'デフォルト',
    'defeating': '打ち負かす',
    'defects': '欠陥',
    'defendant': '被告',
    'defender': '擁護者',
    'defenders': '擁護者',
    'defending': '守る',
    'defensive': '防御的な',
    'defiance': '反抗',
    'deficiency': '欠乏',
    'deficit': '赤字',
    'defining': '定義する',
    'definitively': '決定的に',
    'deflation': 'デフレ',
    'deforestation': '森林伐採',
    'defying': '挑む',
    'degradation': '劣化',
    'dehydration': '脱水',
    'deity': '神',
    'delegate': '委任する',
    'delegates': '代表者',
    'delegation': '代表団',
    'deliberate': '意図的な',
    'deliberately': '故意に',
    'delicacy': '珍味',
    'delicate': '繊細な',
    'delicious': 'おいしい',
    'delight': '喜び',
    'delighted': '喜んだ',
    'delightful': '楽しい',
    'delights': '喜び',
    'delinquency': '非行',
    'delivering': '配達する',
    'delta': 'デルタ',
    'demand': '需要',
    'demanding': '要求の厳しい',
    'democracy': '民主主義',
    'demographic': '人口統計の',
    'demolish': '取り壊す',
    'demon': '悪魔',
    'demonstrate': '実証する',
    'demonstrating': '実証する',
    'demonstration': '実演',
    'demonstrations': 'デモ',
    'demoted': '降格された',
    'denial': '否定',
    'denominations': '宗派',
    'dense': '密集した',
    'density': '密度',
    'dentist': '歯科医',
    'deny': '否定する',
    'denying': '否定する',
    'departed': '出発した',
    'departing': '出発する',
    'departments': '部門',
    'departure': '出発',
    'dependencies': '依存',
    'dependency': '依存',
    'depict': '描写する',
    'depicted': '描かれた',
    'depicting': '描写する',
    'depiction': '描写',
    'depictions': '描写',
    'deploy': '配備する',
    'deployed': '配備された',
    'deployment': '配備',
    'deport': '強制送還する',
    'deposit': '預金',
    'deposits': '堆積物',
    'depressed': '落ち込んだ',
    'depression': 'うつ病',
    'deprivation': '剥奪',
    'depth': '深さ',
    'depths': '深さ',
    'deputies': '代理',
    'deputy': '副',
    'derive': '由来する',
    'derived': '派生した',
    'deriving': '導出する',
    'descend': '降りる',
    'descended': '降りた',
    'descending': '降下する',
    'descent': '降下',
    'describing': '記述する',
    'descriptions': '説明',
    'descriptive': '記述的な',
    'desert': '砂漠',
    'deserted': '見捨てられた',
    'deserts': '砂漠',
    'deserved': '値した',
    'deserves': '値する',
    'designated': '指定された',
    'designing': '設計する',
    'desirable': '望ましい',
    'desires': '欲望',
    'desks': '机',
    'desolate': '荒涼とした',
    'despair': '絶望',
    'desperate': '必死の',
    'desperately': '必死に',
    'desperation': '絶望',
    'despise': '軽蔑する',
    'destinations': '目的地',
    'destined': '運命づけられた',
    'destiny': '運命',
    'destitute': '貧困の',
    'destroy': '破壊する',
    'destroying': '破壊する',
    'destructive': '破壊的な',
    'detached': '分離された',
    'detachment': '分離',
    'detained': '拘束された',
    'detecting': '検出する',
    'detective': '探偵',
    'detention': '拘留',
    'deter': '抑止する',
    'deteriorate': '悪化する',
    'deterioration': '劣化',
    'determination': '決意',
    'determined': '決意した',
    'determining': '決定する',
    'deterrence': '抑止',
    'detrimental': '有害な',
    'devastated': '荒廃した',
    'devastating': '壊滅的な',
    'devastation': '破壊',
    'devising': '考案する',
    'devote': '捧げる',
    'devoted': '献身的な',
    'devotion': '献身',
    'devour': '貪り食う',
    'diabetes': '糖尿病',
    'diagnose': '診断する',
    'diagnosed': '診断された',
    'diagonal': '対角線',
    'diagram': '図',
    'diagrams': '図',
    'dialect': '方言',
    'dialogue': '対話',
    'diameter': '直径',
    'diamond': 'ダイヤモンド',
    'diamonds': 'ダイヤモンド',
    'diary': '日記',
    'dice': 'サイコロ',
    'dictated': '口述した',
    'dictator': '独裁者',
    'dictionaries': '辞書',
    'dietary': '食事の',
    'differed': '異なった',
    'differential': '差分',
    'differing': '異なる',
    'differs': '異なる',
    'digest': '消化する',
    'digestion': '消化',
    'digestive': '消化の',
    'digital': 'デジタル',
    'digitally': 'デジタルで',
    'dignity': '尊厳',
    'dilemma': 'ジレンマ',
    'diligence': '勤勉',
    'diligent': '勤勉な',
    'dilute': '希釈する',
    'dimensional': '次元の',
    'dimensions': '寸法',
    'diminish': '減少する',
    'diminished': '減少した',
    'diminishing': '減少する',
    'dine': '食事する',
    'dining': '食事',
    'dinosaur': '恐竜',
    'dinosaurs': '恐竜',
    'dioxide': '二酸化物',
    'diploma': '卒業証書',
    'diplomacy': '外交',
    'diplomatic': '外交的な',
    'dire': '悲惨な',
    'directing': '指示する',
    'directive': '指令',
    'directories': 'ディレクトリ',
    'directory': 'ディレクトリ',
    'dirt': '汚れ',
    'disabilities': '障害',
    'disability': '障害',
    'disable': '無効にする',
    'disabled': '障害のある',
    'disadvantage': '不利',
    'disadvantaged': '不利な立場の',
    'disagreed': '同意しなかった',
    'disagreements': '意見の相違',
    'disappear': '消える',
    'disappearance': '失踪',
    'disappeared': '消えた',
    'disappearing': '消える',
    'disappoint': '失望させる',
    'disappointed': '失望した',
    'disappointing': '失望させる',
    'disappointment': '失望',
    'disapproval': '不承認',
    'disarmament': '軍縮',
    'disasters': '災害',
    'disastrous': '悲惨な',
    'disbelief': '不信',
    'disc': 'ディスク',
    'discard': '捨てる',
    'discarded': '捨てられた',
    'discern': '識別する',
    'discharge': '放出',
    'disciplinary': '懲戒の',
    'discipline': '規律',
    'disclose': '開示する',
    'disclosure': '開示',
    'discomfort': '不快',
    'disconnect': '切断する',
    'disconnected': '切断された',
    'discontent': '不満',
    'discontinue': '中止する',
    'discount': '割引',
    'discouraged': '落胆した',
    'discourse': '談話',
    'discovering': '発見する',
    'discoveries': '発見',
    'discreet': '慎重な',
    'discrepancies': '不一致',
    'discrete': '離散的な',
    'discretion': '裁量',
    'discriminate': '差別する',
    'discriminated': '差別された',
    'discrimination': '差別',
    'discussions': '議論',
    'disdain': '軽蔑',
    'diseases': '病気',
    'disembark': '下船する',
    'disguise': '変装',
    'disguised': '変装した',
    'disgust': '嫌悪',
    'disgusted': '嫌悪した',
    'disgusting': '嫌な',
    'dishes': '料理',
    'dishonest': '不正直な',
    'dishonesty': '不正直',
    'dishwasher': '食器洗い機',
    'disintegration': '崩壊',
    'dislike': '嫌う',
    'dismal': '陰鬱な',
    'dismantle': '解体する',
    'dismay': '落胆',
    'dismayed': '落胆した',
    'dismiss': '却下する',
    'dismissed': '却下された',
    'dismissing': '却下する',
    'dismissive': '軽視する',
    'disobedience': '不服従',
    'disorder': '障害',
    'disparities': '格差',
    'disparity': '格差',
    'dispatch': '派遣',
    'dispatched': '派遣された',
    'dispel': '払拭する',
    'dispensary': '診療所',
    'disperse': '分散する',
    'dispersed': '分散した',
    'displace': '置き換える',
    'displaced': '避難した',
    'displacement': '避難',
    'displaying': '表示する',
    'displays': 'ディスプレイ',
    'disposal': '処分',
    'dispose': '処分する',
    'disposed': '処分された',
    'disposing': '処分する',
    'disproportionate': '不釣り合いな',
    'disprove': '反証する',
    'dispute': '論争',
    'disputed': '論争された',
    'disputes': '論争',
    'disregard': '無視する',
    'disrupt': '混乱させる',
    'disrupted': '混乱した',
    'disrupting': '混乱させる',
    'disruption': '混乱',
    'disruptive': '破壊的な',
    'dissatisfaction': '不満',
    'disseminate': '普及させる',
    'dissent': '異議',
    'dissertation': '論文',
    'dissolve': '溶かす',
    'dissolved': '溶解した',
    'dissonance': '不協和音',
    'distances': '距離',
    'distant': '遠い',
    'distilled': '蒸留された',
    'distinct': '明確な',
    'distinction': '区別',
    'distinctive': '独特の',
    'distinctly': '明確に',
    'distinguish': '区別する',
    'distinguished': '著名な',
    'distinguishing': '区別する',
    'distort': '歪める',
    'distorted': '歪んだ',
    'distortion': '歪み',
    'distract': '気を散らす',
    'distracted': '気が散った',
    'distraction': '気晴らし',
    'distractions': '気晴らし',
    'distress': '苦悩',
    'distressed': '苦しんでいる',
    'distressing': '苦痛な',
    'distribute': '配布する',
    'distributed': '分散された',
    'distributing': '配布する',
    'distribution': '分布',
    'distributors': '販売業者',
    'districts': '地区',
    'distrust': '不信',
    'disturb': '邪魔する',
    'disturbance': '妨害',
    'disturbed': '動揺した',
    'disturbing': '不穏な',
    'ditch': '溝',
    'divergent': '発散する',
    'diverse': '多様な',
    'diversify': '多様化する',
    'diversion': '転換',
    'diversity': '多様性',
    'divert': '転換する',
    'diverted': '転換された',
    'divide': '分割する',
    'dividend': '配当',
    'dividing': '分割する',
    'divine': '神聖な',
    'divinity': '神性',
    'divorce': '離婚',
    'divorced': '離婚した',
    'dizziness': 'めまい',
    'dizzy': 'めまいがする',
    'dock': 'ドック',
    'docking': '接岸する',
    'doctrine': '教義',
    'documented': '文書化された',
    'documenting': '文書化する',
    'dodge': 'かわす',
    'dome': 'ドーム',
    'domes': 'ドーム',
    'domestic': '国内の',
    'domestically': '国内で',
    'domestication': '家畜化',
    'dominance': '支配',
    'dominant': '支配的な',
    'dominate': '支配する',
    'dominated': '支配された',
    'dominating': '支配する',
    'domination': '支配',
    'dominion': '支配権',
    'donate': '寄付する',
    'donated': '寄付された',
    'donating': '寄付する',
    'donations': '寄付',
    'donor': '寄贈者',
    'donors': '寄贈者',
    'doom': '運命',
    'doomed': '運命づけられた',
    'doorway': '出入口',
    'dormant': '休眠中の',
    'dosage': '投与量',
    'doses': '用量',
    'dots': '点',
    'doubled': '倍になった',
    'doubling': '倍増する',
    'doubts': '疑い',
    'dough': '生地',
    'dove': 'ハト',
    'downfall': '崩壊',
    'downside': '欠点',
    'downstream': '下流',
    'downtown': '繁華街',
    'downward': '下向きの',
    'doze': 'うたた寝する',
    'dozens': '何十も',
    'draft': '草案',
    'drafted': '起草された',
    'drafting': '起草する',
    'drafts': '草案',
    'dragged': '引きずられた',
    'dragging': '引きずる',
    'dragon': '竜',
    'dragons': '竜',
    'drain': '排水する',
    'drainage': '排水',
    'drained': '排水された',
    'draining': '排水する',
    'dramas': 'ドラマ',
    'dramatic': '劇的な',
    'dramatically': '劇的に',
    'drank': '飲んだ',
    'drastic': '抜本的な',
    'drastically': '大幅に',
    'draught': '通風',
    'drawback': '欠点',
    'drawbacks': '欠点',
    'drawer': '引き出し',
    'drawings': '図面',
    'dread': '恐怖',
    'dreadful': '恐ろしい',
    'dreamed': '夢見た',
    'dreaming': '夢見る',
    'dreams': '夢',
    'drenched': 'ずぶ濡れの',
    'dressed': '服を着た',
    'dressing': 'ドレッシング',
    'drew': '描いた',
    'dried': '乾燥した',
    'drifted': '漂った',
    'drifting': '漂う',
    'drills': '訓練',
    'drip': '滴る',
    'dripping': '滴る',
    'driven': '駆り立てられた',
    'drivers': '運転手',
    'drives': '推進する',
    'drone': 'ドローン',
    'drones': 'ドローン',
    'drool': 'よだれ',
    'droop': '垂れ下がる',
    'dropping': '落とす',
    'drought': '干ばつ',
    'droughts': '干ばつ',
    'drove': '運転した',
    'drowned': '溺死した',
    'drowning': '溺れる',
    'drowsy': '眠い',
    'drum': 'ドラム',
    'drummer': 'ドラマー',
    'drums': 'ドラム',
    'drunk': '酔った',
    'drying': '乾燥',
    'dual': '二重の',
    'dubbed': '吹き替えられた',
    'duck': 'アヒル',
    'ducks': 'アヒル',
    'duel': '決闘',
    'duke': '公爵',
    'dull': '鈍い',
    'dumb': '愚かな',
    'dump': '捨てる',
    'dumped': '捨てられた',
    'dumping': '投棄',
    'dunes': '砂丘',
    'dungeon': '地下牢',
    'duplicate': '複製',
    'duplicated': '複製された',
    'durability': '耐久性',
    'durable': '耐久性のある',
    'duration': '期間',
    'dusk': '夕暮れ',
    'dust': 'ほこり',
    'dusty': 'ほこりっぽい',
    'duties': '義務',
    'duty': '義務',
    'dwell': '住む',
    'dwellers': '住人',
    'dwelling': '住居',
    'dwellings': '住居',
}

def update_dictionary():
    """辞書を更新"""
    dict_path = Path('public/data/dictionaries/reading-passages-dictionary.json')
    with open(dict_path, 'r', encoding='utf-8') as f:
        dictionary = json.load(f)
    
    updated_count = 0
    for word, meaning in PART1_DICT.items():
        if word in dictionary:
            if dictionary[word].get('meaning') == '(要確認)':
                dictionary[word]['meaning'] = meaning
                dictionary[word]['source'] = 'manual_1x_part1'
                updated_count += 1
    
    with open(dict_path, 'w', encoding='utf-8') as f:
        json.dump(dictionary, f, ensure_ascii=False, indent=2)
    
    return updated_count

def update_passage_files():
    """パッセージファイルを更新"""
    passage_files = [
        'advanced-environmental-issues.json',
        'advanced-family-gathering.json',
        'advanced-health-statistics.json',
        'advanced-historical-figures.json',
        'advanced-international-exchange.json',
        'advanced-school-festival.json',
        'advanced-summer-vacation-stories.json',
        'advanced-technology-future.json',
        'beginner-cafe-menu.json',
        'beginner-conversation-daily.json',
        'beginner-supermarket-shopping.json',
        'beginner-weather-seasons.json',
        'beginner-wildlife-park-guide.json',
        'intermediate-career-day.json',
        'intermediate-community-events.json',
        'intermediate-exchange-student-australia-full.json',
        'intermediate-exchange-student-australia.json',
        'intermediate-homestay-america.json',
        'intermediate-hospital-visit.json',
        'intermediate-school-events-year.json',
        'intermediate-school-news.json',
        'intermediate-science-museum.json'
    ]
    
    files_updated = 0
    total_updates = 0
    
    for passage_file in passage_files:
        passage_path = Path(f'public/data/passages-phrase-learning/{passage_file}')
        with open(passage_path, 'r', encoding='utf-8') as f:
            data = json.load(f)
        
        file_updates = 0
        for phrase in data.get('phrases', []):
            for segment in phrase.get('segments', []):
                lemma = segment.get('lemma', '')
                if lemma in PART1_DICT:
                    if segment.get('meaning') == '(要確認)':
                        segment['meaning'] = PART1_DICT[lemma]
                        file_updates += 1
        
        if file_updates > 0:
            with open(passage_path, 'w', encoding='utf-8') as f:
                json.dump(data, f, ensure_ascii=False, indent=2)
            print(f"  ✅ {passage_file}: {file_updates}箇所")
            files_updated += 1
            total_updates += file_updates
    
    return files_updated, total_updates

def analyze_remaining():
    """残りの(要確認)を分析"""
    dict_path = Path('public/data/dictionaries/reading-passages-dictionary.json')
    with open(dict_path, 'r', encoding='utf-8') as f:
        dictionary = json.load(f)
    
    confirmed = sum(1 for entry in dictionary.values() if entry.get('meaning') != '(要確認)')
    unconfirmed = sum(1 for entry in dictionary.values() if entry.get('meaning') == '(要確認)')
    total = len(dictionary)
    percentage = (confirmed / total * 100) if total > 0 else 0
    
    print(f"\n📊 辞書の状態:")
    print(f"  総単語数: {total}語")
    print(f"  意味確定: {confirmed}語 ({percentage:.1f}%)")
    print(f"  (要確認): {unconfirmed}語 ({100-percentage:.1f}%)")
    
    target = int(total * 0.95)
    shortage = target - confirmed
    achievement = (confirmed / target * 100) if target > 0 else 0
    
    print(f"\n🎯 目標達成状況:")
    print(f"  目標(95%): {target}語")
    if shortage > 0:
        print(f"  不足: {shortage}語")
        print(f"  達成率: {achievement:.1f}%")
    else:
        print(f"  🎉 目標達成！ 超過: {-shortage}語")
        print(f"  達成率: {achievement:.1f}%")

def main():
    print("=" * 120)
    print("1回出現単語 Part 1/4 (a-d)")
    print("=" * 120)
    print(f"\n対象: {len(PART1_DICT)}語\n")
    
    dict_count = update_dictionary()
    print(f"📚 辞書更新: {dict_count}語\n")
    
    files_count, updates_count = update_passage_files()
    print(f"\n📄 パッセージ更新: {files_count}ファイル, {updates_count}箇所")
    
    analyze_remaining()
    
    print(f"\n{'=' * 120}")
    print(f"✅ 完了: 辞書{dict_count}語、パッセージ{updates_count}箇所を更新")
    print(f"{'=' * 120}")

if __name__ == '__main__':
    main()
