#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Grade 1 Units 5-9 一括生成スクリプト
Unit 5: 助動詞can
Unit 6: 現在進行形
Unit 7: 命令文
Unit 8: 過去形（規則動詞）
Unit 9: 過去形（不規則動詞）
"""

import json
import os

# Unit 5: 助動詞can（60問）
def create_unit5():
    return [
        # 穴埋め15問
        {"id": "g1-u5-fib-001", "type": "fillInBlank", "japanese": "私は泳げます", "sentence": "I ____ swim.", "choices": ["can", "cannot", "am", "do"], "correctAnswer": "can", "difficulty": "beginner", "explanation": "「できる」はcanを使う。肯定文ではI canの形。", "hint": "「できる」を表す助動詞"},
        {"id": "g1-u5-fib-002", "type": "fillInBlank", "japanese": "彼は英語を話せます", "sentence": "He ____ speak English.", "choices": ["can", "cans", "is", "does"], "correctAnswer": "can", "difficulty": "beginner", "explanation": "canは主語に関わらず形が変わらない。三人称単数でもcanのまま。", "hint": "canは変化しない"},
        {"id": "g1-u5-fib-003", "type": "fillInBlank", "japanese": "あなたは走れますか", "sentence": "____ you run?", "choices": ["Can", "Do", "Are", "Is"], "correctAnswer": "Can", "difficulty": "beginner", "explanation": "「できますか」の疑問文はCanを文頭に置く。Can you~?の形。", "hint": "疑問文はcanを文頭に"},
        {"id": "g1-u5-fib-004", "type": "fillInBlank", "japanese": "彼女はピアノを弾けません", "sentence": "She ____ play the piano.", "choices": ["cannot", "can", "does not", "is not"], "correctAnswer": "cannot", "difficulty": "beginner", "explanation": "「できない」はcannotまたはcan't。notを付けて否定形にする。", "hint": "canの否定形"},
        {"id": "g1-u5-fib-005", "type": "fillInBlank", "japanese": "私たちは料理ができます", "sentence": "We ____ cook.", "choices": ["can", "cans", "are", "do"], "correctAnswer": "can", "difficulty": "beginner", "explanation": "canは主語がweでも形が変わらない。助動詞の後ろは原形動詞。", "hint": "canは変化しない"},
        {"id": "g1-u5-fib-006", "type": "fillInBlank", "japanese": "あなたは自転車に乗れますか", "sentence": "Can you ____ a bike?", "choices": ["ride", "rides", "riding", "rode"], "correctAnswer": "ride", "difficulty": "beginner", "explanation": "助動詞canの後ろは必ず動詞の原形。rideを使う。", "hint": "canの後ろは原形"},
        {"id": "g1-u5-fib-007", "type": "fillInBlank", "japanese": "彼はサッカーができます", "sentence": "He ____ play soccer.", "choices": ["can", "is", "does", "has"], "correctAnswer": "can", "difficulty": "beginner", "explanation": "「できる」はcanを使う。三人称単数でもcanのまま変化しない。", "hint": "「できる」を表す助動詞"},
        {"id": "g1-u5-fib-008", "type": "fillInBlank", "japanese": "私は速く走れません", "sentence": "I ____ run fast.", "choices": ["cannot", "can", "do not", "am not"], "correctAnswer": "cannot", "difficulty": "beginner", "explanation": "「できない」はcannotまたはcan't。canにnotを付ける。", "hint": "canの否定形"},
        {"id": "g1-u5-fib-009", "type": "fillInBlank", "japanese": "彼女は歌えますか", "sentence": "____ she sing?", "choices": ["Can", "Does", "Is", "Has"], "correctAnswer": "Can", "difficulty": "beginner", "explanation": "「できますか」の疑問文はCanを文頭に置く。Can she~?の形。", "hint": "疑問文はcanを文頭に"},
        {"id": "g1-u5-fib-010", "type": "fillInBlank", "japanese": "彼らは日本語を読めます", "sentence": "They can ____ Japanese.", "choices": ["read", "reads", "reading", "to read"], "correctAnswer": "read", "difficulty": "beginner", "explanation": "canの後ろは必ず動詞の原形。readを使う。", "hint": "canの後ろは原形"},
        {"id": "g1-u5-fib-011", "type": "fillInBlank", "japanese": "あなたは泳げますか", "sentence": "Can you ____?", "choices": ["swim", "swims", "swimming", "swam"], "correctAnswer": "swim", "difficulty": "beginner", "explanation": "canの後ろは必ず動詞の原形。swimを使う。", "hint": "canの後ろは原形"},
        {"id": "g1-u5-fib-012", "type": "fillInBlank", "japanese": "私はギターを弾けません", "sentence": "I ____ play the guitar.", "choices": ["cannot", "can", "do not", "am not"], "correctAnswer": "cannot", "difficulty": "beginner", "explanation": "「できない」はcannotまたはcan't。否定形はcanにnotを付ける。", "hint": "canの否定形"},
        {"id": "g1-u5-fib-013", "type": "fillInBlank", "japanese": "彼は速く走れます", "sentence": "He can run ____.", "choices": ["fast", "quick", "fastly", "quickly"], "correctAnswer": "fast", "difficulty": "beginner", "explanation": "「速く」は副詞fast。fastlyという形はない。", "hint": "「速く」はfast"},
        {"id": "g1-u5-fib-014", "type": "fillInBlank", "japanese": "あなたは日本語が話せますか", "sentence": "Can you ____ Japanese?", "choices": ["speak", "speaks", "speaking", "spoke"], "correctAnswer": "speak", "difficulty": "beginner", "explanation": "canの後ろは必ず動詞の原形。speakを使う。", "hint": "canの後ろは原形"},
        {"id": "g1-u5-fib-015", "type": "fillInBlank", "japanese": "私たちはテニスができません", "sentence": "We ____ play tennis.", "choices": ["cannot", "can", "do not", "are not"], "correctAnswer": "cannot", "difficulty": "beginner", "explanation": "「できない」はcannotまたはcan't。canにnotを付ける。", "hint": "canの否定形"},
        
        # 並び替え15問
        {"id": "g1-u5-so-001", "type": "sentenceOrdering", "japanese": "私は泳げます", "words": ["I", "can", "swim", "."], "correctAnswer": "I can swim.", "difficulty": "beginner", "explanation": "肯定文は「主語 + can + 動詞原形」の語順。", "hint": "主語 + can + 動詞原形"},
        {"id": "g1-u5-so-002", "type": "sentenceOrdering", "japanese": "あなたは走れますか", "words": ["Can", "you", "run", "?"], "correctAnswer": "Can you run?", "difficulty": "beginner", "explanation": "疑問文は「Can + 主語 + 動詞原形?」の語順。", "hint": "Can + 主語 + 動詞原形"},
        {"id": "g1-u5-so-003", "type": "sentenceOrdering", "japanese": "彼は歌えません", "words": ["He", "cannot", "sing", "."], "correctAnswer": "He cannot sing.", "difficulty": "beginner", "explanation": "否定文は「主語 + cannot + 動詞原形」の語順。", "hint": "主語 + cannot + 動詞原形"},
        {"id": "g1-u5-so-004", "type": "sentenceOrdering", "japanese": "彼女はピアノを弾けます", "words": ["She", "can", "play", "the", "piano", "."], "correctAnswer": "She can play the piano.", "difficulty": "beginner", "explanation": "「楽器を弾く」はplay the + 楽器名。canの後ろは原形動詞。", "hint": "play the + 楽器名"},
        {"id": "g1-u5-so-005", "type": "sentenceOrdering", "japanese": "あなたは英語を話せますか", "words": ["Can", "you", "speak", "English", "?"], "correctAnswer": "Can you speak English?", "difficulty": "beginner", "explanation": "疑問文は「Can + 主語 + 動詞原形 + 目的語?」の語順。", "hint": "Can + 主語 + 動詞原形"},
        {"id": "g1-u5-so-006", "type": "sentenceOrdering", "japanese": "彼らはサッカーができます", "words": ["They", "can", "play", "soccer", "."], "correctAnswer": "They can play soccer.", "difficulty": "beginner", "explanation": "「スポーツをする」はplay + スポーツ名（無冠詞）。", "hint": "play + スポーツ名"},
        {"id": "g1-u5-so-007", "type": "sentenceOrdering", "japanese": "私は速く走れません", "words": ["I", "cannot", "run", "fast", "."], "correctAnswer": "I cannot run fast.", "difficulty": "beginner", "explanation": "否定文は「主語 + cannot + 動詞原形 + 副詞」の語順。", "hint": "主語 + cannot + 動詞 + 副詞"},
        {"id": "g1-u5-so-008", "type": "sentenceOrdering", "japanese": "彼は泳げますか", "words": ["Can", "he", "swim", "?"], "correctAnswer": "Can he swim?", "difficulty": "beginner", "explanation": "疑問文は「Can + 主語 + 動詞原形?」の語順。三人称単数でもcanは変化しない。", "hint": "Can + 主語 + 動詞原形"},
        {"id": "g1-u5-so-009", "type": "sentenceOrdering", "japanese": "私たちは料理ができます", "words": ["We", "can", "cook", "."], "correctAnswer": "We can cook.", "difficulty": "beginner", "explanation": "肯定文は「主語 + can + 動詞原形」の語順。", "hint": "主語 + can + 動詞原形"},
        {"id": "g1-u5-so-010", "type": "sentenceOrdering", "japanese": "彼女は踊れません", "words": ["She", "cannot", "dance", "."], "correctAnswer": "She cannot dance.", "difficulty": "beginner", "explanation": "否定文は「主語 + cannot + 動詞原形」の語順。", "hint": "主語 + cannot + 動詞原形"},
        {"id": "g1-u5-so-011", "type": "sentenceOrdering", "japanese": "あなたは自転車に乗れますか", "words": ["Can", "you", "ride", "a", "bike", "?"], "correctAnswer": "Can you ride a bike?", "difficulty": "beginner", "explanation": "「自転車に乗る」はride a bike。疑問文はCanを文頭に。", "hint": "ride a bike"},
        {"id": "g1-u5-so-012", "type": "sentenceOrdering", "japanese": "彼は日本語を読めます", "words": ["He", "can", "read", "Japanese", "."], "correctAnswer": "He can read Japanese.", "difficulty": "beginner", "explanation": "肯定文は「主語 + can + 動詞原形 + 目的語」の語順。", "hint": "主語 + can + 動詞 + 目的語"},
        {"id": "g1-u5-so-013", "type": "sentenceOrdering", "japanese": "私はギターを弾けません", "words": ["I", "cannot", "play", "the", "guitar", "."], "correctAnswer": "I cannot play the guitar.", "difficulty": "beginner", "explanation": "「楽器を弾く」はplay the + 楽器名。否定文はcannotを使う。", "hint": "play the + 楽器名"},
        {"id": "g1-u5-so-014", "type": "sentenceOrdering", "japanese": "彼女は歌えますか", "words": ["Can", "she", "sing", "?"], "correctAnswer": "Can she sing?", "difficulty": "beginner", "explanation": "疑問文は「Can + 主語 + 動詞原形?」の語順。", "hint": "Can + 主語 + 動詞原形"},
        {"id": "g1-u5-so-015", "type": "sentenceOrdering", "japanese": "彼らはスキーができます", "words": ["They", "can", "ski", "."], "correctAnswer": "They can ski.", "difficulty": "beginner", "explanation": "肯定文は「主語 + can + 動詞原形」の語順。", "hint": "主語 + can + 動詞原形"},
        
        # 言い換え15問
        {"id": "g1-u5-para-001", "type": "paraphrase", "japanese": "私は泳げます", "originalSentence": "I can swim.", "choices": ["I am able to swim.", "I like swimming.", "I am swimming.", "I swam."], "correctAnswer": "I am able to swim.", "difficulty": "beginner", "explanation": "canは「be able to」で言い換えられる。どちらも「できる」の意味。", "hint": "be able to = can"},
        {"id": "g1-u5-para-002", "type": "paraphrase", "japanese": "彼は英語を話せます", "originalSentence": "He can speak English.", "choices": ["He is able to speak English.", "He speaks English well.", "He is speaking English.", "He spoke English."], "correctAnswer": "He is able to speak English.", "difficulty": "beginner", "explanation": "canは「be able to」で言い換えられる。能力を表す表現。", "hint": "be able to = can"},
        {"id": "g1-u5-para-003", "type": "paraphrase", "japanese": "あなたは走れますか", "originalSentence": "Can you run?", "choices": ["Are you able to run?", "Do you run?", "Are you running?", "Did you run?"], "correctAnswer": "Are you able to run?", "difficulty": "beginner", "explanation": "Can you~?は「Are you able to~?」で言い換えられる。", "hint": "Are you able to = Can you"},
        {"id": "g1-u5-para-004", "type": "paraphrase", "japanese": "彼女はピアノを弾けません", "originalSentence": "She cannot play the piano.", "choices": ["She is not able to play the piano.", "She doesn't play the piano.", "She isn't playing the piano.", "She didn't play the piano."], "correctAnswer": "She is not able to play the piano.", "difficulty": "beginner", "explanation": "cannotは「be not able to」で言い換えられる。", "hint": "be not able to = cannot"},
        {"id": "g1-u5-para-005", "type": "paraphrase", "japanese": "私は料理ができます", "originalSentence": "I can cook.", "choices": ["I am able to cook.", "I like cooking.", "I am cooking.", "I cooked."], "correctAnswer": "I am able to cook.", "difficulty": "beginner", "explanation": "canは「be able to」で言い換えられる。能力を表す。", "hint": "be able to = can"},
        {"id": "g1-u5-para-006", "type": "paraphrase", "japanese": "彼はサッカーができます", "originalSentence": "He can play soccer.", "choices": ["He knows how to play soccer.", "He plays soccer.", "He is playing soccer.", "He played soccer."], "correctAnswer": "He knows how to play soccer.", "difficulty": "intermediate", "explanation": "canは「know how to」（〜の仕方を知っている）でも表現できる。", "hint": "know how to = can"},
        {"id": "g1-u5-para-007", "type": "paraphrase", "japanese": "あなたは自転車に乗れますか", "originalSentence": "Can you ride a bike?", "choices": ["Do you know how to ride a bike?", "Do you ride a bike?", "Are you riding a bike?", "Did you ride a bike?"], "correctAnswer": "Do you know how to ride a bike?", "difficulty": "intermediate", "explanation": "Can you~?は「Do you know how to~?」でも表現できる。", "hint": "know how to = can"},
        {"id": "g1-u5-para-008", "type": "paraphrase", "japanese": "私は泳げません", "originalSentence": "I cannot swim.", "choices": ["I am not able to swim.", "I don't swim.", "I am not swimming.", "I didn't swim."], "correctAnswer": "I am not able to swim.", "difficulty": "beginner", "explanation": "cannotは「be not able to」で言い換えられる。", "hint": "be not able to = cannot"},
        {"id": "g1-u5-para-009", "type": "paraphrase", "japanese": "彼女は歌えます", "originalSentence": "She can sing.", "choices": ["She is able to sing.", "She sings.", "She is singing.", "She sang."], "correctAnswer": "She is able to sing.", "difficulty": "beginner", "explanation": "canは「be able to」で言い換えられる。", "hint": "be able to = can"},
        {"id": "g1-u5-para-010", "type": "paraphrase", "japanese": "彼らは日本語を読めます", "originalSentence": "They can read Japanese.", "choices": ["They are able to read Japanese.", "They read Japanese.", "They are reading Japanese.", "They read Japanese yesterday."], "correctAnswer": "They are able to read Japanese.", "difficulty": "beginner", "explanation": "canは「be able to」で言い換えられる。", "hint": "be able to = can"},
        {"id": "g1-u5-para-011", "type": "paraphrase", "japanese": "あなたは英語を話せますか", "originalSentence": "Can you speak English?", "choices": ["Are you able to speak English?", "Do you speak English?", "Are you speaking English?", "Did you speak English?"], "correctAnswer": "Are you able to speak English?", "difficulty": "beginner", "explanation": "Can you~?は「Are you able to~?」で言い換えられる。", "hint": "Are you able to = Can you"},
        {"id": "g1-u5-para-012", "type": "paraphrase", "japanese": "彼はギターを弾けません", "originalSentence": "He cannot play the guitar.", "choices": ["He is not able to play the guitar.", "He doesn't play the guitar.", "He isn't playing the guitar.", "He didn't play the guitar."], "correctAnswer": "He is not able to play the guitar.", "difficulty": "beginner", "explanation": "cannotは「be not able to」で言い換えられる。", "hint": "be not able to = cannot"},
        {"id": "g1-u5-para-013", "type": "paraphrase", "japanese": "私は速く走れます", "originalSentence": "I can run fast.", "choices": ["I am able to run fast.", "I run fast.", "I am running fast.", "I ran fast."], "correctAnswer": "I am able to run fast.", "difficulty": "beginner", "explanation": "canは「be able to」で言い換えられる。副詞も同じ位置に置く。", "hint": "be able to = can"},
        {"id": "g1-u5-para-014", "type": "paraphrase", "japanese": "彼女は踊れますか", "originalSentence": "Can she dance?", "choices": ["Is she able to dance?", "Does she dance?", "Is she dancing?", "Did she dance?"], "correctAnswer": "Is she able to dance?", "difficulty": "beginner", "explanation": "Can she~?は「Is she able to~?」で言い換えられる。", "hint": "Is she able to = Can she"},
        {"id": "g1-u5-para-015", "type": "paraphrase", "japanese": "彼らはスキーができます", "originalSentence": "They can ski.", "choices": ["They are able to ski.", "They ski.", "They are skiing.", "They skied."], "correctAnswer": "They are able to ski.", "difficulty": "beginner", "explanation": "canは「be able to」で言い換えられる。", "hint": "be able to = can"},
        
        # 動詞変化10問
        {"id": "g1-u5-vf-001", "type": "verbForm", "japanese": "彼女は泳げますか", "sentence": "____ she swim?", "choices": ["Can", "Does", "Is", "Has"], "correctAnswer": "Can", "difficulty": "beginner", "explanation": "「できますか」の疑問文はCanを使う。Canを文頭に置く。", "hint": "「できますか」はCan"},
        {"id": "g1-u5-vf-002", "type": "verbForm", "japanese": "私は走れます", "sentence": "I ____ run.", "choices": ["can", "do", "am", "have"], "correctAnswer": "can", "difficulty": "beginner", "explanation": "「できる」はcanを使う。肯定文の形。", "hint": "「できる」はcan"},
        {"id": "g1-u5-vf-003", "type": "verbForm", "japanese": "彼は歌えません", "sentence": "He ____ sing.", "choices": ["cannot", "does not", "is not", "has not"], "correctAnswer": "cannot", "difficulty": "beginner", "explanation": "「できない」はcannotまたはcan't。canにnotを付ける。", "hint": "canの否定形"},
        {"id": "g1-u5-vf-004", "type": "verbForm", "japanese": "あなたは泳げますか", "sentence": "Can you ____?", "choices": ["swim", "swims", "swimming", "swam"], "correctAnswer": "swim", "difficulty": "beginner", "explanation": "canの後ろは必ず動詞の原形。swimを使う。", "hint": "canの後ろは原形"},
        {"id": "g1-u5-vf-005", "type": "verbForm", "japanese": "彼女はピアノを弾けます", "sentence": "She can ____ the piano.", "choices": ["play", "plays", "playing", "played"], "correctAnswer": "play", "difficulty": "beginner", "explanation": "canの後ろは必ず動詞の原形。playを使う。", "hint": "canの後ろは原形"},
        {"id": "g1-u5-vf-006", "type": "verbForm", "japanese": "彼らは英語を話せますか", "sentence": "____ they speak English?", "choices": ["Can", "Do", "Are", "Have"], "correctAnswer": "Can", "difficulty": "beginner", "explanation": "「できますか」の疑問文はCanを使う。Canを文頭に置く。", "hint": "「できますか」はCan"},
        {"id": "g1-u5-vf-007", "type": "verbForm", "japanese": "私は料理ができません", "sentence": "I ____ cook.", "choices": ["cannot", "do not", "am not", "have not"], "correctAnswer": "cannot", "difficulty": "beginner", "explanation": "「できない」はcannotまたはcan't。否定形。", "hint": "canの否定形"},
        {"id": "g1-u5-vf-008", "type": "verbForm", "japanese": "彼は走れますか", "sentence": "Can he ____?", "choices": ["run", "runs", "running", "ran"], "correctAnswer": "run", "difficulty": "beginner", "explanation": "canの後ろは必ず動詞の原形。runを使う。", "hint": "canの後ろは原形"},
        {"id": "g1-u5-vf-009", "type": "verbForm", "japanese": "彼女は歌えますか", "sentence": "____ she sing?", "choices": ["Can", "Does", "Is", "Has"], "correctAnswer": "Can", "difficulty": "beginner", "explanation": "「できますか」の疑問文はCanを使う。", "hint": "「できますか」はCan"},
        {"id": "g1-u5-vf-010", "type": "verbForm", "japanese": "私たちはテニスができます", "sentence": "We can ____ tennis.", "choices": ["play", "plays", "playing", "played"], "correctAnswer": "play", "difficulty": "beginner", "explanation": "canの後ろは必ず動詞の原形。playを使う。", "hint": "canの後ろは原形"},
        
        # 日常英会話5問
        {"id": "g1-u5-conv-001", "type": "conversation", "japanese": "友達に「泳げる？」と聞きたい", "scene": "友達との会話", "question": "How can I ask if my friend can swim?", "choices": ["Can you swim?", "Do you swim?", "Are you swimming?", "Did you swim?"], "correctAnswer": "Can you swim?", "difficulty": "beginner", "explanation": "「〜できる？」はCan you~?で表す。能力を尋ねる最も基本的な表現。", "hint": "Can you~?で能力を尋ねる"},
        {"id": "g1-u5-conv-002", "type": "conversation", "japanese": "「ピアノ弾けるよ」と答えたい", "scene": "自己紹介", "question": "I can play the piano.", "choices": ["Yes, I can.", "Yes, I do.", "Yes, I am.", "Yes, I did."], "correctAnswer": "Yes, I can.", "difficulty": "beginner", "explanation": "Can you~?の質問にはYes, I can.またはNo, I cannot.で答える。", "hint": "Canで聞かれたらcanで答える"},
        {"id": "g1-u5-conv-003", "type": "conversation", "japanese": "「料理できない」と伝えたい", "scene": "友達との会話", "question": "How can I say I cannot cook?", "choices": ["I cannot cook.", "I don't cook.", "I am not cooking.", "I didn't cook."], "correctAnswer": "I cannot cook.", "difficulty": "beginner", "explanation": "「できない」はI cannot~またはI can't~で表す。", "hint": "cannot = can't"},
        {"id": "g1-u5-conv-004", "type": "conversation", "japanese": "「手伝える？」と聞かれた", "scene": "お願い", "question": "Can you help me?", "choices": ["Sure, I can.", "Sure, I do.", "Sure, I am.", "Sure, I will."], "correctAnswer": "Sure, I can.", "difficulty": "beginner", "explanation": "Can you~?には「Sure, I can.」「Of course.」などで答える。", "hint": "Sureで快諾を表す"},
        {"id": "g1-u5-conv-005", "type": "conversation", "japanese": "「英語話せますか」と聞きたい", "scene": "初対面", "question": "How can I ask if someone can speak English?", "choices": ["Can you speak English?", "Do you speak English?", "Are you speaking English?", "Did you speak English?"], "correctAnswer": "Can you speak English?", "difficulty": "beginner", "explanation": "「〜できますか」はCan you~?で表す。能力を尋ねる基本形。", "hint": "Can you~?で能力を尋ねる"}
    ]

def main():
    """メイン処理"""
    # Unit 5のみ先に生成
    unit5 = create_unit5()
    
    output_dir = os.path.join(os.path.dirname(__file__), '..', 'public', 'data')
    os.makedirs(output_dir, exist_ok=True)
    
    # Unit 5を保存
    output_path = os.path.join(output_dir, 'grammar_grade1_unit5.json')
    with open(output_path, 'w', encoding='utf-8') as f:
        json.dump(unit5, f, ensure_ascii=False, indent=2)
    
    print(f"✅ Unit 5（助動詞can）60問を生成しました")
    print(f"📊 内訳: 穴埋め15、並び替え15、言い換え15、動詞変化10、日常英会話5")

if __name__ == '__main__':
    main()
